### ISSUE TITLE
Better chaining / card order selection

### ISSUE THREAD

**Issue by saiyansoul** [29988122/Fate-Grand-Order_Lua#10]
Any plan to add more feature to rhis?Especially auto skill?or other?

**Comment by 29988122** [comment]
Not at the moment.
As you can see, the behavior of the script is not "smart", you still have to adjust your team member to 周回(farm). And auto skill will only increase the length of every turn, make it more inefficient.

**Comment by saiyansoul** [comment]
Hmmm.. you have a point there.
Well,Hope that someone can contribute in the future.Thank you!
