### ISSUE TITLE
Add auto support selection to autoskill lists.

### ISSUE THREAD

**Issue by 5urmount** [29988122/Fate-Grand-Order_Lua#101]
Make it so that we can choose one list during the menu which contains both auto support and autoskill, so that I can run separate lists that farm for exp (searches for chaldea lunchtime) and qp (searches for mona lisa) in the same script.

**Comment by TryBane** [comment]
I was literally about to add this suggestion. I'll take a look at the auto-skill code that uses a list and see about implementing something similar for the support select. Shouldn't be too complicated.

**Comment by 29988122** [comment]
@TryBane 
If you're going to touch that, feel free to modify the behavior between BOTH autoskill AND autoskill_list.

I was writing for myself so the implementation was rather quick and dirty.

**Comment by TryBane** [comment]
I have a version of the enhancement ready. Just need to figure out how to submit it as a pull request?

First time submitting a pull request to a git that wasn't my own.

**Comment by TryBane** [comment]
I can always adjust it a different way too. Here I linked the support and CE selection to the Auto Skill selection used. But I can also allow you to list Support and CE selections that you can choose independently from one another.

For instance, say you have Waver in your support selection. And right now you're farming for the Cheese Cakes for the NA event currently ongoing. I could make it so that instead of making a completely new support selection, you will have another dialog box open asking you to select support, then CE. It would be more modular, expanding scalability of this script.

**Comment by 5urmount** [comment]
One thing I think you should consider is an option to run indefinitely, so once you pick a list, it doesn't keep asking you every instance refresh.

**Comment by TryBane** [comment]
Hmmm, it shouldn't be asking every instance refresh. Only when you first
initiate it.

**Comment by 5urmount** [comment]
Weird, might have ran the wrong script. Will report back when enough AP has regenerated.

**Comment by TryBane** [comment]
Yeah no problem. If there is an issue, then give me the details of what is
happening. I'm running it right now, specifically running skill set 7.

Give any details such as how many swipes you set it to, what type of
support (first, preferred, etc) and when it actually happens like every
run, whenever you run out of AP, etc.

On Nov 29, 2018 23:06, "5urmount" <notifications@github.com> wrote:

Weird, might have ran the wrong script. Will report back when enough AP has
regenerated.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/29988122/Fate-Grand-Order_Lua/issues/101#issuecomment-443084198>,
or mute the thread

**Comment by MathewSachin** [comment]
I tried a simpler implementation using `Lua Tables` so the script remains more readable for the user.
Also, not limited to the use of 10 settings.
I created an array called `Party_List` which replaces `AutoSkill_List` which may or may not include AutoSupport options.
The user is not required to specify AutoSupport settings for all parties, if not specified the defaults set outside parties like in the original script are used.

You can view the changes here:
https://github.com/29988122/Fate-Grand-Order_Lua/compare/master...MathewSachin:custom

The script to run is `FGO_EN_CUSTOM.lua` which then calls `custom.lua`.

You guys have done an awesome job on the script and it makes my day to day farming a breeze.
Let me know your thoughts on this.

**Comment by reconman** [comment]
@MathewSachin Your feature is really awesome, it makes life much easier. I'm using it every day for farming. I would gladly replace the Support List with your feature, thus turning your FGO_EN_CUSTOM.lua into FGO_EN_REGULAR.lua.

But I'm pretty fresh in the project and don't have much influence.

@potchy Any thoughts from your side?

**Comment by reconman** [comment]
@29988122 @TryBane @potchy Can I throw out the Autoskill_List and replace it with MathewSachin's approach?

It's similar to Autoskill_List, but each option in the popup also includes settings for the support selection. So it doesn't make sense to keep the old reduced logic.

Users who use the old feature will have to migrate to the new feature, but I doubt that many people use the old feature.

**Comment by MathewSachin** [comment]
@reconman This might seem unrelated, but, I would also like to ask if separate files are really required for different regions. I mean the user could specify the `GameRegion` in their script and we could do something like the following in `regular.lua`:

```
StageCountRegion_List = {
    "EN" = Region(1722,25,46,53),
    "CN" = Region(1722,25,46,53),
    "JP" = Region(1722,25,46,53),
    "TW" = Region(1710,25,55,60),
}

SupportSwipeEndClick_List = {
    "EN" = Location(35,390),
    "CN" = Location(35,390),
    "JP" = Location(35,350),
    "TW" = Location(35,390)
}

StageCountRegion = StageCountRegion_List[GameRegion]
SupportSwipeEndClick = SupportSwipeEndClick[GameRegion]
```

**Comment by 29988122** [comment]
> 
> 
> @reconman This might seem unrelated, but, I would also like to ask if separate files are really required for different regions. I mean the user could specify the `GameRegion` in their script and we could do something like the following in `regular.lua`:
> 
> ```
> StageCountRegion_List = {
>     "EN" = Region(1722,25,46,53),
>     "CN" = Region(1722,25,46,53),
>     "JP" = Region(1722,25,46,53),
>     "TW" = Region(1710,25,55,60),
> }
> 
> SupportSwipeEndClick_List = {
>     "EN" = Location(35,390),
>     "CN" = Location(35,390),
>     "JP" = Location(35,350),
>     "TW" = Location(35,390)
> }
> 
> StageCountRegion = StageCountRegion_List[GameRegion]
> SupportSwipeEndClick = SupportSwipeEndClick[GameRegion]
> ```

They tend to have different flow most of the time - Japanese (not exclusive to Delightworks) mobile games will constantly add inelegant UI buttons, UI flows, ending screen windows....clutter.

Anyway, and the event (extra reward window) is merely only one of the cases - most of the time the system change will break the script in other versions.

It happened fairly frequently...although there * will * be a better way handling it - I guess that's up to you guys drafting a better way.

**Comment by MathewSachin** [comment]
@29988122 I think you're misunderstanding what I said.
I'm only talking about merging the starting script where the user specifies his/her settings.
This is the only place where region-specific files are being used.

Region-specific UI elements are already being handled well using common files like for e.g.: 

https://github.com/29988122/Fate-Grand-Order_Lua/blob/ac7e6dc8310d5b02da272bf2d58eeff6f192a657/regular.lua#L163-L180

**Comment by 29988122** [comment]
> 
> 
> @29988122 I think you're misunderstanding what I said.
> I'm only talking about merging the starting script where the user specifies his/her settings.
> This is the only place where region-specific files are being used.
> 
> Region-specific UI elements are already being handled well using common files like for e.g.:
> 
> https://github.com/29988122/Fate-Grand-Order_Lua/blob/ac7e6dc8310d5b02da272bf2d58eeff6f192a657/regular.lua#L163-L180

I'm sorry, now I get it(probably). You are right and I support the change.

**Comment by potchy** [comment]
> 
> 
> @29988122 @TryBane @potchy Can I throw out the Autoskill_List and replace it with MathewSachin's approach?
> 
> It's similar to Autoskill_List, but each option in the popup also includes settings for the support selection. So it doesn't make sense to keep the old reduced logic.
> 
> Users who use the old feature will have to migrate to the new feature, but I doubt that many people use the old feature.

I think it's great and you can extend it to even more settings than the ones available in his branch.

**Comment by MathewSachin** [comment]
@reconman Can I start work on this or have you already started?

**Comment by MathewSachin** [comment]
I would like to suggest one more thing, since we are changing support config anyway

Should we do:
```
{
    Name = "Party 1",
    Skill_Command = "123,#,456",
    Support_SwipesPerUpdate = 10,
    Support_MaxUpdates = 3,
    Support_FriendsOnly = 0,
    Support_FriendNames = "",
    Support_SelectionMode = "preferred",
    Support_PreferredServants = "",
    Support_PreferredCEs = Lunchtime,
    Support_FallbackTo = "first"
}
```

or:
```
{
    Name = "Party 1",
    Skill_Command = "123,#,456",
    Support =
    {
        SwipesPerUpdate = 10,
        MaxUpdates = 3,
        FriendsOnly = 0,
        FriendNames = "",
        SelectionMode = "preferred",
        PreferredServants = "",
        PreferredCEs = Lunchtime,
        FallbackTo = "first"
    }
}
```

The second one seems less verbose to me.

**Comment by reconman** [comment]
You can start working, didn't expect you to become so active.

You have to keep in mind that someone might want to use support selection while not wanting to set SkillCommands. That's possible with the current regular script.

**Comment by MathewSachin** [comment]
> didn't expect you to become so active

Well, I'm sitting at home due to lockdown regarding coronavirus.
Thought I could use that time to contribute to some projects I regularly use as a way of thanking them.

> You have to keep in mind that someone might want to use support selection while not wanting to set SkillCommands. That's possible with the current regular script.

Yeah, that's pretty important

**Comment by MathewSachin** [comment]
#351 has now been merged, this issue can be closed.
