### ISSUE TITLE
Preferred support selection chooses non-max limit break craft essences.

### ISSUE THREAD

**Issue by 5urmount** [29988122/Fate-Grand-Order_Lua#104]
Tried using the included mona_lisa.png, but it kept choosing non-MLB versions as long as they appeared before MLB ones.

**Comment by potchy** [comment]
Post your configuration file.

**Comment by potchy** [comment]
Okay, to enforce that you want a MLB CE, prepend the image name with a *, like this:
`Support_PreferredCEs = "*mona_lisa.png"`
