### ISSUE TITLE
Issue selecting supports

### ISSUE THREAD

**Issue by raspberrytealeaf** [29988122/Fate-Grand-Order_Lua#106]
Hiya,

I'm using the waver face cards and holy night supper included from your files. It works the majority of the time, but sometimes I will get an error:

![image](https://user-images.githubusercontent.com/7444536/49131684-559a6c80-f296-11e8-9055-2d2da89287dc.png)
![image](https://user-images.githubusercontent.com/7444536/49131694-5a5f2080-f296-11e8-888d-5605411259b6.png)

I have no idea what triggers this, but I think it's related to scrolling down / swiping on the friends list. When there's a Waver w/Holy Night Supper at the 1st or 2nd slots, it seemingly has no issues selecting him.

Any suggestions on how to fix this?

**Comment by ryuga93** [comment]
The error happens when the scrolling reached the end of the support list, causing the boundary to fall out of expected range.

You can reduce the value of `Support_SwipesPerUpdate`, maybe to 4 to fix it.

@potchy Maybe instead of throwing the error, how about catching it and toast it as notification and proceed to update the support list?

**Comment by raspberrytealeaf** [comment]
Ah, I see. I'll reduce the swaps. Thanks.

**Comment by potchy** [comment]
Just to confirm: the error appeared when the script found the right match in the 3rd support slot? I mean 3rd visible on screen, not total.

**Comment by ryuga93** [comment]
![image](https://user-images.githubusercontent.com/6499824/49153149-e2edc780-f34f-11e8-896b-977f9f3de207.png)
It throws error when the second visible servant is matched regardless the CE. For the image above, I'm trying to get Ishtar with the 5 Start Gacha CE.

**Comment by raspberrytealeaf** [comment]
@potchy It seems to occur after it swipes down a few times and needs to refresh cause it doesn't find the servant + CE you want. I think what @ryuga93 said is on point. My screen res is whatever the default NOX resolution is.

**Comment by TryBane** [comment]
@raspberrytealeaf While working on a fix, it might be better to limit the number of swipes in the settings in the meantime to keep it from throwing that error.

**Comment by potchy** [comment]
I just pushed a fix for this issue.
Please help check if it has indeed been solved before I close it. 😄

**Comment by raspberrytealeaf** [comment]
I've been running the updated script for a while w/more siwpes and so far I haven't encountered the same error. Thanks!
