### ISSUE TITLE
 (Extra window appearing, script in wrong state issue)Permenant fix of script accidently clicked on extra status window

### ISSUE THREAD

**Issue by 29988122** [29988122/Fate-Grand-Order_Lua#109]
Steps to reproduce:
1. Make Danger / Servant target switching active. (Default active if I recall correctly.)
2. Script enters Battle 3/3.
3. ONLY WHEN the danger target is at the right-most position of the battlefield, this bug happens.
4. The script will "switch" to the right-most target.
5. Since the game already has its default target on the right-most target, another click on it will pop out the enemy status window.
6. Stuck, yay.

Possible cause:
When you click on the target that you've already selected as the target, the enemy status window will pop out and f you up.

Workaround:
Just check if there's a cross icon (close window icon) on the certain position of the screen whenever you selected a target. Not recommended.

How to fix it permanently:
*Client language compatibility must be considered if possible*
There are 5 kinds of extra windows that will mess up our script routine.
1. Team wiped out window.
2. Master skill (master cloth skill) window.
3. Servant skill window (if the option's on/if the skill's on CD).
4. Enemy status window.
5. Servant status window.
Extra. DATA HAS BEEN UPDATED WINDOW (sometimes it happened during your battle, and, bang you've been sent back to the title screen. Thanks, Delightworks!)

I guess we'll have to figure out a way to handle them once and forever.
I have no idea how to write an Observer, or if it's possible in the Lua script engine. 
FYI: coroutine lib is not working http://ankulua-tw.boards.net/thread/691/bug-ankulua-coroutine

=
Side notes: I have no idea it's because I updated Nox to 6.2.5.3, or I updated Ankulua to 8.0.5.
The performance of recognition is VERY FAST now. You guys gotta give it a try.

**Comment by TryBane** [comment]
You only open up that menu when you press and HOLD on them. I have never had an instance where just clicking on an already selected enemy produced the status menu for them. The lua scripts way of pressing on screen may produce a similar affect though.

This is just a bit of information to help if it does.

**Comment by 29988122** [comment]
@TryBane 

That's why we'll have to deal with it beforehand - sooner or later it will be applied to other clients.

**Comment by TryBane** [comment]
Ah I see, you make a good point good sir!
