### ISSUE TITLE
吃蘋果後會卡住

### ISSUE THREAD

**Issue by lamlart0619** [29988122/Fate-Grand-Order_Lua#11]
設定沒體力吃蘋果後會卡在選完角色進關卡之前

**Comment by 29988122** [comment]
請問是使用 1.4.3的版本嗎？十天前的release最新版

然後是臺版還是哪國版本 XD
==
目前其中一些卡住的原因是因為大家的手機/模擬器速度不同，所以我可能點得太快了
之後考慮增加一個選項讓人調整, 切換每下按鍵的容許值

會變成按鍵快-容易卡住 按鍵普通-折衷 按鍵慢-幾乎不會卡住

**Comment by lamlart0619** [comment]
是台灣版最新的，我已經把夜神模擬器速度調快了換成4個CPU再跑，可是還是卡在選完角色進關卡前畫面

**Comment by 29988122** [comment]
我看了一下code, 找不到問題, 手邊也沒有臺灣版可以測試..或許明天做一下速度調整選項

是用regular檔案來刷沒錯吧？
請問是打活動嗎？還是一般種火關卡也會卡？
可以的話您如果能把出錯的畫面給錄下來，我會比較容易發現問題~

如果是活動卡的話，可能是有額外的視窗要點按，就需要我手動去更新
