### ISSUE TITLE
Tools to use to capture CE images without leaving android environment

### ISSUE THREAD

**Issue by TylerNodell** [29988122/Fate-Grand-Order_Lua#110]
I was wondering what tools would be the most effective in order to capture images from screenshots without exporting them off the phone for editing on a pc.

**Comment by potchy** [comment]
You can try [this](http://ankulua.boards.net/thread/531/tool-snapyourscript), but I've never used it personally.

**Comment by TryBane** [comment]
I've done my editing of images on mobile using oie (online image editor) which you can find [here](http://www.online-image-editor.com/)

**Comment by reconman** [comment]
See https://29988122.github.io/Fate-Grand-Order_Lua/#/support-image-maker
