### ISSUE TITLE
Cannot refill ap / Conflict between refilling apples and AP ran out

### ISSUE THREAD

**Issue by ParasiteEve** [29988122/Fate-Grand-Order_Lua#112]
So maybe it's a problem with my settings:
I have autoskill on for a1b1c1d1e1f1g1h1i1456.

When I run out of AP after a battle, when the script restarts and tries to enter a 40ap node; when say I have 30 ap, it will not refill but somehow end up in the AP RAN OUT exit script code instead. However, if I start the script at the menu, it will refill AP fine but that involves a manual start - any ideas how to fix? The Use Stones settings is correct and works but after a battle when the script tries to restart it fails to restart properly.

**Comment by TryBane** [comment]
How many stones/apples do you have it set to use?

**Comment by ParasiteEve** [comment]
1 apple a time

**Comment by TryBane** [comment]
Yes, that is why. That setting doesn't change how many apples it consumes at once, it determines how many times it will refill your AP.

For instance, if you set it to 3, it will run till it hits the refill AP screen. After it hits, it will use an apple, thus using 1 of those 3. Now it will run until it runs out of AP again, and when it gets to the refill screen, it will consume another apple, totaling 2/3. And after the 3rd time, it will exit the script at the AP refill screen.

I hope this helps out my man.

**Comment by TryBane** [comment]
It would also be great for you to reply if it did help, so that we can close the issue.

**Comment by ParasiteEve** [comment]
Just testing it out now, with respond

**Comment by ParasiteEve** [comment]
It works now, thank you so much TryBane. Please close ticket.
