### ISSUE TITLE
Using silver and bronze apples

### ISSUE THREAD

**Issue by ParasiteEve** [29988122/Fate-Grand-Order_Lua#116]
I looked at Regular.lua and it looks like it clicks a specific location for Gold Apples; would it be possible to pick Silver and Bronze apples? Thanks.

**Comment by TryBane** [comment]
Yes, it is definitely possible. It is something I plan to have implemented once we do an overhaul of the current script.

**Comment by potchy** [comment]
@TryBane added this option. See [the updated documentation](https://github.com/29988122/Fate-Grand-Order_Lua#autorefill) for details.
