### ISSUE TITLE
Script occasionally fails while scrolling to the bottom of support select.

### ISSUE THREAD

**Issue by TheIanator** [29988122/Fate-Grand-Order_Lua#117]
Has happened to me only three times over many hours of running the script, I've included screenshots of the full error and of the screen two of the times it has failed. Perhaps it's due to finding the servant it's looking for but halfway between the two spots it's looking for it?

![screenshot_20181203-195050](https://user-images.githubusercontent.com/29805524/49489374-e11c7c00-f807-11e8-8bf1-3e692f9f4e87.png)
![screenshot_20181203-195057](https://user-images.githubusercontent.com/29805524/49489375-e2e63f80-f807-11e8-8436-194397c0fdfc.png)
![screenshot_20181203-195102](https://user-images.githubusercontent.com/29805524/49489378-e4176c80-f807-11e8-870e-2012329905fa.png)
![screenshot_20181203-195108](https://user-images.githubusercontent.com/29805524/49489380-e5e13000-f807-11e8-8b06-7e83a40a8f77.png)
![screenshot_20181204-204717](https://user-images.githubusercontent.com/29805524/49489381-e7125d00-f807-11e8-96a1-74f8de54bf48.png)

**Comment by potchy** [comment]
Are you using the latest code base? I mean code base, the one you get when you click "Clone or download" in the main page, not the one in the release tab. I'm asking because I'm sure I already fixed this in #106.

**Comment by TheIanator** [comment]
That's probably it, I am using the latest release. Sorry about that.
