### ISSUE TITLE
Enemy Servant Targeting

### ISSUE THREAD

**Issue by TheOnlyZii** [29988122/Fate-Grand-Order_Lua#119]
so if there are 3 servant on the field the script will automatically select the 3rd servant (left most) by default the game would select servant 1 (right most) 
is there any way to disable this?
or disable the servant/danger targeting altogether

thanks

**Comment by Alucardnr** [comment]
battleLogic.lua-->ChooseTarget-->Change every param to Target3Click in click()

**Comment by TheOnlyZii** [comment]
like this ?

sorry im not an adept coder
`function TargetChoose()
	t1 = Target1Type:exists(GeneralImagePath .. "target_servant.png")
	usePreviousSnap(true)
	t2 = Target2Type:exists(GeneralImagePath .. "target_servant.png")
	t3 = Target3Type:exists(GeneralImagePath .. "target_servant.png")
	t1a = Target1Type:exists(GeneralImagePath .. "target_danger.png")
	t2a = Target2Type:exists(GeneralImagePath .. "target_danger.png")
	t3a = Target3Type:exists(GeneralImagePath .. "target_danger.png")
	if t1 ~= nil or t1a ~= nil then
		click(Target3Click)
		toast("Switched to priority target")
		TargetChoosen = 1
	elseif t2 ~= nil or t2a ~= nil then
		click(Target3Click)
		toast("Switched to priority target")
		TargetChoosen = 1
	elseif t3 ~= nil or t3a ~= nil then
		click(Target3Click)
		toast("Switched to priority target")
		TargetChoosen = 1
	else
		toast("No priority target selected")
	end
end`

**Comment by Alucardnr** [comment]
Yes, try it

**Comment by TheOnlyZii** [comment]
Nice its working as intended thanks

**Comment by potchy** [comment]
I bet it's because you wanted to hit Santler instead of Caesar. :)

**Comment by TheOnlyZii** [comment]
Those AOE NP cleaved my whole party, making the run unnecessarily longer

**Comment by 29988122** [comment]
>potchy
I bet it's because you wanted to hit Santler instead of Caesar. :)

XD Nice coincidence

Meanwhile JP server player(me) understand nothing! Too long ago for me.

**Comment by Shiien72** [comment]
d
