### ISSUE TITLE
國服/B服版本需要有人抓圖, 我才能改一個可用的版本出來

### ISSUE THREAD

**Issue by 29988122** [29988122/Fate-Grand-Order_Lua#12]
我這兒沒有b服的號...

抓圖細節請看首頁的readme，我裡邊有講方法
基本上，需要抓的圖仿照現有的其他服的版本（要在哪個屏幕抓圖，抓下來之後要怎麼resize等），都抓好給我我改一個版本出來，您測試沒問題我就放上去release了。
  
或是您真的不懂的話，在這邊回應，我能夠給您詳細的指示。

**Comment by bloodvulture** [comment]
我最仅若是有时间或许可以帮您。。我先去读读readme

**Comment by bloodvulture** [comment]
还是比较疑惑抓取的图大概需要多大呢。。。看您得解释是抓屏后resize，然后crop the desired pattern这一步不是特别明白。。。直接截下来差不多一样的大小还是怎样

**Comment by ryuga93** [comment]
先抓屏后resize，需要的图参照image文件夹，参照image_TW吧，也许和B服一样。

基本上就是：
看image_TW文件夹的png有哪些图，再和B服里的画面对比，然后抓屏再resize。比如battle.png，到战斗画面抓屏，resize。
如果文件夹的某些png和B服里的画面一致，创个txt把它们列下来，然后和其他图一起给我们。

**Comment by bloodvulture** [comment]
get，我这两天就去搞

**Comment by 29988122** [comment]
@bloodvulture 
謝謝啊親 國服其他小夥伴們就靠你了 :)

**Comment by bloodvulture** [comment]
没事，我今晚有正好有时间弄=。=

**Comment by bloodvulture** [comment]
那个questreward这个图片我似乎没找到对应的位置，想问下具体在哪？

**Comment by 29988122** [comment]
每天刷種火會拿到綠方不是麼

那個畫面就是了, 任務獎勵的畫面

**Comment by bloodvulture** [comment]
ok，谢谢

**Comment by ryuga93** [comment]
首次通关的奖励画面

**Comment by bloodvulture** [comment]
以及target-servent也没找到=。=是剧情关卡的boss从者带的标志吗

**Comment by ryuga93** [comment]
体力40的素材关卡boss从者也可以

**Comment by 29988122** [comment]
坑爆了
https://www.ptt.cc/bbs/TypeMoon/M.1515922263.A.F97.html

我圖都抓好了結果給我改回來了 )#($*)#
測試都懶得測了...

**Comment by bloodvulture** [comment]
我前几天也抓好了，除了一个boss的。。结果这一更新字体和图标都改了，还改丑了:(

**Comment by 29988122** [comment]
媽個巴子，同樣是英文但是字型不同，對上的位置也不同

https://imgur.com/a/NdN42

我在那朦看了半小時才發現這件事.....真的是夠坑
