### ISSUE TITLE
Selecting support by np name text instead of portrait?

### ISSUE THREAD

**Issue by raspberrytealeaf** [29988122/Fate-Grand-Order_Lua#120]
I have my script set to select waver with mlb holy night, but I found it recently trying to use an ilya support also with mlb holy night when there was a waver right under her.

Is it possible to select supports based on np name instead of detecting face portrait similarity? With the older version of support selection, I had it set to a cropped image of wavers np name text and never had it mess up like this. This doesn't require 4 face portrait pictures either.

Alternatively, since the script tried to select ilya with mlb ce, does this mean it prioritizes ce over face portrait? Can that be adjusted?

**Comment by potchy** [comment]
I didn't understand very well, but I suppose you're talking about about this bug I fixed two days ago in 4dcae3e

**Comment by raspberrytealeaf** [comment]
What's happening is:

- I have my script set to select waver with mlb hns as my support
- At the top of the support list, there's an ilya with mlb hns
- Under ilya is a waver with mlb hns
- The script should select waver, but it selects ilya instead

**Comment by potchy** [comment]
Try the latest version of the code base.
If it still doesn't work, upload both your config file and a screenshot of your support list with Illya and Waver visible.

**Comment by raspberrytealeaf** [comment]
I updated it and used it for the end of the event. No issues as far as I can see. Thanks.
