### ISSUE TITLE
How to edit the script?

### ISSUE THREAD

**Issue by zerato110** [29988122/Fate-Grand-Order_Lua#122]
Whenever I try to edit the script, for example, delete a "0" and replace with a "0" from my keyboard, the script did not run but keep saying "Syntax error." I used both notepad and Sublime Text, but it still does not work. What should I do to solve the problem? I am using NOX player.

**Comment by potchy** [comment]
Read this:
https://github.com/29988122/Fate-Grand-Order_Lua/issues/99#issuecomment-441133426

AnkuLua (or Lua itself) doesn't support files encoded in UTF-8 with BOM.
