### ISSUE TITLE
Stage Recognition the 2nd.

### ISSUE THREAD

**Issue by Keichide** [29988122/Fate-Grand-Order_Lua#123]
I already saw the 2 Tickets we had here in the past about the Stage Recognition Bug.. This Time it's a little different... I have my AutoSkills set to "aei,#,d1,4" which would for my understanding fire the NP of Servant 1 in the first Turn on Battle 2, but the Script needs to long to see if the second battle already started and gives me the "Battle 2/3" screen after the second turn on the second Battle. Same with the third Battle... It takes 1 whole turn until he recognized that it's already in the next Battle and not in the previous one. And yes i'm using 2.3 already.

**Comment by potchy** [comment]
So? Why did you close this issue? Did you solve it or not?

**Comment by Keichide** [comment]
I think so... Just changed the order a bit and put the skill in the previous route and the np release right after the second Round.. Which solved it... Had probaly something todo with the extra semikolon which the scripts interprets as another turn.

**Comment by potchy** [comment]
Oh, right.
There are two turns in `d1,4` because of the semicolon.
