### ISSUE TITLE
Disable Targeting?

### ISSUE THREAD

**Issue by ineedhelp6969** [29988122/Fate-Grand-Order_Lua#126]
Having targeting on puts me into the extra status window bug, and im just wondering how to disable it all together, can't seem to figure it out

**Comment by potchy** [comment]
There should be an option to control auto target, so I'll reopen this and mark it as an enhancement.

**Comment by 29988122** [comment]
The option has been added in this commit:
https://github.com/29988122/Fate-Grand-Order_Lua/commit/057fcca2062b80bf3b944154a332f0c62bda5462

Also, the servant selection bug has been solved in the previous commits, since I'm also a JP server user.
