### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by MoeJoe1** [29988122/Fate-Grand-Order_Lua#128]
http://prntscr.com/lvvt3d

Got this whenever i turn on the JP_regular.lua http://prntscr.com/lvvtal

Nothing happens after, i don't know if i did something wrong or if something is up.

Please help.

**Comment by potchy** [comment]
That black message is normal. Just click OK.

**Comment by MoeJoe1** [comment]
Ok that's good, but like i said nothing happens after. Like the script doesn't start or anything. I tried doing the menu section and the battle section. Nothing moves

**Comment by potchy** [comment]
What's your device resolution? Please post a full screenshot.
The only aspect ratio currently supported is 16:9. See #40 for details.

**Comment by ArianTerra** [comment]
I have same problem. My phone is Xiaomi Mi A2 Lite with 19:9 aspect ratio and 1080x2280 pixels. I`ve tried to change my resolution to 1280x720, but it still don`t work.

**Comment by potchy** [comment]
Other aspect ratios are supported now, but devices with a notch still are not.
See #155 for details.
