### ISSUE TITLE
Error when editing English lua

### ISSUE THREAD

**Issue by Toastygirl** [29988122/Fate-Grand-Order_Lua#129]
Hey, 

No idea what I'm doing wrong this time but whenever I change anything in the English lua file for FGO it spits out this error no matter what I've changed. Even if it's just enabling auto-battle, refills or anything else. 

Please help a girl out! 

https://i.imgur.com/VSwP82K.png

Using Nox

**Comment by TylerNodell** [comment]
Which version are you using? Additionally if you download the default file and use it do that not error out?

**Comment by Toastygirl** [comment]
> Which version are you using? Additionally if you download the default file and use it does that not error out?
> 
> Could you also attach your edited lua file to your response.

Nox Version: 6.2.6.0 - Yeah, if I use the default one it works fine. The instant I use notepad to edit even a 0 to a 1 on refill or just NP use to spam it gives that error.

https://www.dropbox.com/s/1acitta7w8oosus/FGO_EN_REGULAR.lua?dl=0

**Comment by potchy** [comment]
See [here](https://github.com/29988122/Fate-Grand-Order_Lua/issues/99#issuecomment-441133426).
@29988122 we should add this to the documentation. Every now and then someone asks about this. @_@

**Comment by Toastygirl** [comment]
That's fixed it. I downloaded Notepad++. 

Sorry for the silly mistake.

**Comment by potchy** [comment]
No worries.
I'm just as surprised that UTF-8 with BOM isn't supported.

**Comment by 29988122** [comment]
@potchy 
>we should add this to the documentation. Every now and then someone asks about it. @_@

Sure. Will add it .

I wonder if we can change the default user settings *.lua files to utf8 without BOM - thus unless they use other text editor, windows user should be able to edit it directly via notepad.exe without BOM being added.

OR THAT IS ALREADY THE CASE NOW. XD
I was using older version on my side(cause JP server target selection issue), so can't confirm now.

**Comment by potchy** [comment]
Windows Notepad always include the BOM when saving in UTF-8, so there's not much we can do. :c
