### ISSUE TITLE
nox playerでの使い方について。

### ISSUE THREAD

**Issue by 888kk** [29988122/Fate-Grand-Order_Lua#13]
日本語での質問よろしいでしょうか。

nox player6.0.0でFate-Grand-Order_Luaを使いたいのですが、上手くインストール出来ません。

noxにankuluaをインストールしてusbデバッグを有効にした後、
PCからNox\bin\nox_adb.exe” connect 127.0.0.1:62001でnoxへ接続しました。
\ama_daemon\nox_player.run.batを実行すると、"Daemon installation complete."と表示されました。

次に、noxでUSBデバッグを無効にしてからankuluaを起動すると、
"Daemonが発見しました"と表示されます。
しかし、"スクリプトを選ぶ"から.luaファイルを選ぼうとしても
/sdcard/以下のどのフォルダにも.luaファイルが見つかりません。

これはインストールに失敗したのでしょうか？
何か思い当たる原因があれば教えて下さい。

**Comment by 29988122** [comment]
私の説明不足ですね、反省します。近日マニュアルを補足します。

ダウンロードしたファイルはPC、エミュ（あるいはスマフォ）の両方に置かなければなりません。
PCの方は毎回daemonのインストールが必要で、スマフォの方はLuaスクリプトのアクセスです。

つまり
https://www.bignox.com/blog/how-to-sharecopy-files-between-nox-app-player-and-your-computer/
のように、シェアフォルダ機能を使って、Fate-Grand-Order_Luaフォルダをあそこ（ C:\Users\%username%\Documents\Nox_share ）にコピーし、そしたらNOXの中の/mnt/sharedに出て来るじゃないのかな。

説明不足、余計な手間をおかけしてすみません…

**Comment by 888kk** [comment]
私の理解が足りてなかったです。
エミュにFate-Grand-Order_Luaフォルダをコピーしたら
ankuluaからスクリプトファイルを選択できました。
スクリプトは動作しました。
回答ありがとうございます。

**Comment by 888kk** [comment]
度々すみません。
noxでのスクリプトの動作について質問です。

種火集めクエスト初級をスクリプトで周回してみましたが、
APが足りている時は実行に成功するのですが、
APが不足している時は、
"AP回復"画面を開いて石を選択した状態で、
スクリーンの一定の場所をタップし続けてループしてしまいます。

ループする時に以下のメッセージが出ます。
" Will only select servant/danger enemy as noble phantasm
target, please check github futher detail"

APがクエスト周回できる数値まで回復しても
ループから抜けられず石を選択し続けてしまいます。
スクリプトの設定が間違っているのでしょうか?

Auto refillの設定:
Refill_or_Not = 0
Use_Stone = 0
How_Many = 5

noxの端末設定:
解像度:1280x720
端末型番:samusung

ループ発生した時のスクリーンショットを撮影しました
https://i.imgur.com/ulevxCj.jpg

**Comment by 29988122** [comment]
そうですね、まず体力が使い果たしたらそこで止まるのが普通ですね。
（私のスクリプトでは）停止条件は設定していないから、そこでstuckするのが正常です。
クリックしてる箇所は予めテストしていたので、誤って石を使ったりとかの誤作動はないでしょう、ご心配なく。

もし自然体力回復を前提にしての周回が所望なら、残念ながら今はこういう機能実装していないです。
一度に満タンを使うか、石、林檎を使って一気に周回するかの二択ですね。

本当にそうしたいのなら、会社、学校で体力回復時間を計算し、teamviewerとかのリモートコントロールソフトウェアを使って家にいるnoxを操作（スクリプトを一旦ストップして、ステージセレクト画面に移行してスクリプトを再開する）する方が今の段階での解決策はですね。

==
ちなみにRefill_or_Not = 0を1にすると、その画面でストップすることなく、林檎．石を使って周回し続けます。
