### ISSUE TITLE
RunTime Error at start of battle

### ISSUE THREAD

**Issue by bakuadachi** [29988122/Fate-Grand-Order_Lua#131]
Attempting to run through story mode with the script; I have daemon installed properly and it loads into the battle fine, once the battle starts I get this error though. 

I've tried adding "Settings:set("MinSimilarity", 0.5)" without quotations to regular.lua but still the same error. 

![image](https://user-images.githubusercontent.com/45959309/50134444-f8268980-025d-11e9-9955-0249de4ca0a8.png)

**Comment by potchy** [comment]
See #87.
Update to AnkuLua's latest version.

- [Trial](https://play.google.com/store/apps/details?id=com.appautomatic.ankulua.trial&hl=pt_BR)
- [Pro](www.dropbox.com/s/6jn4c2rh3j1t3wx/AnkuLua.v8.1.0.apk?dl=1)
