### ISSUE TITLE
Support selection issue in Solomon

### ISSUE THREAD

**Issue by TryBane** [29988122/Fate-Grand-Order_Lua#133]
For everyone's attention, Support selection is not going to work as is because of the CE being overlapped with bonus amount!

You will need to decrease the variable for how much it needs to look like the image.

**Comment by Rajvir8** [comment]
Will it work if we only select Servants?

The Damage Percentage doesn't touch it after all.

**Comment by TryBane** [comment]
Yes, that is the solution I ended up using. Was at work. I posted that
original PSA as a warning but couldn't act on it till now. I just got home.

**Comment by Rajvir8** [comment]
I'm trying to save a picture of Kintoki in his Berserker form but I just keep failing.  I've already tried 6 of them at this point.  Any idea what I'm doing wrong?

**Comment by Rajvir8** [comment]
<blockquote class="imgur-embed-pub" lang="en" data-id="a/soFeirC"><a href="//imgur.com/soFeirC"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by TryBane** [comment]
There are a few steps to make sure you're following.

Did you take the initial screenshot and scale it to 1280x720?

After doing that is when you crop the image.

**Comment by Rajvir8** [comment]
No I didn't scale it to 1280X720, I'll have to look into changing how Nox saves it's screenshots and give it a shot.  Thanks for the advise.

**Comment by Rajvir8** [comment]
Double Checked it is 1280X720 already but I use Snipping Tool usually I'll screenshot it and then crop it instead this time.

**Comment by TryBane** [comment]
You can use online-image-editor. [Here](http://www.online-image-editor.com/) is a link. You can use it for Mobile as well. That's what I use.

**Comment by Rajvir8** [comment]
Thanks for the suggestion it worked perfectly.

**Comment by Rajvir8** [comment]
I'm currently using the default Fate English, is there one for farming the Demon Gods?

The opening is a bit long and because of that it missed my first two skills entirely, as it started clicking to early.

It also messed up on swapping my Team around but that was probably just me putting it in wrong.

I want to swap My Third Member for my Fifth Member.

I put in 32 and it failed completely.

**Comment by TryBane** [comment]
I had to make an adjustment as well. I will be adding this in for future raid events but make these changes:

In regular.lua do the following.

In the current one there is:
```lua
StartQuestClick = Location(2400,1350)
StartQuestWithoutItemClick = Location(1652,1304) -- see docs/start_quest_without_item_click.png
QuestResultNextClick = Location(2200, 1350) -- see docs/quest_result_next_click.png

--[[For future use:
	NpbarRegion = Region(280,1330,1620,50)
	Ultcard1Region = Region(900,100,200,200)
	Ultcard2Region = Region(1350,100,200,200)
	Ultcard3Region = Region(1800,100,200,200)
--]]
```

Make this slight adjustment:
```lua

StartQuestClick = Location(2400,1350)
StartQuestWithoutItemClick = Location(1652,1304) -- see docs/start_quest_without_item_click.png
QuestResultNextClick = Location(2200, 1350) -- see docs/quest_result_next_click.png

isFirstTurn = true

--[[For future use:
	NpbarRegion = Region(280,1330,1620,50)
	Ultcard1Region = Region(900,100,200,200)
	Ultcard2Region = Region(1350,100,200,200)
	Ultcard3Region = Region(1800,100,200,200)
--]]
```

Then further down in the permanent loop the current one is this:
```lua
while(1) do
	if MenuRegion:exists(GeneralImagePath .. "menu.png", 0) then
		toast("Will only select servant/danger enemy as noble phantasm target, unless specified using Skill Command. Please check github for further detail.")
		menu()
	end
	if battle.isIdle() then
		battle.performBattle()
	end
	if ResultRegion:exists(GeneralImagePath .. "result.png", 0) then
		result()
	end
end
```

Change it to this:
```lua
while(1) do
	if MenuRegion:exists(GeneralImagePath .. "menu.png", 0) then
		toast("Will only select servant/danger enemy as noble phantasm target, unless specified using Skill Command. Please check github for further detail.")
		menu()
	end
	if battle.isIdle() then
            if isFirstTurn then
                wait(15)
                isFirstTurn = false
            end
		battle.performBattle()
	end
	if ResultRegion:exists(GeneralImagePath .. "result.png", 0) then
		result()
                isFirstTurn = true
	end
end
```

**Comment by TryBane** [comment]
This should provide you with a long enough time buffer to account for multiple debuffs being applied and the length of the scene. You may need to keep an eye on it in case too many buffs are applied, but so far my game has been running for an hour without issues.

**Comment by Rajvir8** [comment]
Any chance you can provide the notepad, I assume your talking about editing FGO_EN_REGULAR.

But when I open it with Notepad++ I can't even find the start quest option to replace

**Comment by TryBane** [comment]
No, it is not FGO_EN_REGULAR, it is regular.lua which is found a bit lower if sorted by alphabet

**Comment by Rajvir8** [comment]
Ah my bad, I'll edit it now then as I found it

**Comment by Rajvir8** [comment]
I've replaced it, I'll make sure to test it in a minute as I'll need to reroot Nox so I can add the edited version.

But first do you know what could be wrong with my swap?

I'm currently using l32 for it

But it selects my fifth member/2nd Sub Member first and then clicks on my 4th member/1st sub members and then just stalls out.

**Comment by TryBane** [comment]
l32? or x32?

**Comment by Rajvir8** [comment]
l32 as that's the master skill for it

**Comment by TryBane** [comment]
you need to use x32
x is specifically made to allow the process of selecting a sub and non-sub member. "l" will act like a normal master skill and try to use it on 1 servant.

**Comment by Rajvir8** [comment]
Thanks for the help, it worked perfectly.

Everything seems like it's running properly now.

**Comment by TryBane** [comment]
Awesome. I'll close this now

**Comment by potchy** [comment]
It's better to leave this open at least until Solomon ends.
I'm sure people will keep asking about it.

**Comment by TryBane** [comment]
Ah, fair point. My bad.

**Comment by potchy** [comment]
By the way, later on, we should change `battle.png` to this:
![screenshot_20181220-170121](https://user-images.githubusercontent.com/4316326/50350875-a153d500-0527-11e9-806e-306ad8835911.png)

It's more guaranteed that the script can do its things by the time the attack buttons shows up.

**Comment by potchy** [comment]
Actually, it would be great if we could do this right now.
I already have a screenshot of the battle screen from NA and CN. Can you guys help with JP and TW?

**Comment by aqer** [comment]
@potchy 
I have taken screenshots of JP and TW below.
JP
![screenshot_2018-12-22-03-13-38](https://user-images.githubusercontent.com/24737421/50359472-d6980b80-0597-11e9-89b2-de1401108632.png)
TW
![screenshot_2018-12-22-03-10-58](https://user-images.githubusercontent.com/24737421/50359494-e283cd80-0597-11e9-9d8b-64987ea58a5d.png)

**Comment by potchy** [comment]
Oh, the button is exactly the same in all servers.
Right, so AutoSkill should now work without the need to do any of these things:

> I had to make an adjustment as well. I will be adding this in for future raid events but make these changes:
> 
> In regular.lua do the following.
> 
> In the current one there is:
> 
> ```lua
> StartQuestClick = Location(2400,1350)
> StartQuestWithoutItemClick = Location(1652,1304) -- see docs/start_quest_without_item_click.png
> QuestResultNextClick = Location(2200, 1350) -- see docs/quest_result_next_click.png
> 
> --[[For future use:
> 	NpbarRegion = Region(280,1330,1620,50)
> 	Ultcard1Region = Region(900,100,200,200)
> 	Ultcard2Region = Region(1350,100,200,200)
> 	Ultcard3Region = Region(1800,100,200,200)
> --]]
> ```
> 
> Make this slight adjustment:
> 
> ```lua
> StartQuestClick = Location(2400,1350)
> StartQuestWithoutItemClick = Location(1652,1304) -- see docs/start_quest_without_item_click.png
> QuestResultNextClick = Location(2200, 1350) -- see docs/quest_result_next_click.png
> 
> isFirstTurn = true
> 
> --[[For future use:
> 	NpbarRegion = Region(280,1330,1620,50)
> 	Ultcard1Region = Region(900,100,200,200)
> 	Ultcard2Region = Region(1350,100,200,200)
> 	Ultcard3Region = Region(1800,100,200,200)
> --]]
> ```
> 
> Then further down in the permanent loop the current one is this:
> 
> ```lua
> while(1) do
> 	if MenuRegion:exists(GeneralImagePath .. "menu.png", 0) then
> 		toast("Will only select servant/danger enemy as noble phantasm target, unless specified using Skill Command. Please check github for further detail.")
> 		menu()
> 	end
> 	if battle.isIdle() then
> 		battle.performBattle()
> 	end
> 	if ResultRegion:exists(GeneralImagePath .. "result.png", 0) then
> 		result()
> 	end
> end
> ```
> 
> Change it to this:
> 
> ```lua
> while(1) do
> 	if MenuRegion:exists(GeneralImagePath .. "menu.png", 0) then
> 		toast("Will only select servant/danger enemy as noble phantasm target, unless specified using Skill Command. Please check github for further detail.")
> 		menu()
> 	end
> 	if battle.isIdle() then
>             if isFirstTurn then
>                 wait(15)
>                 isFirstTurn = false
>             end
> 		battle.performBattle()
> 	end
> 	if ResultRegion:exists(GeneralImagePath .. "result.png", 0) then
> 		result()
>                 isFirstTurn = true
> 	end
> end
> ```

**Comment by TryBane** [comment]
Ah, awesome. That'd be much easier.

**Comment by Rajvir8** [comment]
Glad to see it, I see that you've also already changed the code as well in the main one

**Comment by Keichide** [comment]
So.. Is there any possible Solution for the CEs yet? Because it would be quite useful if i could use a MLB Ox-Deamon King CE with Waver to boost the Buster Output of my fronline by 15% which fasten up most of the fights.

**Comment by TryBane** [comment]
My suggestion would be to create a new screenshot of the CE that is cropped to remove the % bonus on the bottom.

My initial suggestion about decreasing the variable didn't work as I had hoped when I tested.

**Comment by potchy** [comment]
salomon is ded

**Comment by 29988122** [comment]
Yay Human Law(人理) has been saved!
