### ISSUE TITLE
Can you use AOE NP earlier than the last battle, while using skills?

### ISSUE THREAD

**Issue by Rajvir8** [29988122/Fate-Grand-Order_Lua#153]
This is specifically using the newest version, I don't think the old one ever had this problem.

Granted this is my first time using Arash.

When I tried to use 

"g5,ahi1,d,f,e,bc"

It would break and no longer use any skills other than the first one.

I'm not 100% sure what the problem with other than it may because Arash is murdering the first wave and moving to the next.

I tried this with NP Spam ON and OFF and it broke regardless.

I'm using NA at the moment and not sure how I should fix it.

Not using NP's at all had it working but otherwise not sure what to do,

**Comment by Rajvir8** [comment]
I also tried making it

"g,ahi1,d,f,e,bc"

While turning NP Spam on but that also failed unfortunately as it completely stops using NP's as long as there are any skills to be used.

It's only when I choose an empty list that's it willing to use my NP

**Comment by Rajvir8** [comment]
Is this problem specific to Arash or something?  I'll try a different servant and see if that fixes it

**Comment by Rajvir8** [comment]
Nope the same problem happens now if I use any AOE Servant, not sure if it would happen with ST NP as well

**Comment by Rajvir8** [comment]
Hmm tried it with the old one and apparently this was always a problem

**Comment by Rajvir8** [comment]
But then before I used NP on the final wave and not on the earlier one's, or I would chain multiple NP's to end it on that turn.

**Comment by potchy** [comment]
From your skill string, it seems that this is what's supposed to happen:

**1/3 - Turn 1:**
[g] Use 3rd Servant's 1st skill.
[5] Use 2nd Servant's NP.

**1/3 - Turn 2:**
[a] Use 1st Servant's 1st skill.
[h] Use 3rd Servant's 2nd skill.
[i1] Use 3rd Servant's 3rd skill on 1st Servant.

**1/3 - Turn 3:**
[d] Use 2nd Servant's 1st skill.

**1/3 - Turn 4:**
[f] Use 2nd Servant's 3rd skill.

**1/3 - Turn 5:**
[e] Use 2nd Servant's 2nd skill.

**1/3 - Turn 6:**
[b] Use 1st Servant's 2nd skill.
[c] Use 1st Servant's 3rd skill.

Can you describe what is happening instead?

**Comment by Rajvir8** [comment]
I'm getting 

Battle 1/3 - Turn 1:
[g] Use 3rd Servant's 1st skill.
[5] Use 2nd Servant's NP.

After that the round is over and it becomes

Battle 2/3 - Turn 2:

What should happen is

[a] Use 1st Servant's 1st skill.
[h] Use 3rd Servant's 2nd skill.
[i1] Use 3rd Servant's 3rd skill on 1st Servant.

Instead it just goes straight into attacking normally.

Do I have to put in a different command for rounds now?

Before it ignored the round unless you specified it.

**Comment by Rajvir8** [comment]
Originally my string was

ad,ef,0,0,bc,456

I've never specified anything in regard to round and my first servants later skills came off in another round.

Is it because I had some 0 for skipping turns?

**Comment by ryuga93** [comment]
There are some changes in the code that prevented this, and from the first place your string should not be executable in other stages except 1/3. For stage counter, add # to indicate stage change (refer [Autoskill doc)](https://github.com/29988122/Fate-Grand-Order_Lua#autoskill)

**Comment by Rajvir8** [comment]
Understood just to clarify then

I would change my line

"g5,#ahi1,d,f,e,bc"

**Comment by Rajvir8** [comment]
It turns out it's the second and this fixed my problem.

Thank you for the help.
