### ISSUE TITLE
How can i solve this 

### ISSUE THREAD

**Issue by Mental0ut** [29988122/Fate-Grand-Order_Lua#157]
![screenshot_20190112-140929 1](https://user-images.githubusercontent.com/43524651/51076371-65b7b100-1676-11e9-9c2c-2d98121260d8.jpeg)
I have this error even with the base code

**Comment by potchy** [comment]
Please describe what you're doing step-by-step or provide a video.
What is not working exactly? The script is failing to click the Attack button?

**Comment by Mental0ut** [comment]
> Please describe what you're doing step-by-step or provide a video.
> What is not working exactly? The script is failing to click the Attack button?

I made this video.
It's like do all the pattern cards

https://youtu.be/jkanmP9hw4M

and another problem that I have is with the waiting time in the supports
https://www.youtube.com/watch?v=b2azdSaFwww

**Comment by potchy** [comment]
Hmm, we may revisit `autoskill.lua` later on, but for now, as a stopgap measure, you can increase the wait times between clicks. Here are the lines you will want to tweak:

https://github.com/29988122/Fate-Grand-Order_Lua/blob/2fcbb458df6c83e4351a986b2afae6ed5a116793/modules/autoskill.lua#L115
https://github.com/29988122/Fate-Grand-Order_Lua/blob/2fcbb458df6c83e4351a986b2afae6ed5a116793/modules/autoskill.lua#L117
https://github.com/29988122/Fate-Grand-Order_Lua/blob/2fcbb458df6c83e4351a986b2afae6ed5a116793/regular.lua#L39

Those numbers are in seconds.

**Comment by Mental0ut** [comment]
@potchy 
I think I have different files to yours because the lines do not match the ones you gave me.
I managed to find the section with time. but the error continues.

Maybe I have old files. which is the most current?
![help 2](https://user-images.githubusercontent.com/43524651/51216416-16d27b80-1903-11e9-88ef-09270fe55ea8.PNG)
![help](https://user-images.githubusercontent.com/43524651/51216417-16d27b80-1903-11e9-93eb-1796e0b5b9ec.PNG)

**Comment by potchy** [comment]
[This one](https://github.com/29988122/Fate-Grand-Order_Lua/archive/master.zip) is the latest:
![image](https://user-images.githubusercontent.com/4316326/51218106-05dd3680-1912-11e9-9675-973bdce40a6d.png)

You should also try [the fix for AutoSkill](https://github.com/potchy/Fate-Grand-Order_Lua/archive/master.zip) that I pushed this evening especially for you.
It's not merged yet, but it should work.
