### ISSUE TITLE
Devices with a notch

### ISSUE THREAD

**Issue by potchy** [29988122/Fate-Grand-Order_Lua#158]
AnkuLua's recently added some new functions that help deal with different resolutions and devices with notches.
http://ankulua.boards.net/thread/1243/set-script-area
http://ankulua.boards.net/thread/7/settings#autoGameArea
http://ankulua.boards.net/thread/7/settings#getGameArea
http://ankulua.boards.net/thread/7/settings#setGameArea

With @TryBane's help, we managed to make the script work in different aspect ratios, but notches are still out of the table. My pull request #155 should have addressed that, but @aqer confirmed it's still not working.

I opened this issue for discussion on possible solutions.

**Comment by reconman** [comment]
I have a notch and everything works fine. On some devices you need to set `autoGameArea(false)` even if they have a notch, for example on Samsung Galaxy A50.

See https://29988122.github.io/Fate-Grand-Order_Lua/#/troubleshooting?id=the-script-clicks-in-the-wrong-locations-or-does-nothing-at-all
