### ISSUE TITLE
[Feature Request] Run Customizable Scripts

### ISSUE THREAD

**Issue by TheIanator** [29988122/Fate-Grand-Order_Lua#16]
I currently have an FRep script that can run my ember gathering dailies for me. It's all timing based so if something takes a little too long to load, or if I accidentally touch the screen, the script gets messed up and I have to finish the quest out manually.

It would be nice to have something like this running within this framework so that it is more robust against errors, and so it could automatically start the quest again instead of needing to be manually run once per quest.

For example what my FRep script does:

- Merlin Allies NP gauge up, Merlin's buster up on Spartacus.
- Spartacus self NP gauge up, self buster up.
- Bunyan Allies Buster up.
- Attack - Spartacus NP, 1st and 2nd cards.
- 2nd Battle, Attack - Bunyan NP, 1st and 2nd cards.
- 3rd Battle, Battlesuit - Switch Merlin with Support AOE Berserker with LB Kaleidoscope.
- Attack -> Berserker NP, 1st and 2nd cards.
- Click through results screen.

What I'm hoping for is a script you could pass something like this:

- Skill Position 7
- Skill Position 9
- Target Position 1
- Skill Position 2
- Skill Position 3
- Skill Position 4
- Attack
- NP Card Position 1
- Card Position 1
- Card Position 2
- Wait for Battle 2/3 (If fails run regular.lua possibly)
- Attack
- NP Card Position 2
- Card Position 1
- Card Position 2
- Wait for Battle 3/3
- Mystic Code
- Code Skill 3
- Select Battlesuit target 3
- Select Battlesuit target 4
- Switch
- Wait for servant to load
- Attack
- NP Card Position 3
- Card Position 1
- Card Position 2
- regular.lua takes over to click though results screen, use apples as necessary, and select quest again.

If the script needs a specific support to work it could wait at that screen for manual selection. Or possibly you could have a picture of a support portrait, for example Raikou with a LB Kaleidoscope, and it could refresh the support list until it sees that portrait.

Since this is all just passing positions and not any complicated image recognition (except possibly for supports) this seem like it shouldn't be terribly difficult to implement.

**Comment by 29988122** [comment]
Ryugawa93 did have a plan, and it looked exactly like your request:
https://github.com/29988122/Fate-Grand-Order_Lua/issues/14#issuecomment-354582439

Does it fit your requirement?
The string will have to be input manually for your specialized team / skill / NP card order.

**Comment by TheIanator** [comment]
He seems to have already added autoskilling in his own fork. Was able to get it working after some trial and error, and outside of a few bugs it works well. It doesn't look like it currently supports the order change skill, which would open up many more possibilities for scripting. Also  it would be awesome to add more complex support selection.

**Comment by ryuga93** [comment]
I haven't unlock the Chaldea Combat Uniform yet, will get it done after the Saber Wars event in USA. Might update together with support selection. Aside this 2 issues, I would like to know if there are other bugs exist, so that I can fix them in the next update.

**Comment by TheIanator** [comment]
Using only # marks without commas resulted in it trying to execute all three battles on the first turn.
Using commas before and after the hash as shown in the example resulted in this error: https://imgur.com/a/auID0
for some reason "k1" and "i1" used the skill on the third slot instead of the first, was able to solve this for my use by just moving the target servant to the third slot.

For reference what I eventually got working : Skill_Command = "idfac16,#hik16,#5"

**Comment by ryuga93** [comment]
Weird, the intended string should be idfac16,#,hik16,#,5 but it throws error, hmm. I'll look into this using your command.

**Comment by ryuga93** [comment]
I am sure that the command "idfac16,#,hik16,#,5" is working fine, even with REGULAR_JP, try it again on your side. Just to make sure, did you change anything on regular.lua?

Also "k1" and "i1" did select servant 1 on my side, tested it with the command "i1dfac16,#,hk1i16,#,5"

As for # marks without commas, will either make a check on it or make the instruction clearer.

Thanks for testing.

**Comment by TheIanator** [comment]
Solved my selecting the wrong target servant problem, I had skill confirmation turned off and the press that usually confirms the skill was selecting the third servant instead.

The error when using commas after hashes persists and attemping to run without commas after now gives a warning. Had a thought and tested the EN script on NA and everything worked as it should. I then tried changing setImagePath on the EN script to image_JP to see if would work on JP, and got the same error. Does this mean the problem is with an image in images_jp?

Adding the toast line returned "Runtime error: ?:0: attempt to concatenate a nil value stack traceback: ?: in function 'toast'" and then the same list of lines as the last error.

**Comment by ryuga93** [comment]
Place these images into your JP folder and test it with toast
https://drive.google.com/open?id=1uKgnxNEEY1SABlDS_kHdfq8cr_zfRdtg

Totally forgot about skill confirmation, will add an option to disable it

**Comment by TheIanator** [comment]
Getting the same "Runtime error: ?:0: attempt to concatenate a nil value stack traceback: ?: in function 'toast'" error.

**Comment by ryuga93** [comment]
Can you send me the screenshot without the error?

**Comment by TheIanator** [comment]
https://i.imgur.com/L3T1UUs.jpg

Pasting the numbers over the screenshot they look pretty much identical, I compared an NA screenshot to the JP one and there was about a 7 pixel horizonal difference in location of the battle number, could it be looking at the wrong spot?

NA screenshot if its at all relevant: https://i.imgur.com/0n2Qpaz.jpg

**Comment by ryuga93** [comment]
You are right, the location is wrong. I have updated my fork and included the Skill Confirmation setting.

**Comment by TheIanator** [comment]
Upon reaching the second battle it crashes with ""regular.lua:190: attempt to perform arithmetic on field'?' (a nil value)"
Adding toast(currentStage) after currentStage = checkStageCount(stageCountRegion) returns the same "Runtime error: ?:0: attempt to concatenate a nil value stack traceback: ?: in function 'toast'" it did before.

The first turn executes correctly, but on subsequent turns it isn't executing skills correctly. It performs the click for target selection and the one for skill confirmation when it's on, but not the initial click on the skill.

**Comment by ryuga93** [comment]
> Upon reaching the second battle it crashes with ""regular.lua:190: attempt to perform arithmetic on field'?' (a nil value)"
Adding toast(currentStage) after currentStage = checkStageCount(stageCountRegion) returns the same "Runtime error: ?:0: attempt to concatenate a nil value stack traceback: ?: in function 'toast'" it did before.

Send me the screenshot. I'll look into it. Also get into Battle 3 and run the script. See if the error comes up for 3rd battle.

> The first turn executes correctly, but on subsequent turns it isn't executing skills correctly. It performs the click for target selection and the one for skill confirmation when it's on, but not the initial click on the skill.

I don't quite get you, is it the same command idfac16,#hik16,#5? Is it in Battle 1?

**Comment by TheIanator** [comment]
> Send me the screenshot. I'll look into it. Also get into Battle 3 and run the script. See if the error comes up for 3rd battle.
Same error in third battle, screenshots both with and without toast: https://imgur.com/a/gtpaB

> I don't quite get you, is it the same command idfac16,#hik16,#5? Is it in Battle 1?
Clip here: https://gfycat.com/ScratchyUnfitAtlanticbluetang
For this test I used "a,f1,#,g", you can see the first skill execute properly, and you can see the second click where confirm would be and where the target would be but never clicked the skill itself.

**Comment by ryuga93** [comment]
In JP.lua, change stageCountRegion = Region(1708,28,36,46), this size should solve it the error.

Then, run the command again, if the missing click still happens, remove toast(currentStage) and every toast in function targetchoose(). My execution still works with toast, but so far the only possible cause I can see is this.

If the missing click still occurs even after removing the toast functions, add one toast("before") before and toast("after") after the line click(SkillClickArray[index]) at line 257, just to see if the click runs or not

**Comment by TheIanator** [comment]
Think that x and y are the NA x and y. Changing it to stageCountRegion = Region(1726,28,36,46) results in stage 1 and 3 working, stage 2 still throwing arithmetic error.

**Comment by ryuga93** [comment]
Woops sorry, that's for TW, here's the correct one

(1724,24,38,50)

**Comment by TheIanator** [comment]
That works, thank you.

**Comment by 29988122** [comment]
@ryuga93 
Wait, they actually have different numeric font for stage selections? So we need to screenshot different versions respectively?
That was troublesome to say the least. 

I drafted a new release version just now, wanna make sure if you tested all the three versions(EN TW JP), or I'll test it myself later and try to also add KR/CN support in the next few days.

**Comment by ryuga93** [comment]
The 3 version should not be a problem, but I haven't tested TW yet, JP version has been intensively tested by @TheIanator (Thanks for your help).

It's not just font different, JP and EN have the same font, but they located slightly different =.=

I checked the CN version screenshots in Google, and the font is just...weird lol, plus CN card type uses Chinese characters, hope there is a image that's recyclable...

**Comment by 29988122** [comment]
Okay, I'll screenshot myself CN, KR version then, got a little bit of free time.
If there's anything language dependent I forgot to modify, I guess I'll wait for ppl to file an issue. Not enough servant for a new account to do all the testing..

**Comment by 29988122** [comment]
How did you screenshot the stage counter? Trying to do the CN server, but I've never seen battle with more than 3 stages..

**Comment by ryuga93** [comment]
I got them from Google image youtube screenshot, should be enough for fuzzy recognition. Those stages appears only during events.

It's ok not to have transparent. I'm not sure supported or not, didn't search for it. Just crop with 1 or 2 pixel padding would be enough to recognize all background, so as the search region, just 2 pixels padding.
