### ISSUE TITLE
Is this supposed to work with bluestacks?

### ISSUE THREAD

**Issue by Klevokr** [29988122/Fate-Grand-Order_Lua#161]
Every time I start the lua I get some blank warning message error and it gets stuck there

**Comment by 29988122** [comment]
You are a Jp server player?

Currently only the latest version of nox can bypass fgo Jp client emu
detection (you won't be banned, no worries).


If you're asking about other servers, then yes, bluestack's supported.

**Comment by MrTroika** [comment]
This works fine in emulators provided the emulator itself can do FGO. I'm currently using it on Nox.
