### ISSUE TITLE
Resolution scaling runtime error

### ISSUE THREAD

**Issue by vit2657** [29988122/Fate-Grand-Order_Lua#162]
Getting this runtime error on the function which seems like supposed to fix resolution on my pocofone f1 (with notch). Latest code from master, android 8+, accessibility instead of daemon.
Previously I was hijacking xOffset in the FGO_EN_REGULAR file, but the code is moved now so what the supposed fix now?
![screenshot_2019-01-17-19-04-37-993_com aniplex fategrandorder en 1](https://user-images.githubusercontent.com/18238005/51335529-fb927800-1a8a-11e9-88f5-827f3a4f3ddc.png)

**Comment by vit2657** [comment]
Full message
![screenshot_2019-01-17-19-08-25-972_com aniplex fategrandorder en 1](https://user-images.githubusercontent.com/18238005/51335658-4ca26c00-1a8b-11e9-9bfa-3b6f13de0b54.png)

**Comment by ryuga93** [comment]
You need to update to Ankulua version 8.2.0

**Comment by vit2657** [comment]
@ryuga93 thanks, that helped!

**Comment by potchy** [comment]
Hey, don't go! Is the current version working for you without the need to set the offset manually?

**Comment by vit2657** [comment]
I can also add that from my experience there are multiple differences how game will render itself if resolution is not 16:9. One case it will fill with blue background, and another is just black bars. For me it is black bars only on this notch device, maybe it can be the case.

**Comment by potchy** [comment]
@ryuga93 
Here's a visual representation I made of his screen measures.
I think @aqer's device handles the in-game notch differently.

![borders](https://user-images.githubusercontent.com/4316326/51347042-4f4e9280-1a86-11e9-95d4-e222260d6887.png)

**Comment by vit2657** [comment]
If I can turn on some debug data to help you compare our cases let me know, or maybe test some debug version.

**Comment by potchy** [comment]
Yes, please place this file in the `/modules` folder: [scaling.zip](https://github.com/29988122/Fate-Grand-Order_Lua/files/2770501/scaling.zip)

Run the script directly in the home screen (preferably in landscape mode) and take a screenshot, like this:
![screenshot_2019-01-12-12-24-41](https://user-images.githubusercontent.com/4316326/51074352-4ebc9300-1665-11e9-9177-b20d66035691.png)

Then, click "Cancel". It's important that the script stops. Now open the game, run the script again and take another screenshot.
![screenshot_2019-01-12-12-26-28](https://user-images.githubusercontent.com/4316326/51074353-4ebc9300-1665-11e9-8af4-20557357f507.png)

Post both of them here.

**Comment by vit2657** [comment]
@potchy here are screenshots, unfortunately I'm not able to get the first one in the landscape, cause MIUI does not support landscape on home screen (at least mine). Also your second screen shows ID  (just a heads up).

![screenshot_2019-01-17-22-51-18-004_com mi android globallauncher 1](https://user-images.githubusercontent.com/18238005/51348253-e4638280-1aaa-11e9-9ef1-194376728015.png)
![screenshot_2019-01-17-22-52-56-158_com aniplex fategrandorder en 1](https://user-images.githubusercontent.com/18238005/51348256-e75e7300-1aaa-11e9-8f92-2f0f93469a6c.png)

**Comment by absolution64** [comment]
This might be applicable to Nox emulators, I am currently running EN_script but it shows a similar, if not the same error as vit2657
I am still unsure what to do with it though because I lack the knowledge to do so.

![image](https://user-images.githubusercontent.com/46937691/51558625-09edf300-1ed4-11e9-9e6f-7d48322c9ad7.png)

**Comment by potchy** [comment]
Update AnkuLua.
