### ISSUE TITLE
Getting a caution message then java.io.exception

### ISSUE THREAD

**Issue by vphan6896** [29988122/Fate-Grand-Order_Lua#163]
Before this window, I gotten a "Caution" window pop up but it did not have any message in it except for ok and cancel. I tried launching the script while on first battle screen in usb debugging mode and without usb debugging mode. Both ended in the same messages. Accessibility and Media Projection are on.
![50182970_350905519077989_7189752430047789056_n](https://user-images.githubusercontent.com/22038813/51337660-54432000-1a4d-11e9-9ac5-9b3c206e43dd.jpg)

**Comment by Mental0ut** [comment]
it is a problem with the format with which you save the file when editing it try with this.

https://github.com/29988122/Fate-Grand-Order_Lua#troubleshooting

**Comment by vphan6896** [comment]
I am still getting the same error. I have never edited the file before. But I opened it with notepad++ and made sure it has the correct encoding.

**Comment by potchy** [comment]
It looks like you did not give AnkuLua the necessary permissions for Media Projection to work.

**Comment by Mental0ut** [comment]
@potchy  Is it necessary to give all permits to ankulua?

**Comment by vphan6896** [comment]
I gave all permissions. There were a few prompts asking for permissions and I accepted all. I even checked the settings. I bought AnkuLua Pro2 license and now the script works. This seems to be related to issue #150 . For later references to the thread, I am using a Samsung J7.
