### ISSUE TITLE
Auto target choose interrupt autoskill

### ISSUE THREAD

**Issue by CocytusP** [29988122/Fate-Grand-Order_Lua#164]
i don't really know why but when danger enemy appear,the next autoskill doesn't happen,instead it continue to do a basic attack.

**Comment by potchy** [comment]
Please post your configuration file.

**Comment by CocytusP** [comment]
[FGO_JP_REGULAR.zip](https://github.com/29988122/Fate-Grand-Order_Lua/files/2834032/FGO_JP_REGULAR.zip)

i just change the autoskill tho

**Comment by Mental0ut** [comment]
> Please post your configuration file.

@potchy this happens because the dangerous enemy is in the first position

**Comment by 29988122** [comment]
@Mental0ut 
I did modify the autotarget code for JP server's previous event(Illya).

But as I'm typing this, it worked normally in JP server when the dangerous enemy's in the first position.

The behavior's wrong in other servers?

**Comment by potchy** [comment]
Still can't reproduce. I'm farming Valentine's and it's working great.
#166 seems to have the same problem. Maybe one of you can share a video?
