### ISSUE TITLE
Helpp

### ISSUE THREAD

**Issue by MrPotSticker** [29988122/Fate-Grand-Order_Lua#165]
Im trying to use Memu since i cant download Cookie since i dont have Intel Visualization sadly. So i can download Ankulua and everything but when i try to copy the entire script file into memu it wont let me open/load the script

**Comment by MrPotSticker** [comment]
Nvm now im getting an error message ;/ https://gyazo.com/8e35e5847ef0ea5bb18a51fb44fae575?token=c2ceec70841f83e9de8d2f156f4ed6fe

**Comment by potchy** [comment]
Judging by the error message, it looks like you didn't extract all folders from the .zip.
