### ISSUE TITLE
Quick Question Reguarding Valantines

### ISSUE THREAD

**Issue by Rajvir8** [29988122/Fate-Grand-Order_Lua#167]
I'm setting the Is Event Box to 1 but is there a way to decide which Event Item you use.

For example I want to use the Saber one repeatedly if possible.

**Comment by potchy** [comment]
There's no "official" option, but as a workaround you can replace the coordinates for MENU_START_QUEST_WITHOUT_ITEM_CLICK in `modules\game.lua`.

**Comment by Rajvir8** [comment]
Got it, I'd change it to 

MENU_START_QUEST_WITH_SABER_ITEM_CLICK 

in `modules\game.lua`.

and change docs/start_quest_without_item_click.png

To docs/start_quest_with_saber_item_click.png

Would just the image of the Saber Candy work?

Or would it run into problems when it has to confirm the Saber Image?

![oie_tpdjo4na4cix](https://user-images.githubusercontent.com/17600697/52514475-23838000-2be0-11e9-8a51-4f6f54d6e1c2.png)

**Comment by potchy** [comment]
No, you don't need to change the image. That's only for documentation. lol

**Comment by Rajvir8** [comment]
Got it, I'll make sure to give it a try.  Thanks for the help and clarifying what you were talking about, 

I'll try it tomorrow when my stamina recovers and give it a shot.

**Comment by Rajvir8** [comment]
The first suggestion on how to change it worked as it can now click on which event item I want.

1270,345 worked perfectly when I wanted the first one, and 1270, 600 worked when I wanted the second one.

But now I'm stuck on the confirmation button.

Which section would I change to get past it?

**Comment by potchy** [comment]
There's a toggle on that same window to disable the confirmation.

**Comment by Rajvir8** [comment]
Ah so that's what that's for I didn't realize even though I should have.

Sorry and thank you for all the help.
