### ISSUE TITLE
What's the best way to handle skill Cooldowns in long fights?

### ISSUE THREAD

**Issue by Rajvir8** [29988122/Fate-Grand-Order_Lua#168]
My main problem is due to luck and my NP being spam, I end up at the third round at very different turn counts.

Is there any way to set it so my skills are guaranteed to go off at turn 8 regardless of what wave I'm on?

If not, I'll just have to make it so they go off 4 turns after Wave 3 to pretty much guarantee it will be fine even if it it's not optimal.

**Comment by 29988122** [comment]
> make it so they go off 4 turns after Wave 3

Yeah, unfortunately this is the best we can do at the moment. Autoskill behavior will be revamped in the near future^TM.

I myself would use Kaleido Scope and grab a Waver from friend support though.

**Comment by Rajvir8** [comment]
Got it thanks.

I'd rather use all event CE's for now though, as I managed to form a combination of skills that get me victory consistently even if it does take 10 minutes per battle.

It does suck that I have to manually hit stop at the 30 minute mark, but that's what happens when you don't run out of AP in time.
