### ISSUE TITLE
Boost Item Selection

### ISSUE THREAD

**Issue by jdash007** [29988122/Fate-Grand-Order_Lua#170]
Script should allow automatic selection of specific Boost Item for the events that have them not just defaults to "Begin quest without item".

**Comment by potchy** [comment]
There won't be official support for now, but you can work around it.
See #167.

**Comment by potchy** [comment]
try this new option:

```lua
BoostItem_SelectionMode = "disabled" --[[
	possible values: disabled, 1, 2 or 3
	if you want to use this, make sure "Confirm Use of Boost Item" is off
--]]
```
