### ISSUE TITLE
Runtime error: Can't open /sdcard/FGOLua//image_SUPPORT

### ISSUE THREAD

**Issue by karynyukizawa** [29988122/Fate-Grand-Order_Lua#171]
I've just updated the script, I've set up it as usual and...

Got this error when the script is going to select the preferred support with Cute Orangette CE (Won't post a screenshot due to different language on error, but I'm going to translate and type the whole thing here):

"Runtime error: java.io.IOException: Can't open /sdcard/FGOLua//image_SUPPORT
stack traceback:
[C]: in function 'findAllNoFindException'
?: in function 'regionFindAllNoFindException' /sdcard/FGOLua/modules/support.lua:
216: in function 'findServants' /sdcard/FGOLua/modules/support.lua:
196: in function 'searchMethod' /sdcard/FGOLua/modules/support.lua:
150: in function 'func" /sdcard/FGOLua/modules/ankulua-utils.lua:16 in function 'UseSameSnapIn' /sdcard/FGOLua/modules/support.lua:
165: in function 'searchVisible" /sdcard/FGOLua/modules/support.lua
100: in function </sdcard/FGOLua/modules/support.lua:94>
(tail call): ?
/sdcard/FGOLua/regular.lua:90: in function 'actor'
/sdcard/FGOLua/regular.lua:223: in main chunk
[C]: in function 'dofile'
/sdcard/FGOLua/FGO_EN_REGULAR.lua:85: in main chunk"

The weird thing is... That double / at the start of the error. (Yes, that wasn't a typo, the error shows it like that).
Line 7 at my support.lua: local SupportImagePath = "image_SUPPORT" .. "/"

Using Samsung S7 Edge with Android 8.1 + Magisk
Ankulua is at Ver 8.2.0-Trial.

**Comment by potchy** [comment]
The error message suggests there's something wrong with your folder of support images.
Maybe it got corrupted or something? Try to extract everything to a different folder.
That double backslash is normal, by the way.

**Comment by karynyukizawa** [comment]
I've downloaded again, extracted, deleted the old folder, created a new one, transfered everything...

And I'm still getting this error :/

**Comment by potchy** [comment]
It's gotta be something with your device, because it's been a while since we last changed the directory structure. Are the other parts of the script working correctly, except for the support module?

**Comment by Enryuna** [comment]
Was running into the same problem.

In my case I forgot to put the file extention when specifying CE.

For exemple "lunchtime" instead of "lunchtime.png"
