### ISSUE TITLE
Error when using master skill

### ISSUE THREAD

**Issue by Zilay** [29988122/Fate-Grand-Order_Lua#173]
when i use master skill in auto skill mode, the command following master skill code will miss. For example, when i use "kdh,egi1f1x31gca5" the "d" and "g" will miss. It will work normally when i change function CastMasterSkill and SelectSubMember to as follows:

local function CastMasterSkill(location)
	return function()
		OpenMasterSkillMenu()
		CastSkill(location)()
		wait(0.3)
		WaitForAnimationToFinish()
	end
end

local function SelectSubMember(location)
	return function()
		click(location)
		wait(0.3)
		click(game.BATTLE_ORDER_CHANGE_OK_CLICK)
		wait(1)
		WaitForAnimationToFinish(15)
		ChangeArray(DEFAULT_FUNCTION_ARRAY)
	end
end

**Comment by potchy** [comment]
Do you mind to record a video showing the issue? I want to confirm why this is happening.

**Comment by reconman** [comment]
No reply from user, closing now.
