### ISSUE TITLE
Having One Account on Multiple Devices simultaneously

### ISSUE THREAD

**Issue by Rajvir8** [29988122/Fate-Grand-Order_Lua#175]
You mentioned adding the following to the readme but never ended up doing so.

If you have the time I'd love to discuss how to do so.

I have a couple of questions though, first does installing Magisk on your phone not interfere with FGO?  Or is it sophisticated enough that it's hidden due to not adding any files to system code.  As your phone is still rooted after Magisk and one of the main reasons I didn't root my new phone is I didn't want to interfere with FGO.

If need by I'm open to buying Titanium Pro to do this but I like the sound of learning how to bash chmod/chown more, if you could reference me a place to check that out I'd appreciate it.

Also after the initial setup does anything else need to be done, or can I straight up play FGO on my computer for an hour.  Turn my Computer off and open FGO later that day on my phone without having to set anything else up?

I don't have to continually make backups each time I use the app on one device?

[QUOTE]
I'll add a way to quickly transfer accounts **WITHOUT** using bind codes in readme.md.
To be precise, it's more like one account on multiple devices simultaneously.
Soon^TM

You'll need to purchase Titanium backup, or able to bash chmod/chown files.
Root needed(temporary root or Magisk's enough). [/QUOTE]

_Originally posted by @29988122 in https://github.com/29988122/Fate-Grand-Order_Lua/issues/149#issuecomment-450044253_

**Comment by Rajvir8** [comment]
Never mind I managed to figure it out myself with enough research, in case anyone is curious I did it without root entirely.

I used Helium Pro which Nox can actually use unlike the free version, I created the backup inside of Nox and then restored it back onto my phone and it worked wonderfully.

Now both of them have the same data inside of them which makes swapping between the two easier then ever which is nice.  It was worth the hassle to do as otherwise redownloading the game every day to swap over recently has been quite annoying.

**Comment by 29988122** [comment]
Glad you figure it out. 

I was manually chmod + copying files without titanium backup, and wrote a script for it.
Apparently, this is too complicated that I should not write a manual for it. Not meant for regular user.

Later I found out TiBackup can do that without hassle - Magisk stood undetected by FGO.


I have no idea that how is Helium able to backup without root - I'd guess adb pull.
Anyway, congrats. I'll modify that part, pointing to your comment. 

: D

**Comment by 29988122** [comment]
Hey wait, I already wrote on that.

https://github.com/29988122/Fate-Grand-Order_Lua/wiki/Same-account-on-different-phones-and-emus-at-the-same-time

Anyway since you've already solved that..XD

**Comment by TryBane** [comment]
@Rajvir8 I tried to use Helium on my nox and phone and it seems to just not work at all.

I was able to do an initial internal backup on Nox, but after doing that I can't restore it. It also won't allow me to backup to Google drive.

After getting it on my mobile device as well, it won't allow me to even do a simple backup. I also tried copying the internal data from Nox into the shared folder, then copying that data into my phone, then trying to restore using Helium app and the app didn't recognize the data.

Could you provide a bit of instruction on how to get this working?

**Comment by Rajvir8** [comment]
@TryBane Sure I'm happy to walk you through the steps I took.

So I had a similar problem the first time I tried using Helium at which point I gave up, I'll be honest and say I'm not honestly a 100% sure which step fixed my problem so I'll go through all the steps I ended up taking.

The first two are very self explanatory and while the third is also fairly obvious make sure you didn't miss it.

Step One - Install the Helium app for your computer as well as your phone.

Step two which I assume you've managed, make sure your phone has USB Debugging on in order to so become a Developer and turn it on.

Step three open up the Helium Desktop App and make sure it's actually can connect to your phone, to do so you need to turn USB Debugging on and this is important change the phone to MIDI Mode, at which point your computer app should give you a check-mark.

If it hasn't given you a check-mark you aren't done step three and may need to play around your phone settings until it connects.

Step Four make sure you've got FGO in your Nox App rather that your phone at the moment and that you haven't downloaded any additional data.  If you have clear your cache first and redownload.
We want it as small as possible to minimize the chances of any errors

Step Five start the backup - With Nox turning on Root is very easy, so turn it on and start the backup
By default Helium should decide that you don't need the app itself, only the App Data, this is the setting we want it to have.  If it isn't like that and the full app is included make sure to change the setting so it only creates a backup for the App Data.

Step Six - Make sure FGO is uninstalled on your phone - Connect over to Helium and take the Backout of Nox and over to your phone

Step Seven - Start the Restoration process, it should mention that this contains only app data and that you will have to go to Google Play Store to download the App, hit accept and it will bring you to the Google Play Store.  Reinstall FGO.

Step Eight - Reopen Helium it should then start the restoration process on the New FGO App automatically.  Wait a few minutes and make sure your phone doesn't go to sleep mode while it restores.

Step Nine - Open up FGO on your phone, it should automatically bring you to your account now.  Redownload the full data to make FGO faster on your phone and you can do the same on your Nox afterwards.  Congratulations you now have FGO on both Nox and your computer.

Some quick Disclaimers, first do not use the two at the same time, I have no idea what would happen.  It's fine if you close one a few minutes ago and swap over though as it's less strange for FGO than even a VPN is.

Any Quest you start is stored in your Cache not the Servers, meaning if you start a quest on your computer and transfer over to your phone, the servers will assume you lost the quest and you'll just start back at the menu with your AP missing.  So make sure to complete any quests or you'll miss out on some AP.

If you have any questions feel free to ask, I'd love to help and give back after how much the community has helped me with my questions over the time I've been here.

**Comment by TryBane** [comment]
@Rajvir8 Thank you very much. I didn't get a notification on this reply. Only saw it when checking out if there was any updates on opened tickets and decided to check if there was a reply. I haven't gotten around to following your steps yet as I'm in the middle of farming the HQs out on NA. I'll let you know if I run into any problems with getting this to work, and thanks for the detailed steps!

I do have one question though. You said to copy the folder over, but what exactly am I copying? I thought I found the file I needed, but when I tried to put it in the correct place on my phone, the Helium App didn't seem to register it's location. This was prior to following your step by step instructions though, so I might've done something that wasn't going to work anyways (like uninstalling the FGO app which I didn't do :D )

**Comment by TryBane** [comment]
@Rajvir8 Nevermind! I got it working. Thanks a bunch for the detailed step instructions. Not sure what happened previously as I'm pretty sure I did everything the same as before. Nevertheless, following your instructions got it working so thanks!
