### ISSUE TITLE
Error when using new script

### ISSUE THREAD

**Issue by Eldiaz7** [29988122/Fate-Grand-Order_Lua#176]
hello
first, thanks for your hardwork for making this script
since the script is getting update, i am try to using the newest
but this is what i got
![Screenshot_2019-04-07-07-05-21-113_com appautomatic ankulua trial](https://user-images.githubusercontent.com/14069329/55676831-fcf37400-5906-11e9-90e9-1cc2372cab5b.png)
and now im still using the old script that still work in my phone
and in the old script the swipe on support selection doesnt work, so i must swipe manually to find the correct support  even i already set 'preffered'

sorry for my bad english

**Comment by ryuga93** [comment]
Hi have you updated to the newest Ankulua version?

**Comment by Eldiaz7** [comment]
> 
> 
> Hi have you updated to the newest Ankulua version?

oh i dont know if i must update the app too
i will try then
thankyou

**Comment by Eldiaz7** [comment]
im already update the ankulua and the new script work
but stil, the swipe on selection support doesnt work
any advice for this problem?

**Comment by 29988122** [comment]
What kind of "method" are you using?
e.g., root, media projection, daemon, or android accessibility.

Due to non-root constraints, Android 7 and above might not support certain function such as swipe().
Try another method to see if it's compatible with your phone.

**Comment by Eldiaz7** [comment]
> 
> 
> What kind of "method" are you using?
> e.g., root, media projection, daemon, or android accessibility.
> 
> Due to non-root constraints, Android 7 and above might not support certain function such as swipe().
> Try another method to see if it's compatible with your phone.

im using daemon method
hmm i see
okay i will try later
thanks for the answer
