### ISSUE TITLE
how to fix this?

### ISSUE THREAD

**Issue by popkk213** [29988122/Fate-Grand-Order_Lua#177]
![Screenshot_2019-04-18-03-11-17-525_com aniplex fategrandorder](https://user-images.githubusercontent.com/49636684/56317857-fd520180-6187-11e9-8dd8-9f427f3cb24f.png)
![Screenshot_2019-04-18-03-11-23-141_com aniplex fategrandorder](https://user-images.githubusercontent.com/49636684/56317871-04790f80-6188-11e9-9999-de04905dd50d.png)
why i can't run script? pls help sry for bad english

my phone Xiaomi Redmi Note 4

**Comment by popkk213** [comment]
> ![Screenshot_2019-04-18-03-11-17-525_com aniplex fategrandorder](https://user-images.githubusercontent.com/49636684/56317857-fd520180-6187-11e9-8dd8-9f427f3cb24f.png)
> ![Screenshot_2019-04-18-03-11-23-141_com aniplex fategrandorder](https://user-images.githubusercontent.com/49636684/56317871-04790f80-6188-11e9-9999-de04905dd50d.png)
> why i can't run script? pls help sry for bad english
> 
> my phone Xiaomi Redmi Note 4          Android 7

**Comment by TryBane** [comment]
I am not 100% sure about that since I don't use JP myself. I will give it a test when I get a chance but considering how much Overtime I am getting at work, I am unsure when I will get a chance. It may be tomorrow, or 2 weeks from now. I'll inform you if I figure it out. Meanwhile, maybe someone else could see about the issue?

Also, is this the only part that doesn't seem to run correctly?

**Comment by popkk213** [comment]
ya that right Thanks for info Bane if you figure it out pls tell me

**Comment by popkk213** [comment]
maybe 1080 x 1920 doesn't work?

**Comment by minalinskychan** [comment]
i have the  same problem

my phone xiaomi mi max 2

**Comment by iamcurseal** [comment]
I also have the same problem, using Xiaomi Redmi Note 4x

**Comment by minalinskychan** [comment]
https://www.dropbox.com/s/d3825j7x9ldh1d7/Screenshot_2019-07-10-18-54-27-283_com.android.settings.png?dl=0

I turned  usb debugging security setting on and fixed.

**Comment by popkk213** [comment]
Its work!!! TY

**Comment by TryBane** [comment]
Sorry I wasn't able to provide a solution myself. I honestly had no idea as to why it might've been having problems. I am glad someone was able to find a solution!

Just to be clear, the apparent solution is to turn USB Debugging Security option on. I will close this now and if people are still having trouble we can reopen it at that time.

**Comment by iamcurseal** [comment]
what version of the app ur using guys? is it trial or pro?
