### ISSUE TITLE
CCC Event issue

### ISSUE THREAD

**Issue by ParasiteEve** [29988122/Fate-Grand-Order_Lua#179]
I have skills running on - the script always stops because it accidently clicks the character and no t the skill due to the slot thing...

**Comment by TryBane** [comment]
I haven't tried running the event with the script yet. I'll do an update on it when I get home

**Comment by TryBane** [comment]
Alright, after taking a look I am not sure why the slots would cause a situation where the program doesn't click correctly. I'll have to do some testing to further investigate the situation

**Comment by 29988122** [comment]
Will be solved after we implement a proper observer function.

In the meantime, there'd be ugly wait() everywhere in the code.
