### ISSUE TITLE
I can't get this to run in Bluestacks

### ISSUE THREAD

**Issue by Fullblitz** [29988122/Fate-Grand-Order_Lua#180]
I cannot get the script to run at all - I have extracted everything from the folder and moved it to the device, I get FGO to the screen where it chooses which battle to start, and start the script.  It shows a blank error screen and locks the Bluestacks player up until I reboot it.

Any ideas as to what I did wrong?  I'm not sure where I'd look to provide any other info as to what is actually erroring out.

**Comment by Ryrin45** [comment]
It only works for me if I turn on advanced graphics engine mode. I also use DirectX though it might work in OpenGL too.

**Comment by 29988122** [comment]
Nox is actually the recommended emulator for FGO - at least for JP version.

All other emulators are to an extent buggy with FGO, and prone to be "temporarily blocked"(emu detected, account safe).
