### ISSUE TITLE
Script Stuck on Support Screen

### ISSUE THREAD

**Issue by Neshura87** [29988122/Fate-Grand-Order_Lua#184]
When Starting the Script from the Quest menu it gets stuck in the support screen not doing anything. Starting the script in battle will result in the script doing nothing as well. I think the issue here is that my phone has a notch but I can't figure out how to fix it by reading through old issues.
Android version is 9.

**Comment by 29988122** [comment]
It is known that due to security restrictions, lots of functionalities of AnkuLua does not work on Android 7.0 and later version.

Unfortunately, the only choice remaining would be using emulators.
