### ISSUE TITLE
Script stops on 3rd turn on AnkuLua Pro 8.3

### ISSUE THREAD

**Issue by muvluvalt** [29988122/Fate-Grand-Order_Lua#187]
The script works fine on AnkuLua Trial 8.5. However, on AnkuLua Pro 8.3, the script works fine until the third turn, where it just completely stops. Any idea why it stops on the third turn (on Pro 8.3)?

This is how I configured the script.
```
Support_PreferredServants = ""
Support_PreferredCEs = "*chaldea_lunchtime.png,*mona_lisa.png"

--AutoSkill
Enable_Autoskill = 1
Skill_Confirmation = 1
Skill_Command = "ai6,#,c4,#,k25"

--AutoSkillList
Enable_Autoskill_List = 1

Autoskill_List[1][1] = "QP Farming"
Autoskill_List[1][2] = "ai6,#,c4,#,k25"

Autoskill_List[2][1] = "Lancer Assassin Embers"
Autoskill_List[2][2] = "aih4,#,b4,#,f5"
```
I use the Mage Association Uniform for the 20% NP charge and both can be easily completed in 3 turns.

For "QP Farming"
![image](https://user-images.githubusercontent.com/40586164/60816521-79c71000-a1cc-11e9-9db7-1f05ab3b2b77.png)

For "Lancer Assassin Embers"
![image](https://user-images.githubusercontent.com/40586164/60816935-50f34a80-a1cd-11e9-92ee-55b28b0ba943.png)

Edit: Script seems to stop at Turn 2 if I start it on the Menu Screen, and stops at Turn 3 if I start on Battle 1/3. No error message is given in both cases.

**Comment by iamcurseal** [comment]
I have the same problem.

**Comment by aqer** [comment]
Maybe you can update to AnkuLua Pro 8.5 and try again.
I don't have this problem when using 8.5 pro.

**Comment by wanabrar** [comment]
8.3 won't work tried it myself, has to be 8.5 and above.
