### ISSUE TITLE
Order Change not working properly

### ISSUE THREAD

**Issue by muvluvalt** [29988122/Fate-Grand-Order_Lua#190]
`Autoskill_List[3][1] = "Saber Rider Embers"
Autoskill_List[3][2] = "hi5,#,x21cg1def4,#,5"`

When I tried to order change, it failed because the [cursor wasn't able to click the ok button in the confirmation window](https://i.imgur.com/g4Imbr6.mp4) (despite having this variable set: `Skill_Confirmation = 1`). Other master skills work fine, but the order change just won't work. Any ideas why?

**Comment by aqer** [comment]
I think that order change doesn't consider the situation that Skill_confirmation = 1.
Maybe you can try Skill_Confirmation = 0 for order change.

**Comment by muvluvalt** [comment]
The problem is that if I set `Skill_Confirmation = 0`, my [Servant skills would then not be working properly](https://imgur.com/a/0BxZaD6). Not sure if Order Change would work since I set it at Turn 2, as the script already fails at Turn 1 without activating my Servant skills (with `Skill_Confirmation = 0`). 

Well, even if Order Change does work with `Skill_Confirmation = 0`, I think it just creates another problem, which is not activating my Servants' skills properly.

**Comment by aqer** [comment]
You haven't disable skill confirm in game option. The option is inside "munu".
When you disable it, the Skill Use dialog won't pop-up.

> The problem is that if I set `Skill_Confirmation = 0`, my [Servant skills would then not be working properly](https://imgur.com/a/0BxZaD6). Not sure if Order Change would work since I set it at Turn 2, as the script already fails at Turn 1 without activating my Servant skills (with `Skill_Confirmation = 0`).
> 
> Well, even if Order Change does work with `Skill_Confirmation = 0`, I think it just creates another problem, which is not activating my Servants' skills properly.

**Comment by muvluvalt** [comment]
> I am not sure what is "skill confirm" called in EN server, but you can find similar option in "menu".

Which file is this "menu" located at? I cannot seem to find the option in FGO_EN_REGULAR.lua, and I can't seem to find a filed named "menu.lua" either.

**Comment by aqer** [comment]
Its not a file.
It is an option of FGO game.
There is a "MENU" button and a "SKILL" button  in the right side of battle screen.
You can see them in your link..

**Comment by muvluvalt** [comment]
Yep I found it. And it works now with Skill_Confirmation = 0. I think there should be a disclaimer in the README that Order Change only works with Skill_Confirmation = 0 to avoid confusion. Thanks a lot by the way!

**Comment by forgehe** [comment]
You can manually fix this by editing the autoskill.lua file in the modules folder.

Change this:
```
local function BeginOrderChange()
	return function()
		OpenMasterSkillMenu()
		click(game.BATTLE_MASTER_SKILL_3_CLICK)
		wait(0.3)
```

Into this:
```
local function BeginOrderChange()
	return function()
		OpenMasterSkillMenu()
		click(game.BATTLE_MASTER_SKILL_3_CLICK)
		if Skill_Confirmation == 1 then
			click(game.BATTLE_SKILL_OK_CLICK)
		end
		wait(0.3)
```

(Preferrably on a computer, cuz formatting is a nightmare on mobile)
