### ISSUE TITLE
failing to dertermine card type?

### ISSUE THREAD

**Issue by bakuadachi** [29988122/Fate-Grand-Order_Lua#191]
When running the script (I kept it as vanilla with no modifications), it doesn't seem to click "battle" and or select the quest I am trying to do. Shortly after it prompts "failed to detect card type" with some coordinates right after. 

Currently running on Android 9.0, rooted with AnkuluaPro2.

**Comment by 29988122** [comment]
It is known that due to security restrictions, lots of functionalities of AnkuLua does not work on Android 7.0 and later version.

Unfortunately, the only choice remaining would be using emulators.
