### ISSUE TITLE
Scrip stuck after selecting Support, on both servers JP/NA

### ISSUE THREAD

**Issue by Panchovix** [29988122/Fate-Grand-Order_Lua#192]
Since the 7/8 Commit, "Add updating click for select first method on select support screen.", when farming for QP in both servers (NA and JP), it goes correctly to choose the 1st support option, but after that it gets stuck in the screen when you click to "go into battle".

It does the movement if as it was updating the support list, this results in swapping 4th and 6th servant, then it press "ok", but after that nothing happens, you have to manually click "go into battle", then it continues normally until again it has to select support and start another battle.

Tested on both JP/NA, both in Nox and Android phone, the issue happens in both root (phone) and daemon (nox and phone).

Using the 7/5 commit works without issues.

Nox is using 5.1.1, Android phone is using 7.1.2

**Comment by Panchovix** [comment]
To add, this happens with either "Support_SelectionMode = "preferred"" or "Support_SelectionMode = "first"", haven't tested manual

**Comment by aqer** [comment]
@Panchovix I guess the response after support click is slow in your environment, thus cause the control flow incorrect.

I add double check on support select screen. You can try the following link by replace support.lua on modules directory.

[https://github.com/aqer/Fate-Grand-Order_Lua/blob/master/modules/support.lua](https://github.com/aqer/Fate-Grand-Order_Lua/blob/master/modules/support.lua)

**Comment by Panchovix** [comment]
Thanks, that support.lua seems to fix the problem
