### ISSUE TITLE
a little help

### ISSUE THREAD

**Issue by Dracari** [29988122/Fate-Grand-Order_Lua#198]
Hi I'm quite new to all this and wanted to ask if it's possible to run this on bluestacks ( since Memu doesn't seem to work with FGO) and how to do it . When I start it I simply get a error in 30 secs and thats it.

**Comment by potchy** [comment]
No, it doesn't work with Bluestacks, unfortunately. Use Nox instead.

Em dom, 21 de jul de 2019 14:49, Dracari <notifications@github.com>
escreveu:
