### ISSUE TITLE
Auto friend gacha script does not function properly

### ISSUE THREAD

**Issue by MrTroika** [29988122/Fate-Grand-Order_Lua#199]
It clicks in the area of the summoned items after a summon, which causes it to stall out as soon as it clicks something you didn't set to auto burn.

**Comment by forgehe** [comment]
The problem looks like it starts looping the actions before everything finishes.

I fixed it by changing the `wait(3)` in line 24 with `wait(5)`, which gives fgo a bit more time to load.

It should work in most cases, but if your internet or phone lags a bit, it'll probably break the script again. You could change the wait to be even longer, but then that's a speed vs reliability issue there.

**Comment by 29988122** [comment]
https://github.com/29988122/Fate-Grand-Order_Lua/commit/0f07220cf79146b40c95b748638b6bb198efc8f3

This could work, I have no idea.
Slightly modified the behavior and click position. 

On my side, whether it's lagging or not, it's not clicking cards anymore.
***

Feel free to reopen the issue if it didn't work for you.
