### ISSUE TITLE
エラーについて。

### ISSUE THREAD

**Issue by Tototo0** [29988122/Fate-Grand-Order_Lua#2]
ama_daemonに入っているrun.batが動かない件については、
リンクの英語verのdaemonにてrun.batで解決しました、ありがとうございます。
起動後、種火ステージを右上に設定して JP_REGGULAR を実行した所
Will only select servant/danger enemy as noble phantasm
target, please check github futher detail
と出たのですが、これは私が使っている端末が 1980x1280なのが関係あるのでしょうか? 機種はXiaomi6です。

**Comment by 29988122** [comment]
あのメッセージが出たと同時にスクリプトは動作するはず…
（メッセージがない＝メニュー画面をディテクトできない；メッセージは出るが作動しない＝何らかの原因でシステムは入力を受け付けない）

今私にレポートされた実行不可のケースはいくつかあり、どれも小米Xiaomiです。
Ankuluaの設定で、クリック方式を変えてみてください。
デフォルトの「root」から、「(beta)クリック以外の画面触る函數は他の方法を使う」に変え、結果を知らせて下さい。（結果オーライか、どこで止まったのか、全くだめなのか、数回を実行したら結果をまとめる）

**Comment by Tototo0** [comment]
お返事遅れ申し訳ありません、クリック方式の方を試してみましたがどれもダメでした。
一応動画を取ったので確認して頂けますか?

**Comment by 29988122** [comment]
Ankuluaの原作者と検討中…少々お待ち下さい。

**Comment by Tototo0** [comment]
お手数をお掛けして申し訳ありません、よろしくお願いします。
FRepではタッチ操作が出来ていたのですが。

**Comment by 29988122** [comment]
想像以上に難しいバグのようだ
フレームワークの作者によると、Xiaomiのいくつかの機種．アンドロイドバージョンでしか発生しない、いわばcompatibilityの問題

特定するには
もうちょっと時間がかかりそうなので、気長にお待ち下さいｗ

**Comment by Tototo0** [comment]
なるほど…わかりました。
ちょうど別端末を購入しようと考えていたので良い機会です、色々とありがとうございます!!

ちなみに HuaweiのM3というタブレットで試した所、何故かスクリーンショットを取ると種火クエをタッチするようになっているのですがmenuの画像など取り直す必要があるのでしょうか?
必要であれば動画も取ります。

**Comment by 29988122** [comment]
According to person email with tototo0, the issue has been resolved.
