### ISSUE TITLE
An Opinion and wanted some advice.

### ISSUE THREAD

**Issue by saiyansoul** [29988122/Fate-Grand-Order_Lua#20]
with the auto skill,the script is good for farm exp/qp.

But,in my case it's not 'decent' for event.the script keep choosing for buster card which makes the servant can't fill the np.I was testing it on the NA for Saber wars,like i said.They can't fill the NP which makes my party got wiped out :/

some of the bosses need to be NPed even tho I have Damage CE.

So,any advice?

btw,Great job adding the Auto skill features.It helped a lot for farming exp!
Hope this project will be optimized for Event in the future.Keep doing the great work and good luck!

**Comment by ryuga93** [comment]
The Saber War needed some tweak. The bosses are not the threat but the mobs. Take screenshots on the quests you want to farm on, then crop out the mobs' class. Then replace the target_servant.png and target_danger.png

Here's the example: https://imgur.com/a/CSHHb

I'm farming the Scathach node without problem, just let the script detect the saber mobs to finish them first. Then plan your skill accordingly, eg: Scathach uses NP every 5th turn, so activate Evade skills etc...

I can implement type focusing, which will prioritize the card type depend on user selection. 

Anyway, here's a hint for future events:
Run through the quest manually first, and take note on how you solve the quest. Then change the script behaviour to match it.

**Comment by saiyansoul** [comment]
Thanks for the advice.

I just need Okita To 1 shot scath at last turn,that saves my team.But,anyway I'll try again tomorrow.

Bra,i have some trouble about Choosing priority target.Should I change both picture to saber icon(for the mobs)?and can you explain about target choosen?Bcs i didn't see it in the Lua script.

Oh and one more, can you tell me how many turn for scath that you got for 1 run?

**Comment by ryuga93** [comment]
> Bra,i have some trouble about Choosing priority target.Should I change both picture to saber icon(for the mobs)?and can you explain about target choosen?Bcs i didn't see it in the Lua script.

Change both. When you want farm the Jeanne node, change one into Assassin and one into Rider. 
It's in the regular.lua, two places in function battle() to comment. One before targetchoose() and one before ultcard(), make sure you leave npClicked == 0 as it is.

> Oh and one more, can you tell me how many turn for scath that you got for 1 run?
Around 6 to 8 turns, fast enough before her 2nd NP. My usable servants are Altera, Nero, Okita & a support (random :/), damned cost not enough =.=.  Kill the mobs first and let scath fills your NP.

**Comment by saiyansoul** [comment]
Wew,a pretty high tier servant lol.

I bring herc,alter and supp okita.
I'll try later,need to screenshot first.

Should i resize the image with the same size as the default target.png?Then convert it to png from jpg right?i did this yesterday but end up failed.
Maybe because of the width,Mine is 1280 x 550.(it's around that number)

**Comment by ryuga93** [comment]
You need to resize to 1280x720 first, then crop the image out. No need to have same size as the cropped png, as long as the screen size before crop is 1280x720. Use png, jpg is not supported.

Rolls are just maths, though people called it "rituals". Here's a tip, the card pool reloads everyday, and depletes it's SSR probability whenever 1 is drew out. That's easy for JP, since when the server reloads, at least half of players already asleep. But for NA, 0:00 UTC most players are still active...

**Comment by saiyansoul** [comment]
Ah,I got it wrong about the resizing,I cropped first then resize.Thanks about this,helps a lot!

Oh i see,so 00.00 you do the roll I guess?It will increase the probability of SSR right?

**Comment by ryuga93** [comment]
Yea, just the probability is lower than the JP. Got Altera, Tamamo Caster & Okita. Wanted Jack for Christmas but got Carmilla instead. Now sitting at 190 sq for Nero bride.

**Comment by saiyansoul** [comment]
10 times better than single roll right?At 00.00.


Btw,jalter rate up with new costume on JP coming on the block.

**Comment by ryuga93** [comment]
That depends on your preference, for me, multiple single roll is better. I just roll until a common comes up and stop. Just try and error until you find your "ritual"

**Comment by saiyansoul** [comment]
Thanks.
Especially for the script explanation.

I think you can close this thread now.

**Comment by ryuga93** [comment]
> EDIT:I tried to replace the servant danger and target to saber(since I'm farming on scathach).Now comes the problem,It did aim for Saber but on battle 2 and 3 The script focus on enemy 2 and won't aim for enemy 1 which is a saber in this case.

Did you comment out targetchoosen?

**Comment by saiyansoul** [comment]
Both before Ultcard and target choose already set to 1 beforehand.
I found this still on '0'.
Should i change this?
![screenshot_20180110-073040](https://user-images.githubusercontent.com/31531975/34750222-879b9422-f5d8-11e7-883e-1794a00f9e7a.jpg)

**Comment by ryuga93** [comment]
```
      --if targetchoosen ~= 1 then
		targetchoose()
	--end	
  
    if --[[targetchoosen == 1 and]] npClicked == 0 then
        ultcard()
    end
```

**Comment by saiyansoul** [comment]
For that two, it's 1 from the default.
Maybe i need to narrow the cropping.

I'll give it a try later and report back.

**Comment by ryuga93** [comment]
No I mean just follow the code above, comment out those lines using --

**Comment by saiyansoul** [comment]
Precisely like this,sir?
sorry.I'm blind at code like this
![screenshot_20180110-155134](https://user-images.githubusercontent.com/31531975/34763634-6d645012-f61e-11e7-8b19-b5e0b7c65114.jpg)

**Comment by saiyansoul** [comment]
So,like this?

**Comment by ryuga93** [comment]
if --[[targetchoosen == 1 and]] npClicked == 0 then

you forgot the [[ ]] for the second one

**Comment by 29988122** [comment]
@ryuga93 
```
Here's a tip, the card pool reloads everyday, and depletes it's SSR probability whenever 1 is drew out
```
Not really, since the pseudo-probability could also be "personal".

That depends on the company. 

Some wants to control "Total SSR count in the game", this often appeared in MMORPGs. Because they have competition, therefore they must control the average strength among players.

Another would want to control"SSR/SR/R ratio of a single user". This often appeared in mobile/gatcha games.
You might have heard a noun called "pity counter", and that's a way for the company to ensure that whenever you did NOT get a SSR, the pity counter would increase, effectively make the SSR rate from 1% to maybe...1.05 percent, until you get one and the counter would be reset to 0.
This is used to prevent the statistical outliers(left side of bell curve - the so called 歐洲人 - 臉黑玩家).

**Comment by ryuga93** [comment]
Ah I see, I have this theory because I saw a video of someone using 2 device to draw at the same time, ended up getting the same 10 cards in JP. Plus in JP I can roll better cards after 24:00 JST, >4* CE or servant in multi single. But that's 2 years ago :/

**Comment by saiyansoul** [comment]
BRO!

It actually worked out!
Thank you very much!manage to get 10-12 turn on Scathach.Only use skill 1 time since I didn't count for the turn until it available to use againm
