### ISSUE TITLE
Event Script stops during dialogue after completing a quest in the Summer Event

### ISSUE THREAD

**Issue by DekaRose** [29988122/Fate-Grand-Order_Lua#200]
I'm talking about exchanges from the team members after finishing a quest. Is there a way I can add an extra click or two, or something?

**Comment by 29988122** [comment]
You can check this thread for instructions!
https://github.com/29988122/Fate-Grand-Order_Lua/issues/201

Report if anything irregular occurred, and I'll see if I can do anything..
