### ISSUE TITLE
Media Projection Screenshot Fail

### ISSUE THREAD

**Issue by squalls1** [29988122/Fate-Grand-Order_Lua#205]
Receive the following error every now and again. Was only occasional before, now seems to happen every time I run the script. Script works great, sometimes for over an hour at a time, then randomly spits out this error. Haven't customized or changed the script at all. Any idea what this refers to?

Device Info: Pixel 2 XL (Google Fi), running Android 9.0 stock. 64 GB storage/4 GB RAM.

![Screenshot_20190805-202200](https://user-images.githubusercontent.com/11143277/62592485-4c3fb600-b8a1-11e9-9d98-ce066bcb058d.png)

**Comment by aqer** [comment]
Is your Ankulua version 8.5.2?
Sometimes I have the same problem when using Ankulua 8.5.2
So I turn back to use  8.5.0

**Comment by squalls1** [comment]
It was yesterday when the problem started getting worse. I downgraded to 8.5.1, which has been working fine the last day or so until it started acting up again.

I will uninstall 8.5.1 and downgrade to 8.5.0 and see if that fixes the issue. Thanks for the quick response! I will keep you posted.
