### ISSUE TITLE
SUPPORT_LIST_ITEM_REGION_ARRAY?

### ISSUE THREAD

**Issue by RalphixJP** [29988122/Fate-Grand-Order_Lua#206]
I'm getting this error every hour when it's trying to select my preferred support servant from my friends list. 

![Screenshot_2019-08-07-22-36-08](https://user-images.githubusercontent.com/15004197/62671272-2fb88200-b964-11e9-8660-fc7084137c99.jpg)

**Comment by muvluvalt** [comment]
I'm also experiencing this problem in the JP server, but only when I'm selecting Waver with Teatime CE (default image inside IMAGE_SUPPORT). I don't have any trouble with any servant + Mona Lisa Lily CE (custom screenshot by me). Note that the image file name of teatime is "teatime.png" without the asterisk in front.

```
Support_PreferredServants = "waver4.png, waver3.png, waver2.png, waver1.png"
Support_PreferredCEs = "teatime.png"
```

```
Support_PreferredServants = ""
Support_PreferredCEs = "*mona_lisa_lily.png"
```

**Comment by TheIanator** [comment]
The script needs to scroll in precise intervals to work. It recently stopped working for me as well (on JP, haven't tested NA). Don't think it's a problem with the script as there's been no changes to how it scrolls the support screen and scripts that were working two weeks ago fail today.

So it's probably either a change to the game or a change to AnkuLua. Maybe downgrading AnkuLua might fix the problem like in issue #205.

**Comment by muvluvalt** [comment]
The issue first occurred to me when I was at version 8.5.0. That was when I upgraded to version 8.5.2 but the problem persisted. Downgrading to any version below 8.5.0 would make the script completely unusable, which was why I didn't do it.

https://github.com/29988122/Fate-Grand-Order_Lua/issues/187
https://github.com/29988122/Fate-Grand-Order_Lua/issues/185

**Comment by RalphixJP** [comment]
> Actually, never mind. It was because I didn't put the asterisk in front of the file name. Can't believe that I made such a dumb mistake.
> 
> `Support_PreferredCEs = "*teatime.png"`
> 
> Edit: No wait, problem still persists even after I added the asterisk. Downgrading the version also doesn't work.

Adding an * only makes it so that the CE the support has is MLB.

**Comment by TryBane** [comment]
This may very likely be due to a slight UI change with the anniversary update. I will need to further investigate the issue before I can say definitively if I have a fix.

**Comment by TryBane** [comment]
Alright, after speaking with a friend who uses JP, he had a similar issue. He had a temporary fix, which I have applied to the script. Give it a try to see if it works as intended. Please post your results, good or bad.

**Comment by potchy** [comment]
errrrrr now it breaks for me
reverted your commit on my private fork

**Comment by muvluvalt** [comment]
Tested and working on JP. Not sure about NA.

**Comment by TryBane** [comment]
@potchy Someone on NA said that it's working just fine. Not sure? Worst case, we can make 2 variables, one used for JP and another for NA.

**Comment by potchy** [comment]
it works if the script finds a match not too far into the list
after ~3 swipes the entries start getting out of bounds

**Comment by TryBane** [comment]
Oh, I see.... I only ever use 3 swipes myself anyways... The cause seems to be some lag on the game side messing with the scroll that is done. I adjusted the offset done to change the scroll amount, keeping it from going out of bounds so much when there is a little lag... Wonder how to fix this one >.>

**Comment by potchy** [comment]
well, for now, just move `SUPPORT_SWIPE_END_CLICK` value to the `_REGULAR` config files, like `StageCountRegion`

**Comment by TryBane** [comment]
That is a fair solution for now

**Comment by TryBane** [comment]
Alright, change implemented. As far as I'm aware, CN isn't having this issues.

**Comment by RalphixJP** [comment]
This error pops up now
![image](https://user-images.githubusercontent.com/15004197/62839820-4c9fce80-bc5e-11e9-999b-85bb78d8cee6.png)

**Comment by RoyJames** [comment]
Pulled commit f4fe480 and got the error below. SUPPORT_SWIPE_END_CLICK in support.lua is not properly defined?
![Screenshot_20190811-183208](https://user-images.githubusercontent.com/8073842/62840337-e8750e80-bc4d-11e9-8158-4a0242544735.jpg)

**Comment by TryBane** [comment]
There were multiple commits, not just one. Let me take a look.

**Comment by TryBane** [comment]
@RoyJames @RalphixJP Please download the latest version and give it a try. I believe it should work as intended now.

**Comment by RalphixJP** [comment]
![image](https://user-images.githubusercontent.com/15004197/62894761-63f0c180-bd1b-11e9-8612-66f4159d36aa.png)
@TryBane

**Comment by RoyJames** [comment]
> @RoyJames @RalphixJP Please download the latest version and give it a try. I believe it should work as intended now.

It's working fine on my side now. Been running for 12 hours w/ no problem. Thx!

**Comment by TryBane** [comment]
Awesome! @RalphixJP If that is what came up after I posted that comment, then I am unsure of what the issue is :(
