### ISSUE TITLE
Cannot continue game at friend request prompt

### ISSUE THREAD

**Issue by RoyJames** [29988122/Fate-Grand-Order_Lua#209]
Not sure if this is also due to the UI change in JP server? If I got the friend request prompt after finishing a request, the script will keep clicking just a little bit outside the "send friend request" button, but will not trigger any UI event. After some time the new "repeat quest" window pops up, but the script does not recognize this window and hangs there.
![Screenshot_20190812-231327](https://user-images.githubusercontent.com/8073842/62920863-d1bcdd80-bd5b-11e9-812c-74ecccd56658.jpg)

**Comment by TryBane** [comment]
Okay, I wasn't aware of this scenario when I wrote the fix. I will make an adjustment that should solve the issue.

**Comment by TryBane** [comment]
But first, @RoyJames could you record the scenario and post it here? You don't have to use the script, just do it manually with a non-friend.

**Comment by RoyJames** [comment]
> But first, @RoyJames could you record the scenario and post it here? You don't have to use the script, just do it manually with a non-friend.

Sure. I can do that in approx 10h.

**Comment by RoyJames** [comment]
OK I recorded this scenario manually. Just trying to mimic what the script did. After clicking the "close" button, the "repeat quest" window prompts up and the script fails to react to it.
[bug_report.mp4.zip](https://github.com/29988122/Fate-Grand-Order_Lua/files/3499879/bug_report.mp4.zip)

**Comment by TryBane** [comment]
Okay, it isn't allowing me to watch the file. I don't know why, but it keeps giving errors. It would be easier if you could upload it to youtube and just link it. It can be an unlisted video or something. Alternatively, is creating it using a different format or without Zipping the file.

**Comment by RoyJames** [comment]
> Okay, it isn't allowing me to watch the file. I don't know why, but it keeps giving errors. It would be easier if you could upload it to youtube and just link it. It can be an unlisted video or something. Alternatively, is creating it using a different format or without Zipping the file.

Just did that https://www.youtube.com/watch?v=zf_btoVWKFg

**Comment by 29988122** [comment]
Logic fixed

Please try the latest commit to see if this works.
