### ISSUE TITLE
FGO-NA Script doesn't click the "Start" button at the begining of the quest

### ISSUE THREAD

**Issue by Kizuro** [29988122/Fate-Grand-Order_Lua#210]
The script work perfectly when it was in the battle and quest selection, however when the script enter the team overview, just one click away from entering the battle quest, it doesnt click the "Start" button so that the game could enter the battle phase. Any tips on how to fix this problem?

**Comment by 29988122** [comment]
Do you update your EN_***.lua?

Without IsContinuing == 0 variable inside it, it will not work.

Anyway I did a little tweak and now it should work with or without
IsContinuing == 0.


Kizuro <notifications@github.com> 於 2019年8月15日 週四 下午9:44寫道：

**Comment by Kizuro** [comment]
I just follow the instruction as it was written. Pretty new to this kind of thing, so it was trial and error to me.
Should I just add those variable at the end of FGO_EN_REGULAR.lua file?

**Comment by 29988122** [comment]
You compare this file
https://github.com/29988122/Fate-Grand-Order_Lua/blob/master/FGO_EN_REGULAR.lua
to your local file, and check if anything's missing on your side

Just copy paste them xD

**Comment by Kizuro** [comment]
There doesnt seem to be anything missing. Let me check for a while

**Comment by Kizuro** [comment]
still doesnt start. Here's my file
[FGO_EN_REGULAR.txt](https://github.com/29988122/Fate-Grand-Order_Lua/files/3506126/FGO_EN_REGULAR.txt)

**Comment by darrison** [comment]
I have the same issue with the newest version as well. It would just stall on clicking start battle after selecting a support. I switched back to an older version of FGO Lua from back in May and that one worked for me under the same conditions. 

I am using the latest version of Nox and latest version of Ankulua Trial.

**Comment by Kizuro** [comment]
Looks like instead of clicking the "Start Quest" button, the bot simply click the left side of it. Which mean it the problem came from the image.

**Comment by Kizuro** [comment]
--Only for JP currently. Searches for the Continue option after select Free Quests
	if GameRegion == "JP" and game.CONTINUE_REGION:exists(GeneralImagePath .. "confirm.png") then
		IsContinuing = 1 -- Needed to show we don't need to enter the "StartQuest" function
From what I see the IsContinuing  only work for JP, when will it able to do so on NA?

**Comment by preludeofshadows** [comment]
I'm having this same issue. It seems that the bot attempts to click "start quest" faster than the game can register that "start quest" has even loaded on screen. Replicating this bug can be pretty inconsistent since sometimes the quest starts no issue, could vary depending on the speed of the device the script is run on. Previous versions had a small delay before attempting to start the quest, so I'm assuming that bringing the delay back will fix everything.

I'm using the latest version of Nox and latest version of AnkuluaPro2.

**Comment by forgehe** [comment]
Adding the delay to regular.lua in line 203 worked for me.

Can you replace the regular.lua file with this one and see if it works?
https://github.com/forgehe/Fate-Grand-Order_Lua/blob/master/regular.lua


Or just make this change manually on line 200

````
--Friend selection.
	local hasSelectedSupport = support.selectSupport(Support_SelectionMode)
	if hasSelectedSupport == true then
		if IsContinuing == 0 then
			StartQuest()
		elseif IsContinuing == nil then
			StartQuest()
		end
	end
````

with 

````
--Friend selection.
	local hasSelectedSupport = support.selectSupport(Support_SelectionMode)
	if hasSelectedSupport == true then
		if IsContinuing == 0 then
			wait(2.5)
			StartQuest()
		elseif IsContinuing == nil then
			wait(2.5)
			StartQuest()
		end
	end
````

**Comment by preludeofshadows** [comment]
> Adding the delay to regular.lua in line 203 worked for me.
> 
> Can you replace the regular.lua file with this one and see if it works?
> https://github.com/forgehe/Fate-Grand-Order_Lua/blob/master/regular.lua
> 
> Or just make this change manually on line 200
> 
> ```
> --Friend selection.
> 	local hasSelectedSupport = support.selectSupport(Support_SelectionMode)
> 	if hasSelectedSupport == true then
> 		if IsContinuing == 0 then
> 			StartQuest()
> 		elseif IsContinuing == nil then
> 			StartQuest()
> 		end
> 	end
> ```
> 
> with
> 
> ```
> --Friend selection.
> 	local hasSelectedSupport = support.selectSupport(Support_SelectionMode)
> 	if hasSelectedSupport == true then
> 		if IsContinuing == 0 then
> 			wait(2.5)
> 			StartQuest()
> 		elseif IsContinuing == nil then
> 			wait(2.5)
> 			StartQuest()
> 		end
> 	end
> ```

This worked perfectly. Everything is now running as it should.

**Comment by 29988122** [comment]
I still dunno why this matters, but I added this fix to the repo anyway.

Thank you all for finding this out!

**Comment by TryBane** [comment]
I must've forgotten to add a delay in that location. The issue was that the loading the team overview screen took longer on their devices than was expected by the script so it clicked the location prematurely.
