### ISSUE TITLE
Runtime Error after picking a support.

### ISSUE THREAD

**Issue by Kizuro** [29988122/Fate-Grand-Order_Lua#213]
![image](https://user-images.githubusercontent.com/10566686/63226702-77ae9300-c207-11e9-8c52-d7c729d3e8e5.png)
I have no idea how did this happen. I was using the latest version of AnkuLua Pro 2, using Nox, and already check the accessibility of app. Previously, the script work fine without this problem, but this occur when I re-open the Nox and re-click the nox_player.run.bat because apparently you need to reinstall daemon everytime you wish to play the script.

Thank you in advance.

**Comment by TryBane** [comment]
This is odd indeed. Have you tried to restart Nox? If not, I would recommend trying to redownload the script and see if a fresh script still has this issue.

**Comment by Kizuro** [comment]
Restarting Nox doesnt help, but redownloading the script seems to fix the problem. Looks like I was inputing a wrong command for the lua file.
