### ISSUE TITLE
Script not selecting Start Quest

### ISSUE THREAD

**Issue by raspberrytealeaf** [29988122/Fate-Grand-Order_Lua#214]
I'm running FGO LUA on my phone (Pixel 3).

I started trying to farm doors today, and this is what happens:

1. Script selects the 40 ap quest correctly
2. Script finds a support w/Mona Lisa correctly
3. On the quest screen, it selects the region in-between "Help" and "Total Cost" on the bottom, not Start Quest
4. Sits there forever until I either manually hit Start Quest or shut off script

**Comment by raspberrytealeaf** [comment]
Also:

1. When I hit Start Quest myself, it seems to have 0 issue finding skills / NPs / other regions to click on correctly.
2. I also tried messing around w/the game.lua file and manually changing the start region myself, but it kept clicking the same area.

**Comment by TryBane** [comment]
Is the device you are using have a notch for camera on the screen? And by that, I mean does the screen have a cutout where the camera sits?

**Comment by TryBane** [comment]
I'm pretty sure this is due to not enough delay between selecting the servant and the menu to start quest coming up.

**Comment by raspberrytealeaf** [comment]
Sorry, forgot I opened this thread.

Yes, that appears to be the issue. I put a wait cmd before it selects the start quest button and it seems to work fine lol. Guess my pixel is too slow. 😛
