### ISSUE TITLE
JP script not working 

### ISSUE THREAD

**Issue by barry3672** [29988122/Fate-Grand-Order_Lua#215]
![Screenshot_2019-08-22-18-15-27](https://user-images.githubusercontent.com/53958608/63529483-628a7a80-c50d-11e9-8b8d-771535eb0adb.png)
My NA script runs just fine, but there's a problem with the JP one. I tried to find the problem, but I don't know what to do.

**Comment by TryBane** [comment]
https://github.com/29988122/Fate-Grand-Order_Lua/blob/master/README.md#syntax-error-unexpected-symbol-near-%E7%87%8E

**Comment by barry3672** [comment]
Should have looked around here a little bit, but yeah it worked.
