### ISSUE TITLE
请问Lua实现对界面的监控和对操作的记录的难度大吗

### ISSUE THREAD

**Issue by Xianbei233** [29988122/Fate-Grand-Order_Lua#22]
如题，想先弄个这个出来，之后做一个jo本傻瓜式生成器配合本项目使用

**Comment by 29988122** [comment]
最新的commit已經包含autoskill，在指定的回合使用特定技能的功能了
(只差關卡截圖就能支持CN版本)

有了這個我想應該就不必用到巨集錄製 : p

**Comment by 29988122** [comment]
@Xianbei233 
已經支持CN版本了，您可以看一下現在的自動技能施放符不符合您的需求~
