### ISSUE TITLE
AP ran out error

### ISSUE THREAD

**Issue by Enfinit** [29988122/Fate-Grand-Order_Lua#224]
I'm having an issue with the auto refill function of the script. Whenever I don't have enough AP, it goes to the refill screen only to error out and give me an "AP Ran Out" error and the script stops. I have it set to use 7 silver apples but it does this with every other option I choose. Not sure exactly what I'm doing wrong.

**Comment by GleipnirFR** [comment]
Can you post the "AutoRefill Stamina" section of your lua file, please ? That could be helpful for pinpointing the issue :)

**Comment by Enfinit** [comment]
Of the EN lua? 

--AutoRefill Stamina
Refill_Enabled = 1
Refill_Resource = "Gold"
Refill_Repetitions = 5

Ran out of silver apples so I changed to gold.
