### ISSUE TITLE
Casting NP at the end of the round

### ISSUE THREAD

**Issue by vit2657** [29988122/Fate-Grand-Order_Lua#226]
Is it possible to cast NP as a 3rd card with auto skill? Its clearly not per documentation, but I wonder if its possible to maybe modify code a bit to do it (hint me where to look please).

Use case: Fran np as a 3rd card, cause bot doesn't care about her self stun and casts her cards anyway.

**Comment by Rajvir8** [comment]
They are working on that now actually, it's currently in the Pull requests, Trybane is spearheading the project right now actually. 

Here's the link to their code if you want a look
https://github.com/29988122/Fate-Grand-Order_Lua/pull/221

**Comment by TryBane** [comment]
It should work, as I've been using it myself for farming with Fran on the current Petal node against Helena using SoAs spreadsheet. It almost always works with the occasional miss (probably due to lag)

**Comment by vit2657** [comment]
Right now I have used hacky fix for myself to never use effective(weak) cards, this way I always 3t with some face cards on w3 that is not Fran.

Another problem that I have encountered, is sometimes after order change with plagsuit bot tries to click skill too fast, which leads to a miss. And as I have a waver 1 skill right after order change, it will just click on a servant right away and lead to being stuck on servant info popup (as skill wasn't selected). I have kinda fixed this by adding a 0.5 delay after the order change, but haven't really had time to report this so leaving this here now @TryBane

**Comment by TryBane** [comment]
Yes, the skill clicking problem was a known issue. Actually, if you look at my Preload NP pull requests at #221 you'll see in the changes to Autoskill at line 32 that I specifically tackled this issue once and for all XD

And besides that, you get to use the Autoskill option that'll allow you to use your cards prior to NP as well. The format is as such:

"a1cdn25"

Where 'n' is used to denote that you are hitting with face cards first before NP, and the number '2' is how many to hit. Naturally only 1 and 2 are used as a 3rd would be like normal card clicking and the goal is for clicking prior to NP.

**Comment by vit2657** [comment]
Thanks, will test your branch later I guess, cause don't wanna interrupt farming for now as its perfect 3t

**Comment by reconman** [comment]
Fixed with #335
