### ISSUE TITLE
1. Autoskill misses the rest of the skills when target not specified. 2. Autoskill error using skills with requirements.

### ISSUE THREAD

**Issue by forgehe** [29988122/Fate-Grand-Order_Lua#227]
1. When autoskill uses a skill that targets, but doesn't specify a target, it will attempt to go through the rest of the skills, but fail to click the rest of the skills. 

2. Some skills require some requirement to activate (eg. Summer Fran's Skills / Moriarty's 2nd Skill).
The error msg can only be closed by clicking the Close button, getting the script stuck.

**Comment by forgehe** [comment]
I can fix the 2nd problem by clicking where the close button would be immediately after selecting a skill.
The click would close the dialogue if it pops up, or wouldn't be registered while the skill animation occurs

line 30
````
local function CastSkill(location)
	return function()
		click(location)
		if Skill_Confirmation == 1 then
			click(game.BATTLE_SKILL_OK_CLICK)
		end
		click(game.BATTLE_SKILL_ERROR_CLICK) -- for closing error msg when you click on a skill that has a requirement. also resets state when clicked on a skill with a cooldown.

		WaitForAnimationToFinish()
	end
end
````
changed in autoskill.lua and 
```game.BATTLE_SKILL_ERROR_CLICK = Location(1280,1160)
added in game.lua

I'm still not sure how to combat the issue with the targeting though.  (besides writing better/more specific autoskill sequences lol)

**Comment by TryBane** [comment]
The Autoskill program assumes the user knows to specify targets when the skill calls for it. Unless you are expecting us to come up with a scenario where we assume the user doesn't know how to set it up, that should be fine for almost anybody to use. As for the instance with the requirements like Frans 3rd skill, can either implement your own fix or I can think of something that would fix it better.

**Comment by TryBane** [comment]
One of the things I am curious of regarding your own implementation for the solution regarding the second issue, is whether it affects the skill targeting of allies.

**Comment by forgehe** [comment]
The first issue really is an edge case. The main instances where the issue happens is with the support units, as they can be different units each time (if set to first instead of preferred). And since most ppl have the supports as their 3rd unit, it won't affect too many servants.

So far, the 2nd issue has been working fine for me. It selects right below the skill targeting of allies would be. But I would like to see if that differs on different devices.

**Comment by forgehe** [comment]
I'm going to close this issue. 
I'm still using my version of the script, where it taps outside to ensure autoskill still continues if you click on a skill that is still on cooldown.
It has been working fine for me this entire time. 
I did modify the skill targeting of allies to be a bit higher up, to avoid tapping on the servant and bringing up the profile.
The skill targeting of allies does affect the skill targeting of enemies however, so you would have to set the enemy targeting at the end of each turn. 
In the end, it was still a lot of variables modified for a pretty minimal benefit.
