### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Draw99Gray** [29988122/Fate-Grand-Order_Lua#228]
Modified the Nerofest script with my own skills, press play and it shows this screen
![Screenshot_1](https://user-images.githubusercontent.com/54757982/64071456-f4526000-cc50-11e9-83d2-8f24962453db.png)

this is the script
https://pastebin.com/raw/bDH1nJ3Q

**Comment by TryBane** [comment]
This is an issue regarding Support. Can you screenshot or post your support settings here?

**Comment by TryBane** [comment]
Nevermind, the code was on the bottom. You need to have "" after the Craft Essence selection. Even if you don't want anything specific. Please place empty pair of " or "Any" will work too.

**Comment by Draw99Gray** [comment]
Sorry, could you tell me which line should i modify?
thanks!

**Comment by TryBane** [comment]
Line 36, the line is currently:
Support_PreferredCEs =

It needs to be:
Support_PreferredCEs = ""

**Comment by Draw99Gray** [comment]
Isn't the line 
Support_PreferredCEs = "*cheer_for_master.png"
Since i need the macro to identify a MLB CFM CE for farming purposes

**Comment by TryBane** [comment]
If that is what you need, then yes. But leaving it blank with no quotes makes it nil, which is the error that was thrown.

**Comment by Draw99Gray** [comment]
It seems it was because i was using ankulua 8.3.0, installed 8.5.2 and it works fine

**Comment by TryBane** [comment]
Great! What's important is that it works now :D

**Comment by Draw99Gray** [comment]
Yeah, almost all of these newly posted issues are caused by a old cracked version of ankulua 8.3.0 that was posted on 4chan.
just make sure to ask which version are they using for now
