### ISSUE TITLE
Runtime Error: The Servant or Craft Essence is not contained

### ISSUE THREAD

**Issue by pastarice** [29988122/Fate-Grand-Order_Lua#229]
Hello

I've run into this issue multiple times in the past few days, please see attached screenshots.
It's always when selecting a support
[screenshot1](https://media.discordapp.net/attachments/360540135936491521/617544989983113226/unknown.png)
[screenshot2](https://cdn.discordapp.com/attachments/360540135936491521/617545377221967872/unknown.png)

**Comment by TryBane** [comment]
I have a potential fix for this, give the pending merge at #222 a try

**Comment by TryBane** [comment]
Please reply on the merge whether it has any issues or not

**Comment by reconman** [comment]
No reply from user, closing now.
