### ISSUE TITLE
Selecting Target & Card Issue

### ISSUE THREAD

**Issue by saiyansoul** [29988122/Fate-Grand-Order_Lua#23]
Long story short

I downloaded the new Master since Jerry Released it.

Before that everything works fine and since I'm curious whats in the update,i gave the new one a try.
I've experienced some problems.

1.Selecting target,like at firts before Ryuga tell me how.The Script won't change to the 2nd target which is has the same name/class as the first one.I've tried to change the regular.lua script like I used to.
Instead of a success,it wont even run.It shows me An error instead and won't run the script.

2.I have some trouble with the card priority.It used to Buster then arts.Now,it's like so random and often doing some Card with the same servant(which is different from what i've experienced)
Then,instead of Arts it chose Quick instead.Cmon man,quick meme is dead

so,any advice?

**Comment by ryuga93** [comment]
Are you using the one cloned from Master or the 1.6.0 release?

 If you cloned the code directly from Master:
1) You can't just replace the regular.lua, there is a new variable for different server behavior. 

2) The card type region and some some wait time changed but I didn't see any problem with that changes. Haven't tested the new script yet though. That's the behaviour when the card type can't be identified, it will just select the first 3.

So, for now use the old scripts, your customized FGO_REGULAR_EN.lua and regular.lua

**Comment by 29988122** [comment]
The larger selection area (was) for CN version, guess I can revert it cuz it's not needed anymore.

Will have a CN supported version release later..

**Comment by 29988122** [comment]
Try the latest release, should be OK.
Tested on CN JP server, since the code has been reverted, EN server should be OK, tool
