### ISSUE TITLE
Some questions about editing the .lua file.

### ISSUE THREAD

**Issue by consistentescape** [29988122/Fate-Grand-Order_Lua#230]
I saw Support_FriendNames in the .lua file but I am not sure how to use it. Will inputting my friends' name auto pick his servant without the need of specifying the details? Or do I still need to add the images?

Edit: Had another question. Does the script check every class category to find the specified servant? Because I don't think there's any way to input the servant class.

**Comment by potchy** [comment]
For your first question, you need to take a screenshot of your friend's names.
It's still undocumented, so read this: https://github.com/29988122/Fate-Grand-Order_Lua/issues/212#issuecomment-524125097

For the second, no, the script will only scroll through the active tab of your support list.
