### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MrPotSticker** [29988122/Fate-Grand-Order_Lua#231]
So im using the lua with memu since I don't have a android phone. How do I edit the luas to use nps and such

**Comment by TryBane** [comment]
I suggestion downloading this app on the emulator to make the editing process easier:

https://play.google.com/store/apps/details?id=com.quseit.qlua5pro2

You will want to edit the FGO_XX_REGULAR file that suits your region. Follow the instructions listed in the readme file here on the site or that is downloaded for information on setting it up.
