### ISSUE TITLE
Cant detect MLB Cheer for Master

### ISSUE THREAD

**Issue by GenosisRex** [29988122/Fate-Grand-Order_Lua#234]
Not sure if it's for all CE or only for cheer for master.

**Comment by TryBane** [comment]
What is the device you are using?
Also what version of Ankulua are you using?

**Comment by GenosisRex** [comment]
Using the pro version, I included the * before the CE too. But it seems like the AI just scrolls past the MLB CE. Without the * though, it detects correctly to select Waver + Cheer for Master.

**Comment by Rajvir8** [comment]
Replace the Limit Broken CE, I had this problem earlier and wasn't sure if the update would fix it so I once again replaced the limit Broken CE picture.

Here's the Issue
https://github.com/29988122/Fate-Grand-Order_Lua/issues/182

Inside the issue is a fixed version

**Comment by GenosisRex** [comment]
Cheers, that fixed it
