### ISSUE TITLE
Jalter png

### ISSUE THREAD

**Issue by MrPotSticker** [29988122/Fate-Grand-Order_Lua#235]
Anyone got a png for jalter that works? Been trying for the past hour and it just skips pass jalter every time :(.

**Comment by forgehe** [comment]
![jalter1](https://user-images.githubusercontent.com/4041213/65822365-68a00500-e1f7-11e9-80d6-a4fb2cae9079.png)
![jalter4](https://user-images.githubusercontent.com/4041213/65822366-68a00500-e1f7-11e9-89d5-b374f32a3f9e.png)

Can you try these two images if they work?
