### ISSUE TITLE
The first skill used after chargesuit switch-in for the switched in character isnt detected.

### ISSUE THREAD

**Issue by GenosisRex** [29988122/Fate-Grand-Order_Lua#236]
This is probably due to lag. The screen shows the tap happening, but the skill isnt activated because there's a lag from character loading from being switched in. 

For example X11abc, a will not be detected. However if I do x11dabc, d will be detected.

Not sure why. Weird quirk.

**Comment by TryBane** [comment]
I have something that should solve this issue, but it hasn't been merged in with the base script yet. It it in #221 right now, waiting for review for it to be merged.
