### ISSUE TITLE
Can't execute the run.bat command

### ISSUE THREAD

**Issue by persicaria198** [29988122/Fate-Grand-Order_Lua#239]
I'm trying to install the daemon, but I keep getting "'This' is not recognized as an internal or external command, operable program or batch file." message. It's driving me crazy! For reference, this is the address of the folder:

This PC\Storywriter (Huawei)\Internal storage\Fate-Grand-Order_Lua-master\ama_daemon

I'm a complete noob when it comes to coding and programming, so I don't really get how any of this works. I just follow the manual on the site, but no matter where I put it on my phone, I keep getting the same message. I just really don't get it...

**Comment by TryBane** [comment]
You need to run the file on the computer while your phone is connected to the computer. It won't run while on your phone.

**Comment by persicaria198** [comment]
Problem is I did connect it to my PC. I got to the command prompt, but when I try run.bat, that message pops up.

**Comment by TryBane** [comment]
Well firstly, you need to turn USB debugging on on your phone. But I also need to make sure that you have Android 7 or lower.

**Comment by persicaria198** [comment]
I already turned on USB debugging but...ah...now I just noticed that I have Android 9...is this why it won't work?

**Comment by TryBane** [comment]
It isn't that it won't work, it's that it won't do anything even if it does. Because turning off USB Debugging will result in Daemon no longer working. So, for Android 8+ you need to use Media Projection, which does not require any programs or Daemon. It will work without needing to run any external programs so you don't need to worry about this.

**Comment by persicaria198** [comment]
I see... Thank you for helping!
