### ISSUE TITLE
是否可以再加一個換人禮裝的功能

### ISSUE THREAD

**Issue by gn01791992** [29988122/Fate-Grand-Order_Lua#24]
你好，剛剛在PTT上面看到這個程式

使用過後感覺還不錯，但若可以是否可以再外加裝一個換人禮裝的功能呢?

畢竟有換人禮裝隊伍靈活性較高

**Comment by 29988122** [comment]
https://github.com/29988122/Fate-Grand-Order_Lua/issues/21#issuecomment-357519404
另一位協力者打算要加了；Autoskill的功能是他寫的，所以等他來加比較適當，邏輯才不會亂掉

ETA未定，記得不要催人家喔~XD

**Comment by gn01791992** [comment]
這回信也太快，非常感謝QQ  要是能在贋作結束前實裝就好了呢...   不過就算沒趕上，拿這個來抽箱也很不錯，感謝大大無私分享

**Comment by 29988122** [comment]
剛好中午休息看到 lol

不過你如果跟我一樣，比較不怕碎石也不在意效率不佳的話，是可以剋職普攻硬跑啦(本人beta開始玩的所以champion pool比較深..)，四星五星顯學湊一湊幾乎不會滅團

嫌手機只有一隻或怕太燙你也可以用電腦的手機模擬器去run

我是可以保證檔案都無毒沒有後門啦，不過**非常複雜, 所以請自力更生**
1.請安裝memu 3.6.2 https://filehippo.com/zh/download_memu/comments/79416/
2.從這篇文章下載，匯入虛擬機image file https://www.reddit.com/r/grandorder/comments/6akkkq/emu_wars_episode_x_return_of_the_emu/
3.乖乖直接編輯虛擬機檔案把fgo acc file丟進去，這樣才能手機+電腦共用一個帳號
4. 參照這篇 這樣模擬器才能繞過檢測跑 https://www.reddit.com/r/grandorder/comments/6wi08i/episode_xiii_doom_or_be_doomed/dm89feh/
我是直接用文中提到的 Patchouli's patcher啦，反正看起來沒什麼backdoor

**Comment by gn01791992** [comment]
目前還沒準要要碎石  等手稿關開了可能就要碎了，沒蘋果也只能碎了...

模擬器方面最新版本夜神已經可以支援FGO了，不過我大概還是會繼續用手機玩，畢竟看上面設定有點麻煩，也怕引繼碼搞丟或亂掉

之前想自動化都是靠Mobizen投影上電腦，再由電腦按鍵精靈操控，有了這程式這步驟就可以省了，算是解放自己的電腦吧...畢竟按鍵精靈動作時滑鼠會被綁架，我又滿懶得寫後台操作，再加上這程式可以自動判斷關卡關數和出卡順序，相信在開發過程也是相當費時費力，真的很感謝作者及其他協力者。

**Comment by 29988122** [comment]
原來nox可以用，感謝情報提供 : p

其實這遊戲主要是弄得太農，我指的不是有強迫症一定要技10那種喔

讓我真正理智斷線的是CCC活動
在那之前我連每天耗體力都懶惰，這個script也還停留在六隻狂戰士亂打的階段

就是那個CCC刷到我精神錯亂..我就決定改善script了
天知道以後會不會還有這種強迫農夫才能看的劇情 0rz

**Comment by ryuga93** [comment]
加了，来找找bug吧=。=

**Comment by gn01791992** [comment]
不知道為啥...只要加入x的指令就會跳錯誤  要啟用這項功能是否還要修改檔案內其他部分?

**Comment by gn01791992** [comment]
抱歉  看來是我自己問題，從電腦下載移到手機的可能出現問題，改用手機直接下載程式碼後問題解決。

**Comment by gn01791992** [comment]
換人過後可能需要增加一些Delay時間  不然好像會太早點技能  造成錯亂
