### ISSUE TITLE
Installing Daemon

### ISSUE THREAD

**Issue by synthelite** [29988122/Fate-Grand-Order_Lua#242]
So I got a Razer phone; I've tried installing it the regular way (but it keeps saying there's no devices attached?) I've tried following the link on Minimal ADB and Fastboot and it sees my device as attached.. but the instructions don't say where to go from where, and I've tried looking it up. Do I try running the BAT file from the prompt? I'm so confused and I don't really know where to turn here.. I'm pretty sure my device can be seen given that again it can be seen through the aforementioned way.

**Comment by TryBane** [comment]
Android version 8+ don't need Daemon. Are you below version 8?

**Comment by synthelite** [comment]
It's Android 8.1. I'm not really tech savy with phones so I'm completely out of my element; I got the APK installed but it keeps asking me Daemon isn't found. In that case can I just go ahead with the script then by selecting that option? Is that what the 'Android 8.1 and up' whole section is for?

**Comment by TryBane** [comment]
Yes, you'll use Media Projection instead of Daemon for the script.

**Comment by synthelite** [comment]
Would you know if there's any notable bugs, is it all just sort of free territory? I've tried looking in the past issues (closed/open) and beyond usual bug reports didn't really find people mentioning their specific OS versions.

**Comment by TryBane** [comment]
Not specifically. Most people that have an issue with the script due to their device version is related to whether they need Daemon or not.
