### ISSUE TITLE
Recent Update now made Skill cool down more dangerous 

### ISSUE THREAD

**Issue by Rajvir8** [29988122/Fate-Grand-Order_Lua#247]
To clarify what I mean, before this recent update you could still plan for skill cool downs normally.

If it hit a skill that was still on cool down, it wouldn't be able to use any other skills that turn but that's it. It would then proceed to use any NP's for that turn and start the next one normally.

There wasn't a strong negative incentive on being optimistic, at worst you lost some auto time. 

Unfortunately now if it hits a skill cool down it doesn't click battle twice to get out of the skill cool down and start fighting, instead it goes straight to the next turn in the skill list which can mean a plan completely falls apart the very moment you hit a skill cool down for the first time. 

This means you have to be much more pestimistc as you may kill wave 2 faster and you can't as easily risk using them in Wave 3 until your a 100% sure everything is sade.

Is there any way I could fix this currently?

It used to be fine after all. My best guess on why is that it used to click battle twice. 

Adding to this I noticed it actually got stuck on a turn randomly, as it wouldn't hit battle and just stayed on the screen.  Not sure how this happened but my best guess is that it clicking the Battle Screen is the problem compared to how it used to work.

To show this yourself, you can make a test,
Use skill I first and then set auto to do this

"i654,g"

What should happen is it clicks the third skill finds it on Cooldown and then breaks for the turn, and that turn only

But instead it assumes everything succeeded and goes on to press the NP button and attack face cards after not being able to detect them.

Worse yet it will not realize the turn completely failed and press g after that, which means your entire turn can be fucked the moment you hit a cooldown rather than just a single turn.

**Comment by TryBane** [comment]
That was how it worked before if something went wrong. But I just thought of a method to make this a little more flexible and will see about implementing it.

**Comment by Rajvir8** [comment]
Really strange, before it always corrected itself by the end of the turn.

Well if that's the ways it's supposed to work nothing to do about it then.

I'll look forward to the future method you create

**Comment by TryBane** [comment]
Well, I wouldn't say "supposed to" but it is expected currently anyways.
