### ISSUE TITLE
Speed.

### ISSUE THREAD

**Issue by saiyansoul** [29988122/Fate-Grand-Order_Lua#25]
Can we hasten the clicking speed?

sometimes,it is too slow(just for eficiency)

i've tried using the Beta fast touch from ankulua itself,turns out it miss the 1st np and faster than the loading time.How can I seek a way for the fast touch?

**Comment by ryuga93** [comment]
You can reduce the number in wait() inside regular.lua

We allow longer waiting due to processor not able to cope with it (running the game plus ankulua.

**Comment by saiyansoul** [comment]
So,we can speed up the choosing card part?And parts between using skill and attack?

**Comment by ryuga93** [comment]
Those are heavy algorithm parts, there is not much wait() functions, the speed at that part totally depends on your phone's processor

**Comment by saiyansoul** [comment]
Damn...

Intel based phone sucks then..
Thanks.
