### ISSUE TITLE
Issue with Auto Lottery

### ISSUE THREAD

**Issue by muvluvalt** [29988122/Fate-Grand-Order_Lua#250]
The script stops for a while in the midst of rolling, and for some reason, continues clicking for a while at the end even after the box has been cleared. Is this intentional, or is this a bug?

[https://youtu.be/YqFuSJecjKc](url)

**Comment by forgehe** [comment]
Pretty sure it's intentional. 
If you leave it running. It'll eventually stop clicking that location, and then it should reset the box.

**Comment by TryBane** [comment]
It is indeed intentional. I set it up so that the clicking lasts a little longer than it takes to clear the box due to some devices being slower. You can increase/decrease the number of clicks by going into the file and changing it on line 35.
