### ISSUE TITLE
Auto Gift Exchange offests incorrect?

### ISSUE THREAD

**Issue by Life-Swordsman** [29988122/Fate-Grand-Order_Lua#253]
Are all of the offsets for the Auto Lottery/Auto Gift Exchange script off? When I start the script, it start clicking in the upper left corner, near Nero's head. I tried messing with the offsets in the consts area, and I managed to get it to start clicking on the correct button for spinning the box, but it still doesn't do things like auto reset the boxes.

**Comment by TryBane** [comment]
If you haven't updated in a while then they would indeed be off. I have already fixed this issue about a week and a half ago or more.
