### ISSUE TITLE
Behavior

### ISSUE THREAD

**Issue by saiyansoul** [29988122/Fate-Grand-Order_Lua#26]
Is it a normal behavior for the script to stop at certain point?

Mine stopped when I left it running when i was sleeping.

**Comment by 29988122** [comment]
Hard to say, could be delay issue

I was mainly using emulator, so the speed was quite ideal - therefore hard to replicate the issue.
Most of the time it was connection issue, sometimes it took longer than normal and then stuck.

You may as well check autoskill, servant died could mess up your skillz(e.g., self casting skill became targeted skill).

**Comment by saiyansoul** [comment]
Usually it stuck after choosing support screen.I couldn't be skill problem,right?

Anyway,I'm on phone,maybe i need to watch over it so I can know what is the cause.

**Comment by 29988122** [comment]
Is it JP server or non-jp server?

Is the stuck consistent(always stuck) or only stuck after refilling stamina?

**Comment by saiyansoul** [comment]
I think after refilling stamina.Because,When i checked it,the stamina exceed the limit

**Comment by 29988122** [comment]
Try using the latest version?

And, which server are you in?
Jp server was like Refill->click support servant->start quest.
But in the other server it was like Refill->click stage->click support servant->start quest

As you can see, there's one extra click.
Tell me your server/behavior so I can check if my fix on this was buggy or not.

**Comment by saiyansoul** [comment]
I'm on JP brother.

I've downloaded the latest master version and turns out the regular.lua can't be edited.
I need to edit it so it can choose target.
So i replace the Regular.lua with the one i use before and replacing the Image_JP. 

For reg jpn.lua ,I'm using  the latest master versionn

**Comment by ryuga93** [comment]
Can't be edited? Is it write access prohibition error?

Btw @29988122 on EN the click() after refilling does not work. Haven't found the cause, I ended up replacing it with menu()

**Comment by saiyansoul** [comment]
I can edit the script,but ankulua won't run and show an error message.

So,as Ryuga told me,I used the old ones

**Comment by ryuga93** [comment]
There are syntax errors in your script. When you run it in ankulua, it will state the error with the line number in brackets. That's the location you'll need to double check

The latest master version addresses the refilling issue for different servers, refer https://github.com/29988122/Fate-Grand-Order_Lua/issues/21#issuecomment-357259023

Plus the order change skill support.

**Comment by saiyansoul** [comment]
Wow!

I've downloaded the latest version.It works fine now on JP server.
I'll try in Na later, Thanks

**Comment by ryuga93** [comment]
`if NotJPserverForStaminaRefillExtraClick == nil then
			--Temp solution, https://github.com/29988122/Fate-Grand-Order_Lua/issues/21#issuecomment-357257089 
			click(Location(1900,400))
			wait(1.5)`

change the wait to bigger value, maybe 3

**Comment by saiyansoul** [comment]
I'm using the latest one rn.Na working fine. Haven't tested it on JP tho
