### ISSUE TITLE
Does this script still work with JP's new skip feature?

### ISSUE THREAD

**Issue by BlitzDungeoneer** [29988122/Fate-Grand-Order_Lua#264]
Title. Does it work with the feature to just auto-redo nodes without going back to node selection?

**Comment by mjloyola** [comment]
Does not appear to work when I tried it. Really suck because this basically prevents farming on JP now. Anyone have a fix or workaround?

**Comment by mjloyola** [comment]
> Does not appear to work when I tried it. Really suck because this basically prevents farming on JP now. Anyone have a fix or workaround?

Scratch that. It just takes a long time to do the continue selection.

**Comment by nghipham513** [comment]
> > Does not appear to work when I tried it. Really suck because this basically prevents farming on JP now. Anyone have a fix or workaround?
> 
> Scratch that. It just takes a long time to do the continue selection.

hmmm wat do you mean by long time? so far i've had to manually hit the "refarm" and select support again by hand, which is pretty bothersome.
