### ISSUE TITLE
I can't use FGO_JP_REGULAR.lua on Non-rooted Phone

### ISSUE THREAD

**Issue by AlfredPaguio** [29988122/Fate-Grand-Order_Lua#269]
![Screenshot_2019-09-26-16-59-16-231_com aniplex fategrandorder](https://user-images.githubusercontent.com/25319699/65675603-ab879e80-e078-11e9-9bef-763f453fc3d3.png)

**Comment by TryBane** [comment]
You have to use Daemon. Firstly, you are on Android 7 which doesn't support Accessibility mode. Follow the instructions on installing Daemon on your device.
