### ISSUE TITLE
AnkuLua

### ISSUE THREAD

**Issue by legendkay** [29988122/Fate-Grand-Order_Lua#27]
After installed AnkuLua so phone or emulated phone has been rooted i'm unable to open fate, the app crash istantly!
what i can do?

**Comment by saiyansoul** [comment]
Afaik,fate grand order can't be played on a rooted emu/phone

**Comment by legendkay** [comment]
How i use the script if the guide make me do programs that root the phone? O.o ankulua root it

https://play.google.com/store/apps/details?id=com.appautomatic.ankulua.trial On Android, install the latest version of sikuli framework here.

Download the latest release version of Fate-Grand-Order_Lua, extract it.

Copy the whole extracted folder into your phone.

On Android, enable developer options->usb debugging, connect your PC to android and execute run.bat inside Fate-Grand-Order_Lua \ama_daemon folder ON PC. After daemon has been installed, you can disable usb debugging and unplug. DAEMON NEEDS TO BE REINSTALLED UPON PHONE REBOOT.

If daemon installation was not successful / driver not properly installed, please install this: https://forum.xda-developers.com/showthread.php?t=2317790

Open ankulua to check if daemon is properly installed - and load the script inside your phone - you're done.

**Comment by legendkay** [comment]
how you use ankulua without root the device?

**Comment by saiyansoul** [comment]
You don't need a rooted phone to use ankulua,just install it from playstore then install daemon from pc

**Comment by 29988122** [comment]
@legendkay 
Yeah, @saiyansoul is right.

If you still can't run it, try to describe your steps, and I'll do my best to help you.
