### ISSUE TITLE
ankulua stopping

### ISSUE THREAD

**Issue by Kyonyuu** [29988122/Fate-Grand-Order_Lua#270]
![71171194_922188671490319_2332529818572161024_n](https://user-images.githubusercontent.com/55859937/65731134-dd116180-e09a-11e9-92ea-f4082a539dae.jpg)

im trying to use ankulua for sometime now, the bot can choose the quest but nothing more, just stop.

**Comment by w-san** [comment]
did you name the support selection correctly?
