### ISSUE TITLE
getting failed determine card type for all card

### ISSUE THREAD

**Issue by Ryan156** [29988122/Fate-Grand-Order_Lua#276]
Just thought this lua script was really helpful, then I try out autoskill and configured skill command for it, and it was working fine and dandy until 2nd turn starts as it won't use skills and waited for awhile only to see fail to determine card type, playing on fgo cn. 
Edit: Was using nox emulator with ankulua pro v8.3.0

**Comment by forgehe** [comment]
try using ankulua 8.5.0 or higher

**Comment by Ryan156** [comment]
Thanks, it worked after i tried ankulua 8.5.5.
