### ISSUE TITLE
AutoSupportSelection does not work

### ISSUE THREAD

**Issue by TuanAnh-Pham** [29988122/Fate-Grand-Order_Lua#278]
#Hi, I have just discovered your wonderful works and try to use it today.

I play FGO JP version. The scripts run just fine with auto attacke, skill and choose quest. The only issue is it could not choose support and start the battle. I tried to read others comments on this issue but haven't found any solution.
This is my setting for AutoSupportSelection:

Support_SelectionMode = "first"
Support_SwipesPerUpdate = 10
Support_MaxUpdates = 3
Support_FallbackTo = "manual"
Support_FriendsOnly = 3
Support_FriendNames = ""
Support_PreferredServants = "Any"
Support_PreferredCEs = "Any"

Could you please have a look ? Much appreciated

**Comment by w-san** [comment]
try removing the 3 off support friends only.

**Comment by Hylas246** [comment]
> try removing the 3 or change it to a 0 on support friends only.

Thanks for the advice but the issue still persists. I tried reinstalling AnKulua, re-load totally unedited scripts but still haven't seen it work ([video](https://drive.google.com/file/d/1-htHygzxwUE51yrksQuLr9nebe1p2Zzf/view?usp=sharing)) The other function work fine though so I guess I have to put in some work to choose the support. 

If any one ask, I use Xiaomi Redmi 6 Pro with MiUI 10.

**Comment by metapea** [comment]
Yeah the same thing is happening to me in nox with the video, but it's not working at all with rest of the functions.

**Comment by vit2657** [comment]
There is kinda an issue on JP with finding a region for friend selection automatically. [This image](https://github.com/29988122/Fate-Grand-Order_Lua/blob/master/image_SUPPORT/support_region_tool.png) used to determine it, however most of the times people have command codes on their cards, which makes it script fail to find this exact image.

**Comment by reconman** [comment]
Possibly already fixed in the master branch

**Comment by reconman** [comment]
Closing because there's no response.
