### ISSUE TITLE
Runtime error when starting regular.lua & JP_regular.lua

### ISSUE THREAD

**Issue by chynanumbawan** [29988122/Fate-Grand-Order_Lua#279]
![SmartSelect_20191030-133702_AnkuLua Pro2](https://user-images.githubusercontent.com/57195580/67892578-9cce5480-fb1a-11e9-8882-804e01add9d0.jpg)
![SmartSelect_20191030-133759_AnkuLua Pro2](https://user-images.githubusercontent.com/57195580/67892581-9d66eb00-fb1a-11e9-94d1-34527c9dcb12.jpg)

I installed Ankulua and copied the scripts. After I successfully install demon when I'm trying to run regular.lua & FGO_JP_REGULAR.lua. A runtime error pops up. _auto_friendgacha.lua works at intended however. I tried to re-copy all the files and checked file path but its still not working. If anyone can help me troubleshoot this, it will be greatly appriciated.

Thank you for sharing this code after all, and thank you for your time.

**Comment by forgehe** [comment]
Try using Ankulua 8.5.0 or higher

**Comment by chynanumbawan** [comment]
@forgehe Thank you for your respond. I tried to update Ankulua to the newest patch. However the same error messages are still coming up.

I did try to install daemon more thank once. Could that be casuing the issue?

Thank you for your time and help.

**Comment by forgehe** [comment]
What phone/emulator are you using? What Android version?
Installing the daemon more than once shouldn't be an issue, but it doesn't hurt to restart your phone and then try installing the daemon again.

**Comment by metapea** [comment]
> ![SmartSelect_20191030-133702_AnkuLua Pro2](https://user-images.githubusercontent.com/57195580/67892578-9cce5480-fb1a-11e9-8882-804e01add9d0.jpg)
> ![SmartSelect_20191030-133759_AnkuLua Pro2](https://user-images.githubusercontent.com/57195580/67892581-9d66eb00-fb1a-11e9-94d1-34527c9dcb12.jpg)
> 
> I installed Ankulua and copied the scripts. After I successfully install demon when I'm trying to run regular.lua & FGO_JP_REGULAR.lua. A runtime error pops up. _auto_friendgacha.lua works at intended however. I tried to re-copy all the files and checked file path but its still not working. If anyone can help me troubleshoot this, it will be greatly appriciated.
> 
> Thank you for sharing this code after all, and thank you for your time.

Yeah, i got the same thing when i tried regular.lua

**Comment by forgehe** [comment]
Hi @metapea, go to http://ankulua.boards.net/thread/1395/ankulua-trial-apk-download and download the newest version of Ankulua.

This script does not support Ankulua 7.2.0
The lowest version of Ankulua that this script supports is 8.5.0.
Meaning the cracked Ankulua Pro versions floating around will not work with this script.

Secondly, you would want to run the script using the FGO_XX_REGULAR.lua file, instead of trying to run regular.lua

**Comment by metapea** [comment]
> Hi @metapea, go to http://ankulua.boards.net/thread/1395/ankulua-trial-apk-download and download the newest version of Ankulua.
> 
> This script does not support Ankulua 7.2.0
> The lowest version of Ankulua that this script supports is 8.5.0.
> Meaning the cracked Ankulua Pro versions floating around will not work with this script.
> 
> Secondly, you would want to run the script using the FGO_XX_REGULAR.lua file, instead of trying to run regular.lua
It's not even working in 8.5.6 for me in regular.lua, and i've also used FGO_XX_REGULAR.lua, that isn't working as well (#277). I'm just saying i've tested regular.lua before and got the same thing

**Comment by forgehe** [comment]
Can you send a screenshot of your Nox Settings, and the Ankulua Settings?
For Example: https://imgur.com/a/u8eK5sA

**Comment by metapea** [comment]
Thank you, I've found the problem: https://i.imgur.com/adYUChr.png
You need to have Screenshot by: daemon in ankulua's setting and not media projection.
There a setting in android 7, where you can use ankulua without daemon, do not use this. It's will only show Screenshot by: media projection, with daemon gone.

**Comment by forgehe** [comment]
Good to hear

**Comment by chynanumbawan** [comment]
@forgehe I figured out my issue as well but I'm too ashamed of it to share.  I miss spelled preferred lol
