### ISSUE TITLE
Added Halloween 2019 CEs

### ISSUE THREAD

**Issue by forgehe** [29988122/Fate-Grand-Order_Lua#280]
I screenshotted and tested the Halloween 2019 CEs for you guys to add into the main repository.
https://github.com/forgehe/Fate-Grand-Order_Lua/commit/f5cd0ad74ac72890371b77da1cc133cca95fe353
Can't figure out how to make a pull request without adding all my other junk commits I made.

**Comment by reconman** [comment]
Fixed with https://github.com/29988122/Fate-Grand-Order_Lua/commit/9fa064dd0144b6313cd0a5262ecb1eeb6a6bcb05
