### ISSUE TITLE
Freezing issue on Bluestacks

### ISSUE THREAD

**Issue by MrTroika** [29988122/Fate-Grand-Order_Lua#281]
In the latest version of bluestacks, attempting to use any script causes FGO to immediately lock up as soon as you hit the play button and require a hard reset of the emulator.

**Comment by forgehe** [comment]
Seems like an issue between Ankulua and Bluestacks. 
You can either wait until the Ankulua devs fix this issue, or try using another emulator.

Looks like other people are also having that problem >
http://ankulua.boards.net/thread/1568/all-screen-freezes-starting-script

**Comment by MrTroika** [comment]
I figured out how to fix it-- turning on the Advanced Graphics Engine in bluestacks options makes everything work fine. ID-10T error~
