### ISSUE TITLE
Getting the Script to run on my notched phone

### ISSUE THREAD

**Issue by Neshura87** [29988122/Fate-Grand-Order_Lua#282]
Would it be possible for me to basically hard code the game area so that the script would at least work in one orientation of my phone (notch always on the left for example) and if it is possible, how would I do that?

Edit: Running Android 9, Phone is a Samsung Galaxy A50

**Comment by reconman** [comment]
I have an OnePlus 6 with a notch, and on my phone everything works correctly in all orientations.

Here is another user with problems on the Galaxy A50, maybe my comment at the bottom helps: #289

**Comment by Neshura87** [comment]
Seems to be working, thank you so much I've been wanting to use this script for ages but couldn't because of the notch
