### ISSUE TITLE
Automation hindrance due to continuous sorties

### ISSUE THREAD

**Issue by graphite1** [29988122/Fate-Grand-Order_Lua#284]
Hello. I am playing FGO Japan version.
Due to the continuous sorties implemented in recent updates, it is no longer possible to continue to circulate free quests automatically.
How can I solve this problem?

**Comment by vit2657** [comment]
You mean popup about doing same quest one more time at the end of the free quest without going back to menu? If yes, then it works fine for me.

**Comment by graphite1** [comment]
yes. and sorry.
It seems my mistake.
The script worked.
However, after that, when an error (Stuck?) Occurred, even if you tap the play icon, it stopped working.

**Comment by vit2657** [comment]
Can you screenshot the error you are getting?

**Comment by graphite1** [comment]
this is . sometimes i see

2019年11月18日(月) 15:43 vit2657 <notifications@github.com>:

**Comment by graphite1** [comment]
![Screenshot_20191118-163825](https://user-images.githubusercontent.com/57855383/69136230-d54fc580-0afd-11ea-9cd0-2ff674303517.png)

**Comment by reconman** [comment]
The last screenshot seems like an Ankulua bug.

**Comment by reconman** [comment]
See https://github.com/29988122/Fate-Grand-Order_Lua/issues/317#issuecomment-585053679
