### ISSUE TITLE
I cant for the life of me figure out why i keep getting this error

### ISSUE THREAD

**Issue by Technosource99** [29988122/Fate-Grand-Order_Lua#286]
I cant figure out why the luas dont show up, i tried moving them in their own folder, out side a folder i cant figure it out
![Capture+_2019-11-17-05-08-57](https://user-images.githubusercontent.com/57864607/69007904-f5fafe00-08f8-11ea-90ae-22d128455041.png)

**Comment by vit2657** [comment]
You can use them from any folder actually. Have you tried "Select script" button that is the second top right?

**Comment by Technosource99** [comment]
never mind i have the biggest dumb
