### ISSUE TITLE
Stuck in Support Selection Screen

### ISSUE THREAD

**Issue by ReikutsuNeko** [29988122/Fate-Grand-Order_Lua#289]
I'm using FGO_EN_REGULAR.lua on non root phone (Samsung galaxy A50) and it always stuck on support selection screen. I already tried to set the FallbackTo to manual (select the support manually and start the battle manually) and it does nothing when entering the battle

```
--AutoSupportSelection
Support_SelectionMode = "preferred"
Support_SwipesPerUpdate = 10
Support_MaxUpdates = 3
Support_FallbackTo = "first"
Support_FriendsOnly = 0
Support_FriendNames = ""
Support_PreferredServants = ""
Support_PreferredCEs = "chaldea_lunchtime.png"
```

**Comment by hayate1412** [comment]
Got the same issue. Please help!!!

**Comment by cboldes** [comment]
Interesting enough I've been running into the same issue. I have the Samsung Galaxy S10+. Initially it'll pick the event, but once it hits the support screen nothing happens. I've attempted to fall back and usual the manual support selection but nothing happens once I go into battle. Honestly we just need a Dev to help us out.

**Comment by cboldes** [comment]
@potchy would you be able to help out?

**Comment by reconman** [comment]
Can you try this? https://github.com/29988122/Fate-Grand-Order_Lua/issues/310#issuecomment-586916790

**Comment by hayate1412** [comment]
> Can you try this? [#310 (comment)](https://github.com/29988122/Fate-Grand-Order_Lua/issues/310#issuecomment-586916790)

Holysh*****t. I got it fixed. 
Thanks a lot for the advice.

**Comment by ReikutsuNeko** [comment]
I can confirm this is working until Start Battle (and swiping thru support selection screen until it found a desired CE). When entering the battle, script won't choose skills that I already put in Skill_Command. My Skill_Command was:

`Autoskill_List =
{
	{
		Name = "QP",
		Skill_Command = "adf36,#,4,#,i6",
		Support_SelectionMode = "preferred",
		Support_PreferredServants = "",
		Support_PreferredCEs = "*mona_lisa.png"
	},
	{
		Name = "Exp Ishtar",
		Skill_Command = "adf36,#,ig4,#,h6",
		Support_SelectionMode = "preferred",
		Support_PreferredServants = "",
		Support_PreferredCEs = "*chaldea_lunchtime.png"
	},
	{
		Name = "Exp Karna",
		Skill_Command = "adf36,#,4,#,hi6",
		Support_SelectionMode = "preferred",
		Support_PreferredServants = "",
		Support_PreferredCEs = "*chaldea_lunchtime.png"
	}
}
`

**Comment by reconman** [comment]
@ReikutsuNeko What exactly happens during battle? Does it attack automatically, ignoring your Skill_Commands, or does it not do anything? Can you provide a screenshot of the battle?

**Comment by ReikutsuNeko** [comment]
@reconman it doesn't do anything at all. I waiting for it like 10 mins and it does nothing :(
Here's the screenshot:

![image](https://user-images.githubusercontent.com/33795863/78885706-44b35b00-7a87-11ea-8f57-7ebb87cc734f.png)

**Comment by reconman** [comment]
@ReikutsuNeko Can you please test add this after getGameArea():
```
	gameWithBorders:highlight()
	wait(10)
	gameWithBorders:highlight()
```

Please take a screenshot and post it here again. I think that Ankulua doesn't treat your tiny navigation bar correctly. My assumption is correct if you don't see a yellow line between the blue border and the navigation bar.

If I'm correct and Ankulua cannot handle your navigation bar, you can still change the game area manually using setW. I've already picked the correct value based on your screenshot width.
```
	local gameWithBorders = getGameArea()
	gameWithBorders:setW(2300)
	local scaleMethod = DecideScaleMethod(scriptWidth, scriptHeight, gameWithBorders:getW(), gameWithBorders:getH())
```

But I would then also report the issue to the Ankulua team, so they can fix their non-immersive code.

**Comment by ReikutsuNeko** [comment]
Thanks for your reply @reconman 
After I add `gameWithBorders:highlight()`, it only show red border across my screen and still working until the battle started. But, when I add `gameWithBorders:setW(2300)`, It does nothing, even it can't choose the quest

**Comment by reconman** [comment]
@ReikutsuNeko I think we need to do a little personal debug session together. Do you have a Discord account?

**Comment by ReikutsuNeko** [comment]
Uh sure. @reconman _vkrul#1943

**Comment by reconman** [comment]
This particular issue was solved by setting autoGameArea(false), because there was a notch on the left. (not visible in the screenshot)
