### ISSUE TITLE
[JP xmas event- stuck on servant screen]

### ISSUE THREAD

**Issue by nghipham513** [29988122/Fate-Grand-Order_Lua#291]
I put in the specifications for skadi and the xmas event CE in the JP.lua file, but the program will keep scrolling down and not hit the skadi. pretty weird as i followed the format during gilfest of this year and didn't run into any issues with that.

**Comment by nghipham513** [comment]
JK i found out the issue
turns out my screenshot for the CE was a different name than the one in the .lua file

**Comment by aqer** [comment]
You can directly use filter in game to filter out desired event CE in JP server, no need to take screenshot of CE by yourself.
