### ISSUE TITLE
support.lua:38: Attempt to index local 'str' (a nil value)

### ISSUE THREAD

**Issue by RoyJames** [29988122/Fate-Grand-Order_Lua#294]
I've been using this repo for a few times. Now I'm playing JP server's Christmas event. The issue was when I start the script, either from the quest selection screen or the first battle screen, this error message immediately prompts:

![image](https://user-images.githubusercontent.com/8073842/70383820-51da0500-1942-11ea-8107-4e879fdf1e41.png)

![image](https://user-images.githubusercontent.com/8073842/70383817-41298f00-1942-11ea-90c4-e8b015fbf752.png)

I confirmed my repo is up-to-date. It looks like some initialization error in parsing the friend list? But I wonder why it won't work when I'm already in the battle. I'm running on a OnePlus 5 phone as I used to with AnkuLua 8.5.0-pro2. Can you suggest any possible fix? Thanks a lot.

**Comment by RoyJames** [comment]
I just tried my previous scripts (for QP and tanebi) that worked fine in the past but now with this error too.

**Comment by RoyJames** [comment]
OK now I found a fix. I just commented out the following lines in support.lua
```
	-- friend names
	-- for _, friend in ipairs(split(Support_FriendNames)) do
	-- 	friend = stringUtils.Trim(friend)
	-- 	table.insert(FriendNameArray, friend)
	-- end
```
I looked at the file history and found this is a new feature of selecting a fixed friend, which could be very useful. But this initialization seems to have some trouble getting the friend list (are there extra steps to take to get the list?).

**Comment by aqer** [comment]
Maybe there are some special characters in your FGO_JP_REGULAR.lua that cause this problem.
Your can try original FGO_JP_REGULAR.lua to check this problem. 
I haven't encounter this problem in JP Christmas event.

**Comment by reconman** [comment]
It's probably too late but the error indicates that you probably don't have this line in your script:
```
Support_FriendNames = ""
```
My linked PR fixes the exceptions if you forget that line
