### ISSUE TITLE
Doesn't seem to run

### ISSUE THREAD

**Issue by Enfinit** [29988122/Fate-Grand-Order_Lua#295]
I can't seem to get this to run correctly on my note 10+. The auto friend gacha seems to work perfectly fine but I can't run the EN script for some reason. At most when I run it, it can click the quest and even refill with apples but doesn't do select the preferred support (or any support for that matter) or run auto skill. I don't get any errors either. I've been using Media Projection/Touch by Accessibility since for whatever reason I lose daemon when disabling usb debugging.

**Comment by reconman** [comment]
Was also reported in #333
