### ISSUE TITLE
Failed to get card type stopping script, nox player

### ISSUE THREAD

**Issue by Timinterrante** [29988122/Fate-Grand-Order_Lua#298]
Using the EN_regular to farm new christmas event and starting from the menu, the script will run perfectly during the support selection, and select the preferred CE, but once battle one starts the script will perform the auto skill for that stage, but at the card select screen will pop-up 3-4 failed to get card type errors 
![FailedCardType](https://user-images.githubusercontent.com/58995211/71033273-a9176c80-20dc-11ea-8352-d227a504ef92.png)
After this the script freezes, and doesn't click anything will get stuck on battle 2. It will stay soft locked like this until I abort the script.

If I start the script at battle 1, the script will successfully detect the card types on the first stage, but will fail at card selection on the second stage after performing the stage 2 autoskills. 
![FailedCardTypeStage2](https://user-images.githubusercontent.com/58995211/71034387-ef6dcb00-20de-11ea-9db4-cbe292ea2ab6.png)

**Comment by Shijuuichi** [comment]
It seems that it doesn't recognize it isn't in the battle screen anymore. Forcing it through the battles while running the script also results in a freeze on the mission select screen, and it doesn't recognize the support select screen anymore. 

Tested this by adding a bunch of toast calls in a few functions, but haven't found why it doesn't recognize anything anymore.

**Comment by Shijuuichi** [comment]
issue appears on ankulua pro 2, does not appear on ankulua 8.5

**Comment by Timinterrante** [comment]
I updated to the latest ankulua and the script works now, thanks.
