### ISSUE TITLE
EN Server Christmas 2019 CEs

### ISSUE THREAD

**Issue by forgehe** [29988122/Fate-Grand-Order_Lua#299]
https://imgur.com/a/7Tvns0d
Also 3rd + 4th Ascension Eresh and 4th ascension Altera

**Comment by colourspectrum** [comment]
Thanks a bunch man. I came to check issues to look for merry sheep png, as mine wasn't working at all.

**Comment by mingchungtsai** [comment]
I noticed that there are a few of support/CE contributions lying around in disparate issues. Do they get committed into the main branch, or do they stay forever in these individual issues? Would be cool if they can committed so we can just pull each time :) ...

**Comment by forgehe** [comment]
We just have to wait until the contributors add the support CEs to the repo. We usually just post an issue with CEs that we screenshotted if the people maintaining the repo are inactive during the event.

**Comment by reconman** [comment]
@forgehe Even though the event is already over, could you please add the images via a Pull Request? You will need to create a fork of the project, add the images and then create a Pull Request to transfer the changes to this project.
