### ISSUE TITLE
[Feature Request] Auto use apples / stones to refill stamina] 關於台版的部份

### ISSUE THREAD

**Issue by w31012** [29988122/Fate-Grand-Order_Lua#3]
可以請大大幫忙寫一個台版自動吃蘋果補體的編程嗎？

**Comment by 29988122** [comment]
預訂會加入所有版本~

原先不加入的原因是因為這個script一來效率慢(不會chain)，二來有時候網路連線障礙跑狗跑了20秒之類的就會出問題，所以常常需要人顧，這是預設的使用情境

乾脆就不寫吃果了


要加一個吃果routine可以，我另寫一個function，然後想要自動吃果/吃幾顆就請玩家自己改*.lua裡面對應的數字，我會寫說明檔

要一點時間就是了

**Comment by 29988122** [comment]
請看release區的1.4.0版本

已經支援了，刷一下，有bug請提出~
