### ISSUE TITLE
Apple refill touch confirmation 1/3 of second before. 

### ISSUE THREAD

**Issue by MerryNight** [29988122/Fate-Grand-Order_Lua#30]
^This, what I see is:
1.Click the quest.
2.Click the apple.
3.Click the Confirm button 1/3 of second before, and get stuck in the confirmation windows.
4.???? Script trying to click the quest forever.
I play the EN script.

**Comment by ryuga93** [comment]
I added a little waiting, if that's isn't enough you can change to bigger value.

**Comment by MerryNight** [comment]
else
            click(AppleClick)
	    wait(1.5)
            click(Location(1650,1120))
            stoneused = stoneused + 1
        end

I try to add this but ankulua give me a runtime error: [https://prnt.sc/i4ldsm](url)

**Comment by ryuga93** [comment]
you have a type of "流" at line 49

**Comment by MerryNight** [comment]
No, somehow the script capture this of regular.lua firsts lines--[[
このスクリプトは人の動きを真似してるだけなので、サーバーには余計な負担を掛からないはず。
私の国では仕事時間は異常に長いので、もう**満**足プレイする時間すらできない。休日を使ってシナリオを読むことがもう精一杯…
お願いします。このプログラムを禁止しないでください。
]]

**Comment by ryuga93** [comment]
Oops, didn't saw the first line...

How about trying the new master? I have updated to include wait() before click(AppleClick).

**Comment by MerryNight** [comment]
Thanks, I did it and now the script was working fine. Close this thread.
