### ISSUE TITLE
auto gift exchange does not recognize lottery.png

### ISSUE THREAD

**Issue by Shijuuichi** [29988122/Fate-Grand-Order_Lua#303]
![Screenshot_20191220-104547](https://user-images.githubusercontent.com/54473180/71246303-af912880-2316-11ea-8fea-f9213776dda5.jpg)

tested with ankulua 8.6.0-pro2. 

added toast in file _auto_gift_exchange.lua to see if the if statement would result in true or false:

toast("FinishedLotteryBoxRegion:exists(FinishedLotteryBoxPattern) " .. (FinishedLotteryBoxRegion:exists(FinishedLotteryBoxPattern) and 'true' or 'false'))

problem is that it does not recognize the lottery can't continue and just starts tapping away.

**Comment by saberkevin** [comment]
looks like we need to change FinishedLotteryBoxRegion position, but i dont know how to debug the region for the exact position

**Comment by TheIanator** [comment]
Using FinishedLotteryBoxRegion:highlight(3) it looks like its looking in the right place but not for the right size, doubled the last two parameters of FinishedLotteryBoxRegion and it seems to be working for me now.

**Comment by saberkevin** [comment]
wow @TheIanator it works! thank you very much :D

try changing the region value of FinishedLotteryBoxRegion into this guys
|
v
local FinishedLotteryBoxRegion = Region(520, 840, 140, 200)

**Comment by reconman** [comment]
Fixed by #330
