### ISSUE TITLE
difficult to change target for christmas event (saber quest)

### ISSUE THREAD

**Issue by fategrandfans** [29988122/Fate-Grand-Order_Lua#308]
I have some issues about my script for fate grand order, specifically i can't change target among enemies.
specifically:
abc4,#,**t3**acg1hi4x31,#,t1g3d6"
1- turn
Arash charge np and shoot
2-turn
**change target**
archuria enter in battlefield and use the first and the last skil
waver (support) cast all skill on archuria
change waver support to ishtar
3-turn
change target to **saber alter**
merlin use skill (specifically on ishtar)
shoot NP

idk if are correct, thank for your help anyways

**Comment by reconman** [comment]
Issue is too old and not reproducable anymore, closing it.
