### ISSUE TITLE
Unable to battle

### ISSUE THREAD

**Issue by ethelion99212** [29988122/Fate-Grand-Order_Lua#31]
Hi, 
When I run the script in the battle screen, no button is being clicked, but i can see "No priority target selected" repeatedly shows up in the screen, the screen just stay like that.

I do suspect it might be screen resolution issue.
My phone screen resolution is 1080 x 1920 pixels, 16:9 ratio.

Possible to give some advise on how to solve this?

thank you

**Comment by 29988122** [comment]
Is your phone brand MI or oppo? or even Android 8.0? User reported that certain version of OSes cannot run due to safety measures.

For now, you can enter Ankulua->settings, and try every option under "touch by" to see if any of it works.

**Comment by ethelion99212** [comment]
Thanks for the reply

I am using Redmi note 4 phone with android 7.0

I will follow your advise.

Thanks.
