### ISSUE TITLE
FGO_EN_Regular Only seems to recognize the results page.

### ISSUE THREAD

**Issue by Sandman2112** [29988122/Fate-Grand-Order_Lua#310]
I've been tinkering with the code for a couple of days now, at first it was able to select the Ember Gathering Quest I wanted to automate, but now it only seems to work with the Results Screen after the node has already been completed. I've tried starting it on the Menu, Battle Screen, The Support Select, and the Results screen, and all it seems to understand is how to get me through the results pages. It does nothing for the actual game play, support select, or node selection. Nothing happens.

I tried using the script without modifying it - Nothing worked.
I tried using a copy of a friends setup(That worked on their device) - Nothing worked.

Attached is the setup that I tried last. I'm using a Galaxy 10e.  Android 9. 

[FGO_EN_REGULAR.txt](https://github.com/29988122/Fate-Grand-Order_Lua/files/4008427/FGO_EN_REGULAR.txt)

--------------------------------------------------------------------------------------------------------
Update: 1/5/2020

Script will now select the quest. It no longer does anything on the results page. It still does nothing during the actual farming.  Friend Gacha auto clicker is slightly off, but it still works. 

I'm so tired.

**Comment by Tamonten94** [comment]
Same problem here. i use Galaxy s10e too.
Script works on JP perfectly but for NA it only recognize the results page.

**Comment by Sandman2112** [comment]
That's interesting. I'd assume that they both use the same stuff from the modules folder, and both look pretty much the same when I read them, y'know aside from the comments in one being in Japanese. 

If you're playing both JP and NA, does that mean you're using an android emulator for one of the accounts?

**Comment by Tamonten94** [comment]
Nope, i've never used an emulator

**Comment by Sandman2112** [comment]
Ok. Do you have both versions of the game on the same phone?

**Comment by Tamonten94** [comment]
Yes, Galaxy s10e Android 9. I hope someone fix FGO_EN_Regular soon

**Comment by Sandman2112** [comment]
I see. Sorry for the misunderstanding.

**Comment by TheRealPlagiariser** [comment]
Ankulua version?

**Comment by Sandman2112** [comment]
It's on 8.6.

**Comment by TheRealPlagiariser** [comment]
It might have to do with the Galaxy s10e stretching the game screen and causing image recognition to fail because of 2 possibilities:
1. The image stretched and can't be matched.
2. The location where the bot is searching the image is different.

Check if the phone has an option to play the game on regular size. I

Not sure about this one but it's worth a try if you want( no need to do it for everything, just do it for Attack button and buster/arts/quick) if it works then you do the rest:
What you have to try out is to replace locations and regions in  ..modules\game.lua as well as replacing the actual image for each of them. If you require coordinates and can't code to get it, use snapAndPlay on Ankulua and just click the targetted spots, it will create both an image + give you the exact region, ( x,y,h,w). Ignore last 2 coordinates for locations. Don't forget you also have to configure the image sizes to be of the same as

**Comment by Sandman2112** [comment]
I moved everything over to an old galaxy s7edge. Ankulua seems to miss skill icons and other prompts on the new screen, but otherwise seems to work. 

NOX Resolution is 720 x 1280 (16:9) - Works Fine. 
S7 Edge Resolution is 1440 x 2560 (16:9) - Works, but is imprecise. 
Pixel 2: 1920 × 1080 (16:9) - Works just fine. 
s10e: 2280 × 1080  (19x9) - Does not work, only idles. 

I think Plagiarizer's idea holds. Screen resolution does seem to have an effect. From what I can tell, anything that runs the game in 16:9 works, anything over that fucks with things in the Images_EN folder, which might explain why the friend gacha script still works. Maybe. I don't know. I didn't make this thing.

s10e has something in it's options called Full Screen Apps under Display. I can bring it down to 16:9, and I'll try it after I recover my account because I failed to bring it back to the original device figuring this out. 

Yes. I AM an idiot.

**Comment by cboldes** [comment]
I've attempted to use the full screen with my note 10+ and it didn't work. Only thing I got to work is results and selection of the quest. . I've come to a similar conclusion actually that the screen resolutions for the S10e and S10+ are different from other andriod devices.

I'm a little unsure what to modify. I thought about taking screenshots of my screen and modifying the Images_EN folder, but i wasn't sure what else needed to be modified.

I will say I've noticed on the JP side. That Ankulua seems to be off just slightly, but still works cause it can click what it needs to click.

**Comment by Sandman2112** [comment]
I've also thought about that, but I don't want to put in that much effort into something I'm not sure will work.

**Comment by cboldes** [comment]
I could do some testing. Essentially all the code works anyway. If it's just the assets it shouldn't be to hard to modify. The only thing that confuses me is the difference between JP/NA.

Look at the Images_EN folder and the JP folder the images are the same from what I can tell, but I  could pull them in and screenshot to do comparisons.

**Comment by cboldes** [comment]
Well did an image conversion essentially. I noticed some of the assets in the docs folder are currently different from what we see on NA. Aside from that the over all assets look similar the the Images_EN folder.

I must be glossing over something obvious

**Comment by cboldes** [comment]
@TheRealPlagiariser I may be messing up the snap and play what settings do you use? I click one targeted spot and it stops the script.

**Comment by Sandman2112** [comment]
Is there a way to contact the person who made the bot? I thought opening an issue would be a good way to get in contact, and we don't seem to be getting any closer to an answer.

**Comment by cboldes** [comment]
@Sandman2112 I'm unsure I'd say @ one of the devs that have helped out. There was someone in a previous post that said a Dev helped them out but I never got a response on who

**Comment by TheRealPlagiariser** [comment]
> @TheRealPlagiariser I may be messing up the snap and play what settings do you use? I click one targeted spot and it stops the script.

Snap and play default settings, on latest Ankulua 8.6.0 . 
Currently the error you are reporting for snapandplay has been found in previous versions of Ankulua and everything was solved on the latest one. Also this is not the place to report ankulua issues neither.

**Comment by cboldes** [comment]
@TheRealPlagiariser I didn't figure it was a Ankulua issue honestly. There have been other reports with other andriod devices similar to the S10 or S10+. Where the script is unable to pick a servant or pick cards when in battle. I question it cause the game works fine on JP so something seems to be off on the EN.

**Comment by TheRealPlagiariser** [comment]
@cboldes When I said it was an issue related to Ankulua, I was referring to your problem with snap and play which you stated above.

**Comment by cboldes** [comment]
@TheRealPlagiariser that is fair, so how do we resolve the issue with the Samsung devices? I am willing to provide any information from my device to help mitigate any issues for other users.

**Comment by potchy** [comment]
I'm not particularly interested in working in yet another resolution issue, but these may point you in the right direction:

#148
#154 
#155

Also this is the diagram for our scaling algorithm:
![](https://raw.githubusercontent.com/29988122/Fate-Grand-Order_Lua/master/docs/scaling.png)

**Comment by Enfinit** [comment]
Anyone been able to figure it out for the Note 10+?

**Comment by cboldes** [comment]
@Enfinit still trying to figure it out myself.

**Comment by inTone1337** [comment]
Changing `autoGameArea(true)` on line 46 of modules\scaling.lua to `autoGameArea(false)` and leaving the rest of the file as is fixed the script for me on my Galaxy S10e.

**Comment by reconman** [comment]
Does inTone1337's solution work for you guys?

**Comment by glassofmilk1** [comment]
It works for selecting the quest and in the battle, but it doesn't for selecting support. I can still see the script trying to scroll however.

**Comment by reconman** [comment]
@glassofmilk1 Try setting the value of similar to a lower value at https://github.com/29988122/Fate-Grand-Order_Lua/blob/master/modules/support.lua#L316

**Comment by reconman** [comment]
Also I proposed a new MLB image under #355, maybe that helps. At least it helped me because the script always skipped MLB Star of Altria.

**Comment by glassofmilk1** [comment]
Hi, sorry this is such a late response. But I was able to get it to partially work using https://github.com/29988122/Fate-Grand-Order_Lua/issues/333#issuecomment-585049286

The "first" option at least. 

I can see it trying to swipe and it doesn't actually recognize when there's a servant and CE and I put as preferred on my settings.

**Comment by reconman** [comment]
@glassofmilk1 Try running the script in fullscreen mode with `autoGameArea(false)`, that should fix general issues of missing buttons. You don't need to manipulate the notch area yourself.

And please use the latest version of the script as the support image detection region was slightly off in previous versions.

**Comment by glassofmilk1** [comment]
So I'm trying it with `autogamearea(false)` and it does this bizarre thing where it only works when I flip my screen upside down. Otherwise I could be waiting over five minutes and it'll do nothing.

**Comment by reconman** [comment]
Are you flipping it while the script runs or before running it?

**Comment by glassofmilk1** [comment]
While it runs. 

I did a bit more experimenting and "first" seems to work so long as I have the bottom of the phone on the left side. I do have to flip the phone if I'm using "preferred". Similarly, I can see it trying to scroll but not actually scroll while the bottom of the phone is on the left but if it's on the right, I don't see any inputs.

**Comment by reconman** [comment]
@glassofmilk1 Can you provide 2 screenshots, one for each orientation?

**Comment by glassofmilk1** [comment]
Is that with debug on?

**Comment by reconman** [comment]
You don't need to activate debugmode, no. But you could add `new Region(0, 0, 2560, 1440):highlight(10)` between line 60 and 61 of scaling.lua, which will show the game area used by FGOlua when you start the script.

And you used a fresh scaling.lua and only changed `autoGameArea`, right?

**Comment by glassofmilk1** [comment]
<img width="472" alt="Annotation 2020-04-20 095417" src="https://user-images.githubusercontent.com/55068302/79778048-ff93f200-82ec-11ea-9449-3fd45158e4df.png">

Is it supposed to be like this? Because when I do that it puts up this error:

![Screenshot_20200420-095149_Gallery](https://user-images.githubusercontent.com/55068302/79778111-19353980-82ed-11ea-91d4-0aaab5877dee.jpg)

**Comment by MathewSachin** [comment]
Remove the `,` at the end of the line.

**Comment by reconman** [comment]
And add a tab before `new Region`

![image](https://user-images.githubusercontent.com/12360257/79779637-f893d080-833a-11ea-93a2-fbe15bf690aa.png)

**Comment by glassofmilk1** [comment]
<img width="440" alt="Annotation 2020-04-20 102322" src="https://user-images.githubusercontent.com/55068302/79780701-2522fa80-82f1-11ea-9986-446e4464b4ad.png">

It looks like this and it's still throwing up the same error

**Comment by reconman** [comment]
Sorry, I mixed Java with Lua. Remove the `new `.

**Comment by glassofmilk1** [comment]
![Screenshot_20200420-104020_Fate_GO](https://user-images.githubusercontent.com/55068302/79782355-c90da580-82f3-11ea-907c-93dcfd046f41.jpg)
![Screenshot_20200420-104038_Fate_GO](https://user-images.githubusercontent.com/55068302/79782362-cca12c80-82f3-11ea-8964-0af81d886b6e.jpg)

The bottom of the phone is on the left for the first screenshot and the right on the second

**Comment by reconman** [comment]
Aha! It's because the black bars are asymmetric. Right now the only way to run FGOlua on your device is by enabling full screen mode in Settings -> Display -> Full screen apps.

There may a better solution in the future, but it's hard to implement a fix when we don't have any developer with a Samsung device.

**Comment by glassofmilk1** [comment]
That seems to have worked, so I'm happy with the result regardless.
