### ISSUE TITLE
App Crashing after Daemon Successfully Installed

### ISSUE THREAD

**Issue by pikachuXLv100** [29988122/Fate-Grand-Order_Lua#311]
Hi, managed to successfully install the Daemon, but when I tried to open FGO_EN, my app crashed and immediately redirected me to a support request email to FGO support hub. Uninstalled Ankalua and rebooted my phone and tired to open FGO_EN again, same issue. Anybody knows what went wrong? Using unlocked LGV40 with no root, running Android version 9.

**Comment by pikachuXLv100** [comment]
Seems to think my phone is rooted, but it isn't...

**Comment by K4NZAKI** [comment]
Disable USB debugging. I happened to me.

**Comment by pikachuXLv100** [comment]
Disabled and was still unable to boot. Apparently my files in the data folder of FGO had been wiped... Uninstalled everything. Did a fresh reinstall, game still doesn't boot on my phone. Not sure what the daemon did, because even after restarting a bunch of times it still crashes. Still trying in hopes it would work normally again, likely have to factory reset my phone haha...

**Comment by pikachuXLv100** [comment]
Downloading FGO seems to not download it's associated app data into the phone's internal storage. I'm confused why this is happening...

**Comment by pikachuXLv100** [comment]
So to clarify on above, there isn't a file data/data/com.aniplex.fategrandorder

**Comment by K4NZAKI** [comment]
What the hell? Do you use Qoo App or Google play? Try downloading it on Qoo App, if it continues, send a print of the support email. I'll try searching for it.

**Comment by reconman** [comment]
No reply from user anymore, closing.
