### ISSUE TITLE
Card type problem. 

### ISSUE THREAD

**Issue by K4NZAKI** [29988122/Fate-Grand-Order_Lua#312]
I took a look on some other issues similar to mine, but couldn't find a way to fix it. Skill command works just fine, but when it goes to select the cards it shows a error message saying it couldn't identify the card type, but STILL selects them, and right after the script stops.

**Comment by K4NZAKI** [comment]
Does anyone have a older version of the code? I have tried everything already, used ankulua 8.6, 8.3, 8.5, 7.5... what the hell is wrong with the script?

**Comment by TheRealPlagiariser** [comment]
Could not reproduce it with ankulua 8.6 . Does it happen to any team comps you use? Can you provide a screenshot of the exact scenario of what cards it's trying to pick up before giving the error message?

**Comment by Aquatirem** [comment]
I am having this problem with ankulua 8.3 as well

**Comment by TheRealPlagiariser** [comment]
> I am having this problem with ankulua 8.3 as well

Update to latest ankulua 8.6.

**Comment by K4NZAKI** [comment]
Found a solution, replace all the files on the EN folder. It worked normally. Thanks for the answers.

**Comment by Aquatirem** [comment]
How did you replace them?
