### ISSUE TITLE
点击技能时经常点到英灵头像弹出英灵信息界面导致流程失败

### ISSUE THREAD

**Issue by caoli5288** [29988122/Fate-Grand-Order_Lua#313]
bilibili大陆服，请问是否有解决方案

**Comment by mingchungtsai** [comment]
I'm new to Git, so I'm not sure if the contributors in this project are Chinese. I think the issue title translates to: clicking on skill often clicks onto the servant portrait, popping the servant info frame resulting in the script flow breaking.

**Comment by TryBane** [comment]
@29988122 reads Chinese, maybe he can help?

**Comment by 29988122** [comment]
這聽起來像非標準屏幕大小導致的，說實話另一位維護者potchy和ankulua的開發者都有在試著解決這個問題，目前沒什麼進展..

這段期間內只能期望1.您自個把一些delay調慢 2.換快一點的手機/模擬器，以防點錯位置的事情發生

**Comment by caoli5288** [comment]
@29988122 目前我进行了如下调整，基本不会再出现乱点的状况。
1. 关闭 `Battle_AutoChooseTarget`
2. 打开 `Skill_Confirmation`

我推测是脚本中`Skill_Confirmation`延迟设定不正确导致的。

**Comment by reconman** [comment]
Seems solved
