### ISSUE TITLE
Auto skill doesn't seem to work properly

### ISSUE THREAD

**Issue by Exquivent** [29988122/Fate-Grand-Order_Lua#315]
I didn't even change anything "abc,#,def,#,ghi" is still the skill pattern but apparently instead of every battle use 1 set of skill, it uses the second and third skill in the second and third turn (not battle). I also tried to change it to "abc,0,#,def,#,ghi" but in the second turn it still activates the def skill and third turn it activates ghi. Because of that the auto NP cast is broken and can't be used properly, plus I force NP because auto skill is broken.

**Comment by TheRealPlagiariser** [comment]
Need these infos from you first:
1. Phone Model
2. Android Version
3. Ankulua Version
4. Party Comp( in order)
5. Node being used on
6. Screen Resolution
7. FGO_EN OR FGO_JP?
8. Using latest release version of script?
9. Detail every step of a complete run e.g
W1: 
Turn 1-> --servant does stuff
Turn2 ->--servant does stuff
W2:
Turn 3->--servant does stuff
W3:
Turn 4->--servant does stuff

**Comment by reconman** [comment]
No reply from user, closing now.
