### ISSUE TITLE
[Feature Request] Add target switching to Autoskill

### ISSUE THREAD

**Issue by TheIanator** [29988122/Fate-Grand-Order_Lua#32]
There have been times when I want to switch targets but not use NPs yet. What I was thinking was adding an option to turn off the default (Danger/Servant and use NP's) targeting in favor of some options in the command string.

For example:
"0,#,s1,#,s2t"
Where "s" and a number switches targets and "t" toggles the attempted use of all NPs every turn. 
So battle two switch to target 1, battle 2 switch to target 2 and begin using NPs.

Or another possibility for repeated NP use:
"0,#,4o5"
Where "o" attempts to repeat the following command every turn of the current battle.
So in the example  during battle 2 it uses NP 4 once and NP 5 every turn until the next battle.

Edit: Ended up implementing it myself, it wasn't very complicated and I don't yet know the proper way to suggest code, but I thought I'd share my work anyway.
[regular.lua.txt](https://github.com/29988122/Fate-Grand-Order_Lua/files/1722726/regular.lua.txt)

Added lines 87-90, modified lines 95, 242, 282, and 541. Also need to add line "Enable_Autotarget = 1" to FGO_XX_Regular.lua.

Functionality added is "m", "n", and "o" target enemies from left to right, should work on at least both NA and JP. Also added a option to turn of the default autotargeting.

Been working in my testing so far but I wouldn't be surprised if I broke something.

**Comment by 29988122** [comment]
I'm cleaning code, maaaybe this can be implemented soon^TM.

**Comment by 29988122** [comment]
One should consider this commit
https://github.com/29988122/Fate-Grand-Order_Lua/commit/b5c1e1edb636e7902ed44460cacb15f7e714cf3b

and this commit

https://github.com/29988122/Fate-Grand-Order_Lua/commit/057fcca2062b80bf3b944154a332f0c62bda5462

Before implementing such a feature, in order to prevent unintended behavior.

**Comment by reconman** [comment]
Implemented with #220
