### ISSUE TITLE
Script clicking on "help" after "start quest".

### ISSUE THREAD

**Issue by 5S29nwuB231FWfJLB** [29988122/Fate-Grand-Order_Lua#322]
NA version.

After selecting a support servant, if the game does not load the ensuing party screen fast enough the script seems to click the location of the "start quest" button but it will not register, and immediately afterwards click the location of the "help" button on the left side of it. The click on the left of "start battle" can be seen in the loading screen too so it seems to be intended.

The result is that if the loading of the party screen is not instant, the script appears to click on "help" and then get stuck on the tutorial popup until the user manually intervenes.

Is there a particular reason that the click after "start quest" is done? If it was moved just a few pixels to the right, on top of the "total cost" counter it shouldn't cause any issues as long as the script keeps clicking on "start quest" until the loading screen happens.  Another solution would be to add a few seconds of delay before clicking on "start quest".

**Comment by TheRealPlagiariser** [comment]
Slow phones/ slow internet usually can cause issues. 
The solution is simple, if you are loading slower than the script has been programmed to, you have to add a delay.

Open regular.lua file, and add a delay "wait(2.5) exactly where you see the "local function StartQuest()

> local function StartQuest()
        wait(2.5) -- add this and change the number accordingly to what your phone can handle.
> 	click(game.MENU_START_QUEST_CLICK)
> 
> 	-- old scripts might not have this option set
> 	-- don't wanna force everyone to update their configs
> 	if BoostItem_SelectionMode ~= nil then
> 		if game.MENU_BOOST_ITEM_CLICK_ARRAY[BoostItem_SelectionMode] ~= nil then
> 			wait(2)
> 			click(game.MENU_BOOST_ITEM_CLICK_ARRAY[BoostItem_SelectionMode])
> 			click(game.MENU_BOOST_ITEM_SKIP_CLICK) -- in case you run out of items
> 		else
> 			scriptExit("Invalid boost item selection mode: \"" + BoostItem_SelectionMode + "\".")
> 		end
> 	end

**Comment by 5S29nwuB231FWfJLB** [comment]
Thank you, this solution appears to work.
