### ISSUE TITLE
Does auto support not pick up grailed Servants?

### ISSUE THREAD

**Issue by synthelite** [29988122/Fate-Grand-Order_Lua#325]
Trying to make it pick Summer Nero servants with MLB the Scholars of Chaldea, but it seems to skip past a friend's maxed grailed one?

**Comment by TheRealPlagiariser** [comment]
Can you provide a picture of the summer nero .png file you are using? There's no way to analyse the issue without the materials at hand unfortunately.

**Comment by Skyjersey** [comment]
You could just specify the friends name so the script will always pick it.

**Comment by synthelite** [comment]
Strange, perhaps just restarting the script works. It works now after I fully reset the anklua, I'll put this on hold until it comes up again..
