### ISSUE TITLE
Script stops on manual Support selection

### ISSUE THREAD

**Issue by reconman** [29988122/Fate-Grand-Order_Lua#326]
I'm new to this script and wrote my own Da Vinci farming script. The script doesn't detect MLB scholars of chaldea, so I set the support selection to manual.

Now whenever I start the script from the quest selection screen and get to the support page, I get a message that support selection is manual, I click "Ok" and then the script stops. If I start the battle, the script is still stopped (play button in the bottom left corner)

What am I doing wrong?

**Comment by reconman** [comment]
And now when the first battle finished and I started another quest, the script starting battling again but this time it ignored the AutoSkill commands and just used face cards.

**Comment by Skyjersey** [comment]
Modify a line in modules/support.lua

`local limitBreakPattern = Pattern(GeneralImagePath .. "limitBroken.png"):similar(0.8)`

change it to 	

`local limitBreakPattern = Pattern(GeneralImagePath .. "limitBroken.png"):similar(0.7)`

Worked for me.

**Comment by reconman** [comment]
I'm dumb, I didn't read the https://github.com/29988122/Fate-Grand-Order_Lua/wiki/AutoSupportSelection guide.

Also I just had to wait for the script to tell me that I should select the support in manual mode, then start it again.
