### ISSUE TITLE
Auto gift Exchange

### ISSUE THREAD

**Issue by FrayXQ** [29988122/Fate-Grand-Order_Lua#327]
is the auto gift exchange script supposed to reset boxes ?

**Comment by TheRealPlagiariser** [comment]
Yes it will reset the box #329

**Comment by reconman** [comment]
By adding some FinishedLotteryBoxRegion:highlight() calls I was able to find out that the coordinates of that Region is off. I was able to correct it by changing `local FinishedLotteryBoxRegion = Region(520, 840, 70, 100)` to `local FinishedLotteryBoxRegion = Region(575, 860, 70, 100)`

Should work with any region.

**Comment by FrayXQ** [comment]
thanks, fixed it

**Comment by reconman** [comment]
@FrayXQ Keep this issue open until they fix it.

**Comment by reconman** [comment]
Duplicate of #303
