### ISSUE TITLE
Problems with AutoSupportSelection

### ISSUE THREAD

**Issue by bhaamr** [29988122/Fate-Grand-Order_Lua#328]
```-AutoSupportSelection
Support_SelectionMode = "preferred"
Support_SwipesPerUpdate = 3
Support_MaxUpdates = 10
Support_FallbackTo = "first"
Support_FriendsOnly = 1
Support_FriendNames = ""
Support_PreferredServants = "drake.png"
Support_PreferredCEs = "*the_scholars_of_chaldea.png"
```
all my script works fine until i have to pick supps, any idea what am i doing wrong? it worked once and picked the correct drake but afterwards it doesn't recognize any drake and just refreshes, any ideas?

![drake](https://user-images.githubusercontent.com/60025926/72658742-19830900-397b-11ea-8a7b-09b466b119cd.png)

this is the drake ss that im using

**Comment by Skyjersey** [comment]
From my experience I use the paint program in windows to edit the screenshot I made to make it work. I used to use another program to edit it but it won't detect it.

**Comment by hayate1412** [comment]
So the problem lie on the support images?
How do i fix them?

**Comment by OzymanDIO** [comment]
I have some problem too. But I've checked that it is able to recognize the servant and ce I preferred when I choose "any" for one of them. But when I choose both preferred servant and CE instead of pick "any" one of them, it failed to works. Help pls.

**Comment by reconman** [comment]
I've had similar issues in the past and at some point I figured out the problem. Most likely you used a 1080p screenshot while the normal support images are created in 720p.

In regular.lua, there are these 2 lines of code:
```
local IMAGE_WIDTH = 1280
local IMAGE_HEIGHT = 720
```
which indicate how much images need to be scaled.

If you would change these values to 1920 and 1080, all the existing support images don't work anymore.

The much better solution is to open your image in an editor, downscale it to 75 % of the size and then using that.

In the future you can also downscale the complete screenshot if you need multiple images from one screenshot.

**Comment by reconman** [comment]
You can now use https://29988122.github.io/Fate-Grand-Order_Lua/#/support-image-maker
