### ISSUE TITLE
How do you calculate the X and Y coordinates of buttons correctly?

### ISSUE THREAD

**Issue by reconman** [29988122/Fate-Grand-Order_Lua#329]
I tried to fix the Lottery Box script by adjusting the Reset button position because I'm suspecting that the location in the script is wrong.

But I have no idea on how to calculate the correct locations when scaling.ApplyAspectRatioFix() has been called.

My screen is 2280 * 1080 pixels. I can get the Y position by using `scriptY = measuredY / 1080 * 1440`. But with the X coordinates being manipulated by the notch and blue paddings, I have no idea what the formula is.

Could anyone help?

**Comment by TheRealPlagiariser** [comment]
I'd suggest using your own width and height if you aren't planning on changing mobile phone.
`local SCRIPT_WIDTH = 2280
local SCRIPT_HEIGHT = 1080`

And the next thing you have to do is use Ankulua's SnapAndPlay/RecordAndPlay script and get each button's real coordinates and replace in 

```
-- consts
local SpinClick = Location(605, 639)
local FinishedLotteryBoxRegion = Region(374, 597,152, 152)
local FullPresentBoxRegion = Region(1217, 771, 152, 152)
local ResetClick = Location(1715, 369)
local ResetConfirmationClick = Location(1158, 844)
local ResetCloseClick = Location(1001, 847)
```

**Comment by reconman** [comment]
I don't like that approach since it won't be a global script valid for anyone and I don't know exactly what the old coordinates correspond to on my screen.

**Comment by reconman** [comment]
I found out how to calculate the X value. You need to do the following steps:

1. Take a screenshot and remove the notch and blue borders
2. Measure the width of your new image, for me it was 1920 pixels 
3. Measure the X coordinate of the button you want to click in your new image
4. scriptX = measuredX / newImageWidth * SCRIPT_WIDTH
