### ISSUE TITLE
Galaxy S8 not working

### ISSUE THREAD

**Issue by RUBENGS** [29988122/Fate-Grand-Order_Lua#33]
Since the screen ratio is different, that might be an issue. Any known solutions or fixes?

**Comment by 29988122** [comment]
Can you have a screenshot of it running in menu screen(chaldea gate?)

Two is better, one with navigator bar on and one with it off(immersive fullscreen).

**Comment by RUBENGS** [comment]
https://imgur.com/a/9OJs0

https://imgur.com/a/H76Il

FateGO doesnt run fullscreen (it cant, only the opening screen does it)

Also, used Nox player to do the same exact thing on another account and worked. 

My only guess would be the screen size and ratio. Tried changing the screen resolution to 720, 1080 and 1440 but I can't change the ratio. (18.5:9)

**Comment by 29988122** [comment]
I tested a little bit.

Which one is your situation?

1.The script click, but clicked the wrong position.
2.The script did not click at all.

If the situation is 2, please recheck your daemon related settings like installation - that means Ankulua did not work. : (

**Comment by RUBENGS** [comment]
It's the second one (with the regular script). Also tried de FP gatcha script, this one clicks but the wrong position

**Comment by 29988122** [comment]
http://ankulua.boards.net/board/1/general-discussion

You may want to ask for support here. Let me know the results here tho!

If the Ankulua framework cannot get the display ratio correctly, then it's beyond my scope of problem solving : (

**Comment by paumi** [comment]
I have the same problem since i have an s8+ device. I was looking at the code and i guess we could fix that by changing the regions, since the s8 have two black edges when playing FGo. The problem is i don't know how regions work >.<. Are the regions pixel coordinates??

**Comment by 29988122** [comment]
http://ankulua.boards.net/thread/978/problem-s8-device

I saw that one of you asked here.


The problem is (probably) that Ankulua *should have* capture app usable screen area only, not the whole screen area. It worked well on other phone, so I guess it's a samsung os compatibility thing.

**Comment by RUBENGS** [comment]
Ended up modidying the script (regular) regions and locations. That killed the multiple devices support but now works on S8 when using 2220x1080 resolution.

All I did was delete all the setting options and rescale regions and locations to 1080 (that is 1440 used in the script x 0.75). Then added 150 to every x coordinate (2220-1920)/2 for the black side bars.

Also had to update the images to the new resolution.

**Comment by RUBENGS** [comment]
*modifying

**Comment by 29988122** [comment]
All that modifying/hacking must be really tiresome! The scaling should have been done by Ankulua.

Anyway, good job mate! Hope the author of Ankulua can fix this soon.

**Comment by N0jja** [comment]
@RUBENGS Hey, could you send us the modified lua script file please ? that would be nice ! Thanks

**Comment by Juliannico111** [comment]
@RUBENGS The updated script would be great, this error occurs for all bezel-less phones (18:9)

**Comment by 29988122** [comment]
I've got some assistance from the author of Ankulua.

Part of the resize script was like:
```
function detectDimension(reg, target, initDimension)
    local defaultDimension = preferenceGetNumber("defaultDimension", initDimension)

    local dimension = autoResize(target, defaultDimension, true, reg)
    if (dimension < 0 and defaultDimension ~= initDimension) then
        dimension = autoResize(target, 1280, true, reg)
    end

    local widthOn720 = getRealScreenSize():getX() * 720 / getRealScreenSize():getY()

    regionXShift = 0;
    if (dimension < 0 and widthOn720 > 1290) then
        print("widthOn720 = " .. widthOn720)
        Settings:setScriptDimension(true, widthOn720)
        Settings:setCompareDimension(true, widthOn720)
        regionXShift = (widthOn720 - 1280) / 2
        local newReg = reg:offset(regionXShift, 0)
--        newReg:highlight(1.0)
        dimension = autoResize(target, widthOn720, true, newReg)
    end
    if (dimension < 0) then
        scriptExit("錯誤:\n   找不到聊天圖示，可能是不支援的長寬比")
    end

    toast (""..dimension)
    print("Version " .. version)
    print ("dimesion = "..dimension)

    preferencePutNumber("defaultDimension", dimension)
    return dimension
end
```
It will take me some time to understand this : p

**Comment by 29988122** [comment]
To be honest, to achieve this I'd have to modify every line with region function - make it more robust, rather than hard-coded value. 
It could take a fair amount of time(as a novice).  Also current I don't really have much of it, got some school related theorycrafting thing to do.

In the mean time, I suggest you use the emu NOX instead. It would not only save your battery juice, but also was reported that both JP&TW version of FGO can be executed on it without any problem - such as emu and root detection.

**Comment by 29988122** [comment]
@RUBENGS @N0jja @Juliannico111 @paumi 

It is said that Ankulua 7.5.1 (2018/3/15) solved the 18:9 screen issue, I believe that it included Galaxy S8.

Does it work now?

**Comment by ness151** [comment]
I just tested the friend gacha lua on my S8, and it works except when it needs to hit the OK button on the "Summon with x friend points.." screen, the button press is too low.

**Comment by 29988122** [comment]
try this file:
press raw button->save as->put it in your s8


https://github.com/29988122/Fate-Grand-Order_Lua/blob/48ad7818508368b3a97bf565790fbc3e84beebfb/_auto_friendgacha.lua

**Comment by ness151** [comment]
Unfortunately, it didn't.  It's now trying to hit near the "Friend Point Summon" text (The "Fr" point) and nowhere near the summon button at all.  See here https://imgur.com/LDQVolQ.gif (ignore the last tap in the top right of the gif, that was me ending the recording.)

**Comment by 29988122** [comment]
I did try to replicate it with emulator(no s8 or 18:9 cellphone), in order to report it to Ankulua Author.

Unfortunately I cannot reproduce it, but I should be able to, no idea why..
If anyone can figure this out or can apply calculations to the existed script, I'd be very happy.
*it should not be simple coordinate replacement, at least we'll need to check for screen resolution / screen aspect.&

In the meantime, I guess it will keep the current status, sorry : (

**Comment by 29988122** [comment]
https://github.com/29988122/Fate-Grand-Order_Lua/commit/d7b8f8b466867f3d87289feb5c99a46400130a6a

At least, auto friend gacha should be working...or is it?
Weird that I cannot change the emu screen aspect to debug, but this confirmed worked on my side.
