### ISSUE TITLE
Issue with recognizing card type in CN

### ISSUE THREAD

**Issue by applefruit88** [29988122/Fate-Grand-Order_Lua#331]
Failed to recognize card type in every battle, it just keep selecting the first 3 cards from the left only. Tried replacing the card image in image_CN still not working, please help.

Model: Huawei P20 Pro
Device Resolution: 2240x1080

![image](https://user-images.githubusercontent.com/60069062/72683701-79f97e00-3b14-11ea-8867-5ae3f00bc186.png)

**Comment by reconman** [comment]
@29988122 @potchy Looks like Buster, Quick and Arts were changed to Chinese. See https://youtu.be/O2JxkdnVWMU?t=491

**Comment by 29988122** [comment]
They (bilibili) frequently change card design.. for at least 2 times, when I'm still active(kind of ) maintaining.

If that's been settled for a while.. Since we're using 1280 * 720, I think it can be googled relatively easy. (I don't have bilibili fgo account)

**Comment by MathewSachin** [comment]
@applefruit88 I've updated CN card type images. Give the latest code a try.
