### ISSUE TITLE
adding use Mystic code

### ISSUE THREAD

**Issue by keibebe** [29988122/Fate-Grand-Order_Lua#334]
It's possible to use Mystic code? I wonder because i know, and i'm using order change. Is there a way to use the other spells? if not i would be amazing to add them because for some strong servants it is hard to oneshot or kill faster witout using atk ups.

**Comment by potchy** [comment]
from the docs:

> ',' = Turn counter
> ',#,' = Battle counter
> '0' = Skip 1 turn
> 
> Servant skill = a b c	d e f	g h i
> **Master skill = j k l**  <-- Mystic Code
> Target Servant = 1 2 3
> Activate Servant NP = 4 5 6
