### ISSUE TITLE
The Script is not running on NOX

### ISSUE THREAD

**Issue by EWolverine808** [29988122/Fate-Grand-Order_Lua#338]
When i use the NA version of the script on my phone,it's running normally but when i use the JP version of the script on NOX. It's like this:
![image](https://user-images.githubusercontent.com/58509250/75110686-b5332380-5663-11ea-91c9-dcaf940dea5e.png)
I wait for a half an hour but notthing happen. :(

**Comment by Thunray** [comment]
Same for me, and when is on the friend servant selection screen gives me this error: 

https://i.imgur.com/QnPFg4S.png

Something is wrong with the JP scritps ;_;, can someone help us?

**Comment by observeroftime02** [comment]
Same problem, "first" support selection option throws the null pointer exception, or it just repeatedly draws red squares. An older version of the script worked for me (last working release I downloaded was around end of January)

**Comment by reconman** [comment]
The title of #340 is more clear, that's why I noticed it there first. I have an open PR to fix the issue.

**Comment by reconman** [comment]
@potchy Please close this because of #343
