### ISSUE TITLE
New Support Selection Issue and band-aid for some users

### ISSUE THREAD

**Issue by zxcvnnvcxz** [29988122/Fate-Grand-Order_Lua#339]
@TryBane 
I had some issues with the new support selection on my phone (LGV30, V8.0.1) so I took out some old support lines in game.lua and put it in the new game.lua, as well as using the old support.lua instead of the new one, while putting in `game.NeedsToRetry` in the old support (L153). Don't know if the retry would work, but even if it doesn't I don't really mind.

I am definitely not a coder so sorry for the formatting, just thought if anyone ran into this issue this would help.

Btw, the issue was that it wouldn't correctly click on a servant with a preferred CE, it would instead long press and show the Servant Info.

This is what I'm using as bandaid:
[game and supportlua.zip](https://github.com/29988122/Fate-Grand-Order_Lua/files/4243261/game.and.supportlua.zip)

**Comment by TryBane** [comment]
Hmmm, long click you say? That is most certainly odd... I'll have to look into this.

**Comment by zxcvnnvcxz** [comment]
After a fresh install of latest release and some testing, it now only occasionally happens to MLB CE's with both specific servants / none-specific servants, maybe one out of ten times. However, in the case that it doesn't happen, the script does consistently seems to miss the first scroll-through, only picking back up by the second or third refresh.

Non-MLB CE's with both specific / none-specific servants work fine, and does not produce a misclick in where Servant Info is displayed, trapping the script.

I think it has something to do with how when it scrolls, it usually holds a servant down (3rd servant down) and scrolls, but when it finds a support with a preferred CE, the scroll doesn't happen but since it is holding that servant down it goes to Servant Info. It seems to know that the preferred CE has appeared on screen, but it doesn't click on the region where the CE is like it usually does and instead starts to try scrolling.

It might be an issue relating to 18:9 aspect ratios. I have tried putting FGO in both 16:9 aspect and original, to no difference.
