### ISSUE TITLE
Got runtime error at the begin of the battle

### ISSUE THREAD

**Issue by watchlee** [29988122/Fate-Grand-Order_Lua#34]
After I modified the script "FGO_TW_REGULAR" and ran on NOX app player, I got the runtime error at the beginning of the battle.  If only run the original script "FGO_TW_REGUALR", it can work without generating any errors. Also, I found that only the problem may happen in Skill_Command. If only give Skill_Command = "bcde5,#,0", it can work. When I give Skill_Command = "bcde5,#,h", the error would generate. Could you give me some advice? 

The following instruction that I modified in FGO_TW_REGULAR.lua
Refill_or_Not = 1
Use_Stone = 0
How_Many = 5
Enable_Autoskill = 1
Skill_Confirmation = 0
Skill_Command = "bcde5,#,h6,#,0"

![bug](https://user-images.githubusercontent.com/6651815/36340440-e26253c0-1417-11e8-894b-1bc0037add10.JPG)

**Comment by ryuga93** [comment]
My guess is the script can't identify stage 2 of the battle, in regular.lua please add `toast(currentStage)` after `currentStage = checkStageCount(stageCountRegion)` and check the pop up message shown then let me know

**Comment by watchlee** [comment]
Can't get any message due to the error is happened in currentStage = checkStageCount(stageCountRegion). When I tried to use toast( stageCountRegion ) and toast( checkStageCount(stageCountRegion) ) to print the value, it got runtime error at toast( stageCountRegion ). Seems like the problem is happened on value stageCountRegion.

**Comment by watchlee** [comment]
Hi, I uploaded the latest version for cropping. All graphs resolution are 1280 x 760. Hope it could help to solve this problem. 
![battle1](https://user-images.githubusercontent.com/6651815/36595213-470b248c-18dc-11e8-884b-23636f81310d.png)
![battle2](https://user-images.githubusercontent.com/6651815/36595214-49043cb0-18dc-11e8-9add-ee4fc7efb75c.png)
![battle3](https://user-images.githubusercontent.com/6651815/36595218-4a60925c-18dc-11e8-886e-154cb7e00156.png)
![round1](https://user-images.githubusercontent.com/6651815/36595221-4e50bb76-18dc-11e8-9850-8df89f6c3096.png)
![round2](https://user-images.githubusercontent.com/6651815/36595223-50d2cae2-18dc-11e8-8d8e-7bae93e30307.png)
![round3](https://user-images.githubusercontent.com/6651815/36595225-534daf94-18dc-11e8-86f1-8a3a0361310c.png)
![round4](https://user-images.githubusercontent.com/6651815/36595227-54bfce2a-18dc-11e8-9062-4fcadc2fcbc4.png)
![round5](https://user-images.githubusercontent.com/6651815/36595230-56070e4c-18dc-11e8-9a8a-faa22725c154.png)
![round6](https://user-images.githubusercontent.com/6651815/36595231-5813309e-18dc-11e8-8125-2884720370da.png)
![round7](https://user-images.githubusercontent.com/6651815/36595243-5f4479b8-18dc-11e8-934b-1ef3c5e28448.png)
![round8](https://user-images.githubusercontent.com/6651815/36595246-60e3b086-18dc-11e8-9260-5b9b2449b6d4.png)
![round9](https://user-images.githubusercontent.com/6651815/36595249-622cb21c-18dc-11e8-9274-9f286193d024.png)
![round10](https://user-images.githubusercontent.com/6651815/36595252-63685b40-18dc-11e8-98bc-2ea51261c8fa.png)
![round11](https://user-images.githubusercontent.com/6651815/36595254-65ae85d2-18dc-11e8-8de7-7d55288cc01d.png)

**Comment by 29988122** [comment]
Try replace the files modified in this commit.
https://github.com/29988122/Fate-Grand-Order_Lua/commit/39af602ceca61546a0efd413626d1bcf0117a210

Since Ankukua doesn't support transparent color, this make it more difficult.

If that still didn't work, add this line into regular.lua to see if it works.
Settings:set("MinSimilarity", 0.5)

**Comment by watchlee** [comment]
It works now. Thanks a lot!
