### ISSUE TITLE
NullPointer error on support selection

### ISSUE THREAD

**Issue by pozeromon** [29988122/Fate-Grand-Order_Lua#340]
I can't understand which is the error here, other times it leds me to the images, but this time I don't know.
![Screenshot_20200224-102152](https://user-images.githubusercontent.com/48263725/75156120-2fa98500-56f0-11ea-82c8-7fd3e2ba9754.png)
![Screenshot_20200224-031814](https://user-images.githubusercontent.com/48263725/75156181-51a30780-56f0-11ea-9508-3528ee06844b.png)

**Comment by pozeromon** [comment]
![Screenshot_20200224-102916](https://user-images.githubusercontent.com/48263725/75156279-8adb7780-56f0-11ea-8b57-cfd074eb26e3.png)

**Comment by observeroftime02** [comment]
Getting the same error on the latest version, but only if support selection is set to "first". "preferred" still works correctly.

**Comment by metapea** [comment]
I'm also getting that same error as well, although, if you pick your support manually it works normally.

**Comment by reconman** [comment]
In the last PR, game.SUPPORT_FIRST_SUPPORT_CLICK was deleted by accident. I've added it back in my PR.
