### ISSUE TITLE
Is this still safe?

### ISSUE THREAD

**Issue by Claey** [29988122/Fate-Grand-Order_Lua#344]
The new engine will be implemented on NA soon enough, is it gonna be safe to use this after the new engine came?

**Comment by reconman** [comment]
Why would it not be? JP is running on the new engine and the JP script works fine.

**Comment by metapea** [comment]
the en script is working for the most part.

**Comment by Claey** [comment]
> Why would it not be? JP is running on the new engine and the JP script works fine.

Oh cool! it's nice to know that it's gonna be fine.
