### ISSUE TITLE
Autoskill fail in stage 3 (TW)

### ISSUE THREAD

**Issue by aqer** [29988122/Fate-Grand-Order_Lua#35]
I enable autoskill to run free quest on TW server.
Servant can cast skill in the first two stage,
but they never cast skill in 3rd stage.
Version: 1.8.1
補充:關卡是第五章夏洛特的FQ,看起來是偵測stage時無法認出是stage3

**Comment by justfree97** [comment]
我有相同的問題 在3rd stage不會施放設定好的技能 而是直接選取寶具卡的功能
但在有些關卡是在3rd stage是可以正常施放技能的


正常關卡截圖
![screenshot_20180325-071842](https://user-images.githubusercontent.com/37006438/37870023-d8206d36-2ffe-11e8-9d6e-ef55ce13d1a4.png)
不正常關卡截圖
![screenshot_20180325-072928](https://user-images.githubusercontent.com/37006438/37870012-9d62ab1e-2ffe-11e8-929c-c35ee3dd16a2.png)

使用機型 Sony z5p

**Comment by 29988122** [comment]
https://github.com/29988122/Fate-Grand-Order_Lua/commit/a72a8f02599423c8ccdb34bf9c2c12735ec4cc5b

請試試看這個commit能不能解決問題
因為我比較笨，sikuli又不支援透明色，所以試試看這個修過的版本。

**Comment by ryuga93** [comment]
hmm, use multiple "or" conditions for different background @.@?

**Comment by justfree97** [comment]
我置換新的圖片進行腳本後的狀況是一樣的 不能正常運行的關卡還是在第三關無法施放技能
似乎背景比較陰暗的關卡才會偵測不到數字3這個圖片

**Comment by 29988122** [comment]
Try this commit.
https://github.com/29988122/Fate-Grand-Order_Lua/commit/8e0dd93e07be1b8dbb553a0ab9e647ad70644875

An inelegant one, but could work.
Tried a few methods, but this seems like the best idea.
Tested on JP server.

**Comment by 29988122** [comment]
https://github.com/29988122/Fate-Grand-Order_Lua/releases/tag/1.8.2

Should be OK now, 換了一個還可以的解法..
