### ISSUE TITLE
Autoskill stops working every second or third iteration.

### ISSUE THREAD

**Issue by Cerz0** [29988122/Fate-Grand-Order_Lua#354]
After completing the node once or twice the script will stop using autoskill and go with facecards.

This is the current string i'm using:
"i6,#,ge5,#,i1aj14"

First battle is Arash clear. (It would be nice to have an option to have Arash facecards given less priority than any other).
2nd Battle:
Merlin comes in and uses 1st skill.
Saber Liz uses 2nd skill
Saber Liz uses NP
3rd Battle:
Merlin uses 3rd skill on first servant (Tiddy Monk)
Tiddy Monk uses 1st skill
Mystic code 1st skill on Tiddy Monk (Cant remember how to write the name)
Tiddy Monk uses NP.

Sharing my Merlin SUPPORT since all of them in my support list look like that:
![merlin5](https://user-images.githubusercontent.com/62533167/77333907-62ad5b80-6d24-11ea-936e-d162973260a9.png)

My device is a Lenovo TAB10 Plus: https://www.amazon.es/gp/product/B0735BCTCL/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1

**Comment by Cerz0** [comment]
I'm using the AnkuLua version provided on the download link 8.6.1.
The party is Tiddy Monk > Saber Liz > Arash > Merlin
I'm using it on the last farming node (Super Dimension) of Saber Wars.
Screen: 1920x1200 pixel
FGO_EN
Downloaded the script yesterday.

**Comment by potchy** [comment]
Possibly related to #315, #306 and #272, though I've never encountered this issue myself or been able to replicate it.

**Comment by Cerz0** [comment]
In my case it feels as if auto skill was disabled, now i've seen it happening in the first run.

**Comment by reconman** [comment]
> Skill_Command = "i6,0,0,#,ge5,0,#,i1aj14,0,0"

Why all the 0s?

**Comment by Cerz0** [comment]
> > Skill_Command = "i6,0,0,#,ge5,0,#,i1aj14,0,0"
> 
> Why all the 0s?

So the script uses facecards next turn in case the NP leaves something alive, if the battle goes into the next stage the script ignores them, also my issue happens both with and without them.

**Comment by Claey** [comment]
This also happens to me every now and then, though I encountered a new problem that it starts to open up servant details and mess up the script in the 3rd wave after completing nodes 1-2 time(s)

**Comment by reconman** [comment]
@Claey Is it possible that you rotated your screen in the middle of the script and you have a notch? If so, that explains the wrong click positions, because the script doesn't recalculate the game area on screen rotation. So it thinks the black notch bar is still in the same position as before.

I don't know if we can solve that problem, it's a hard one that hasn't been solved by anyone in any Ankulua project yet, I think.

**Comment by Cerz0** [comment]
about my original issue, i think that what happens is that it doesnt press the "i" position that would be Arash self charge and the everything else goes wrong because he doesnt die.

I think it may be solved adding a bit of a delay in case it is lagging because i saw it trying to tap the position for Arash's Np right afterwards.

{
		Name = "PARTY IX - Flaming Mountain", -- Party IX -> Raikou, Eresh, Arash/Waver
		Skill_Command = "i6,0,0,#,efhi5,0,0,#,k1g1abc4,0,0",
		Support_SelectionMode = "preferred",
		Support_PreferredServants = "waver4.png, waver3.png, waver2.png, waver1.png",
		Support_PreferredCEs = "the_classic_three_great_heroes.png, divine_princess_of_the_storm.png",
	},
	{	
		Name = "PARTY VII - Tianzhu", -- Party VII -> Raikou, Kintoki, Arash/Waver
		Skill_Command = "i6,0,0,#,icde5,0,0,#,k1g1hab4,0,0",
		Support_SelectionMode = "preferred",
		Support_PreferredServants = "waver4.png, waver3.png, waver2.png, waver1.png",
		Support_PreferredCEs = "true_samadhi_fire.png, go_west.png",
	},
	{	
		Name = "PARTY VI - Tathagata", -- Party VI -> Salter, Drake, Arash/Waver
		Skill_Command = "i6,0,0,#,cfhi5,0,0,#,k1g1abd4,0,0",
		Support_SelectionMode = "preferred",
		Support_PreferredServants = "waver4.png, waver3.png, waver2.png, waver1.png",
		Support_PreferredCEs = "divine_princess_of_the_storm.png",
	},
	{	
		Name = "PARTY V - NARAKA", -- Party V -> Raikou, Mecha-Eli, Arash/Waver
		Skill_Command = "id6,0,0,#,fhi5,0,0,#,k1g1abc4,0,0",
		Support_SelectionMode = "preferred",
		Support_PreferredServants = "waver4.png, waver3.png, waver2.png, waver1.png",
		Support_PreferredCEs = "ox_demon_king.png, go_west.png",

**Comment by reconman** [comment]
@Cerz0 I would recommend trying different wait values until it works on your device. For most users the script works in its current form.

**Comment by Cerz0** [comment]
where can i change that?

**Comment by reconman** [comment]
https://github.com/29988122/Fate-Grand-Order_Lua/blob/master/modules/battle.lua

wait(x) means wait for x seconds before continuing. I can't tell you which waits need to be modified exactly, but try this one first https://github.com/29988122/Fate-Grand-Order_Lua/blob/master/modules/battle.lua#L89

**Comment by Cerz0** [comment]
ok, i'll set it to 5, i assume it is seconds, and keep an eye on it, the issue doesnt happen as much since i updated the script on 12/04.

Also i got a question, is there a way to force a Brave chain with the NP if one is available?

**Comment by reconman** [comment]
> Also i got a question, is there a way to force a Brave chain with the NP if one is available?

No, brave chaining has been a long wanted feature, but it's currently on halt. https://github.com/29988122/Fate-Grand-Order_Lua/issues/321

**Comment by Cerz0** [comment]
is there any way to get around AnkuLua cooldowns? i dont mind the cooldown nut the way it increases while i dont press OK just kills me.

**Comment by 29988122** [comment]
> 
> 
> is there any way to get around AnkuLua cooldowns? i dont mind the cooldown but the way it increases while i dont press OK just kills me.

I can't help you as I don't know the way. Sorry.

Some ppl reverse engineered the f out of old version Ankulua APKs.
I reported that to the author btw. You can still find the post, but it's no more relevant. For research purposes I'd say?

***

Developing and dealing with All android versions/phone variants is no small feat. I'd say it's not like purchasing a *cheat*, more like supporting an automation framework (selenium for android? lol).
There will be no FGOLUA without hundreds of hours by the authors of Ankulua.

Although I got my free copy during early times of AnkuLua, I'd say if I were to purchase another lifetime copy, I'll definitely do that without any hesitation. 

You can still try reverse engineering tho.

**Comment by Cerz0** [comment]
i think changing the delay to 5 may have solved the issue.
i'm considering buying AnkuLua.
How can i contribute the support CE images for the newest event?
![an_afternoon_at_the_fortress](https://user-images.githubusercontent.com/62533167/80267496-97089480-86a1-11ea-872b-86158138350b.png)
![away_we_go](https://user-images.githubusercontent.com/62533167/80267497-97a12b00-86a1-11ea-92c8-3952baed1652.png)
![distantp_pilgrimage](https://user-images.githubusercontent.com/62533167/80267498-9839c180-86a1-11ea-89a8-2ac68fe28524.png)
![moment_of_bliss](https://user-images.githubusercontent.com/62533167/80267499-9839c180-86a1-11ea-9e36-9e05eb974149.png)

**Comment by reconman** [comment]
@Cerz0 it's best if you add them to the image_support folder on a branch in your fork and then create a pull request to merge your changes into this repository

**Comment by reconman** [comment]
@Cerz0 After asking 29988122 for permission, I can offer you a free alternative for FGOlua, https://github.com/MathewSachin/Fate-Grand-Automata/.

We still have an open issue for making the wait times configurable, but maybe it works out of the box for you. A new release will come soon, which will fix some timing problems for master skills.
