### ISSUE TITLE
Problem with Fullscreen Phone

### ISSUE THREAD

**Issue by AlfredPaguio** [29988122/Fate-Grand-Order_Lua#357]
Hello ahmm I'm using Xiaomi Redmi Note 7
Already set the autoGameArea to false
And added gameWithoutBordersAndNotch:highlight()
Before setGameArea(gameWithoutBordersAndNotch)
![Screenshot_2020-04-08-14-34-31-225_com aniplex fategrandorder en](https://user-images.githubusercontent.com/25319699/78752348-87e9cd00-79a6-11ea-80d9-13426252002e.jpg)

**Comment by reconman** [comment]
autoGameArea should be true, since you have a notch. setImmersiveMode should also be true, since you don't have a navigation bar: https://ankulua.boards.net/thread/7/settings

**Comment by AlfredPaguio** [comment]
Sorry for the late reply 
I set setImmersiveMode and autoGameArea to true and the photo is the result

gameWithoutBordersAndNotch is red
gameWithBorders is green
gameWithoutBorders is yellow 
The ankulua app is already set at fullscreen
![Screenshot_2020-04-22-18-57-23-340_com aniplex fategrandorder en](https://user-images.githubusercontent.com/25319699/79974305-aafa9d80-84cb-11ea-9be8-1f6fae0b30f7.jpg)

**Comment by reconman** [comment]
It's best if you don't do `:highlight()` on the regions, but instead do it on Region(0, 0, 2560, 1440) at the end of the scaling function:

![image](https://user-images.githubusercontent.com/12360257/79974738-25122e80-849a-11ea-890f-092c32e8c63d.png)

The other highlights won't work properly, even on my phone where the script works fine.

**Comment by AlfredPaguio** [comment]
This is the result
![Screenshot_2020-04-22-19-22-20-296_com aniplex fategrandorder en](https://user-images.githubusercontent.com/25319699/79976183-c5824600-84ce-11ea-9a9c-1ea5cc66bfad.jpg)
![IMG_20200422_192300](https://user-images.githubusercontent.com/25319699/79976205-cdda8100-84ce-11ea-9e61-82d73abaf0d0.jpg)

**Comment by AlfredPaguio** [comment]
Nevermind the previous I'm stupid lol
![Screenshot_2020-04-22-19-24-57-214_com aniplex fategrandorder en](https://user-images.githubusercontent.com/25319699/79976375-12feb300-84cf-11ea-823d-a8eb9d164a80.jpg)
![IMG_20200422_192517](https://user-images.githubusercontent.com/25319699/79976388-1abe5780-84cf-11ea-9dbe-9c1d3974821e.jpg)

**Comment by reconman** [comment]
Definitely looks correct now.

**Comment by AlfredPaguio** [comment]
That's weird the script is not working for me

**Comment by AlfredPaguio** [comment]
![Screenshot_2020-04-22-19-27-14-794_com aniplex fategrandorder en](https://user-images.githubusercontent.com/25319699/79976524-59eca880-84cf-11ea-8a69-baf058cbd27c.jpg)
Should I manually set the setGameArea to Region(0, 0, 2560, 1440)

**Comment by reconman** [comment]
Hold on. Did you activate debug_mode yourself? Are you aware that debug_mode just highlights 4 regions in an endless loop and doesn't start the battle?

**Comment by AlfredPaguio** [comment]
Oh sht , yes  ahahhahaha

**Comment by reconman** [comment]
![](https://user-images.githubusercontent.com/12360257/79977046-e9796380-849d-11ea-90b3-8e12ae8eb593.png)

**Comment by AlfredPaguio** [comment]
Sorry I didn't saw the new documentation sorry for wasting your time Tehee~

**Comment by AlfredPaguio** [comment]
Problem is solved thank you aaaahahahahhaah

**Comment by reconman** [comment]
No problem, it went a lot faster after I spent 3 hours debugging gameArea issues with other users.

The debug_mode is not what it should be, in my opinion. It slipped through a merge request and now it's part of the code.

It would be easier if debug_mode just highlights all regions before doing something with them.

**Comment by AlfredPaguio** [comment]
I see , anyways  thank you again for your time gonna close the issue now
