### ISSUE TITLE
Storyskip not working

### ISSUE THREAD

**Issue by Eldiaz7** [29988122/Fate-Grand-Order_Lua#358]
I just redownload the newest script
The function like choose card, auto battle, skip result etc working without error, but when it come to the story, when the skip button come theres nothing happen like clicking randomly on the screen, its like the storyskip feature not working or maybe is just happen in my phone
So i just want to ask any advice for this problem

Im already change the story skip from 0 to 1
My phone is Redmi note 7

Sorry for my bad English

**Comment by Eldiaz7** [comment]
Already solve my problem xD

**Comment by reconman** [comment]
How did you solve it?

**Comment by Eldiaz7** [comment]
> How did you solve it?

In my phone there's an app game booster
This app will automatically auto play when you playing game
And when playing game theres a hidden button in left screen 
When i active ankulua to try the skipstory is active or not
Those button always blinking non stop, so i think the script found that hidden button is same as button skipstory
So i try to turn of the game booster feature and try again
And everything work fine
