### ISSUE TITLE
Game not reconizing craft essence

### ISSUE THREAD

**Issue by chins4tw** [29988122/Fate-Grand-Order_Lua#360]
So I tried to make a new picture for a craft essence that isn't part of the default available using the guide in the wiki, and followed all the instructions. But when I use the code below for the picture I have linked even though there are both normal and MLB versions on a Waver it just scrolls down endlessly. is there something wrong with my Crop? I have tried smaller crops without the Ticket picture on the bottom cutting in and it still can't find the CE.

Name = "Event Expert",
		Skill_Command = "acd1efg6,#,h6,#,k14",
		Support_SelectionMode = "preferred",
		Support_PreferredServants = "waver1.png, waver2.png, waver3.png, waver4.png",
		Support_PreferredCEs = "The_Classic_Three_Great_heroes.png"

![The_Classic_Three_Great_heroes](https://user-images.githubusercontent.com/63263323/79051330-9c73d280-7bfd-11ea-8a8c-f53f7366c81e.png)

**Comment by reconman** [comment]
1. Someone already made a Pull Request for three great heroes, which was merged by me.
2. Your image seems to be a smaller scale than the one in this repository. How did you extract the CE image exactly?

**Comment by chins4tw** [comment]
>     2. Your image seems to be a smaller scale than the one in this repository. How did you extract the CE image exactly?

I took a screen shot on my tablet, moved the picture to my computer, Went onto https://resizeimage.net/ Uploaded my screenshot, went to step 4 and turned the 3rd ratio box to 720px(The default other PXs after doing this was 47%-960x720), switched output image format to PNG left default compression on then did "resize image" button. I then downloaded the new picture and croped out the picture in my first post in Paint.

**Comment by reconman** [comment]
Okay, I know what went wrong. Your tablet has blue bars at the top and bottom, not on the left and right like on a phone screen.

If the blue bars are at the top and bottom, you need to resize to have a **width** of 1280 pixels. If they're on the left and right, resize to a **height** of 720 pixels.

**Comment by reconman** [comment]
Notice: my rule about choosing a width of 1280 is only valid if you don't have a notch or navigation bar. Otherwise I would need to seen a screenshot of your whole screen to tell you the exact values.

**Comment by chins4tw** [comment]
> If the blue bars are at the top and bottom, you need to resize to have a **width** of 1280 pixels. If they're on the left and right, resize to a **height** of 720 pixels.


I just made a new picture and cropped out the Craft essence after making sure the second box was 1280px and the program now works. Thank you for your help.

![The_Classic_Three_Great_heroes](https://user-images.githubusercontent.com/63263323/79052552-53c01780-7c05-11ea-990f-eba16531c4f8.png)
