### ISSUE TITLE
The option "first" for the AutoSupportSelection selection doesnt work.

### ISSUE THREAD

**Issue by duradara** [29988122/Fate-Grand-Order_Lua#365]
The option "first" doesn't work, it gives me this error:
![1](https://user-images.githubusercontent.com/50158352/79522642-997c4600-8032-11ea-9404-25398aefdfcf.jpg)

The "prefered" options works perfectly.

This is the configuration I am using.

Support_SelectionMode = "first"
Support_SwipesPerUpdate = 1
Support_MaxUpdates = 1
Support_FallbackTo = "preferred"
Support_FriendsOnly = 1
Support_FriendNames = ""
Support_PreferredServants = "waver4.png, waver3.png, waver2.png, waver1.png"
Support_PreferredCEs = "any"

Am I doing something wrong?  

Sorry if my english is bad.

**Comment by reconman** [comment]
You're not using the current version, probably: https://github.com/29988122/Fate-Grand-Order_Lua/issues/340#issuecomment-597357550

Also you made me notice some weird logic, in the "first" code, so thanks for that.

**Comment by duradara** [comment]
> You're not using the current version, probably: [#340 (comment)](https://github.com/29988122/Fate-Grand-Order_Lua/issues/340#issuecomment-597357550)
> 
> Also you made me notice some weird logic, in the "first" code, so thanks for that.

Do I just download the master.zip from release and copy the content into my current folder? Because it says the last update was in jan of 2019. Sorry if this is a stupid question I am new to github

**Comment by reconman** [comment]
Not from release, from the `Clone and Download` button at https://github.com/29988122/Fate-Grand-Order_Lua

**Comment by duradara** [comment]
Thx it works now.

**Comment by reconman** [comment]
Actually, the link in Release is the same as the one in `Clone and Download`.
