### ISSUE TITLE
CE and Servant Support Images

### ISSUE THREAD

**Issue by ParadoxKiwi** [29988122/Fate-Grand-Order_Lua#366]
Thank you for your work! this code saved us a shit ton of time and effort. I used _support_img_maker.lua to get images of some servants and CEs I needed and thought other people might need them too. If this is out of place or unneeded feel free to ignore. I also tried to follow your naming scheme too and made sure all of them work on JP (1260x720). I hope this the section where I upload this, this my first time using Github.

[support_suggestions.zip](https://github.com/29988122/Fate-Grand-Order_Lua/files/4506953/support_suggestions.zip)

**Comment by reconman** [comment]
It would be best if you can just create a Pull Request, which involves these steps:
1. Fork the repository using the `Fork` button
2. Upload the images to the image_support folder in your fork
3. Create a Pull Request for merging your fork changes into this project

That would make our lifes much easier.

**Comment by potchy** [comment]
Adding to what @reconman said, we could do it ourselves, but I'm sure it would be handy for you to learn how to contribute to GitHub projects. We could help you if you're still unsure of how.

**Comment by ParadoxKiwi** [comment]
Thank you guys for showing it to me! I have made a pull request. I hope I did right :)

**Comment by reconman** [comment]
Yes you did
