### ISSUE TITLE
Can we get an option to prioritze Effective cards in chains?

### ISSUE THREAD

**Issue by MrTroika** [29988122/Fate-Grand-Order_Lua#369]
Basically for when you are running a mixed team of Servants and need to apply some extra card damage to finish off an enemy, but would prefer to have it come from a specific class of Servant (eg a Rider beating on a Caster). 

I figure this shouldn't be hugely hard to do since the word Effective is shown on the appropriate cards so the script can see it.

**Comment by reconman** [comment]
Already implemented, see https://29988122.github.io/Fate-Grand-Order_Lua/#/features?id=card-priority-customization
