### ISSUE TITLE
Script sometimes selects Saint Quartz to refill instead of Gold Apples

### ISSUE THREAD

**Issue by weiliang321** [29988122/Fate-Grand-Order_Lua#372]
Today I was watching my script run and when I ran out of AP, I had the scare of my life when the script decided to select Saint Quartz to refill it. Luckily, I was there to intervene, but if I had not been there, the script would have already used SQ. Does anyone know why this is happening? I had already set the refill_resource variable to Gold but for some reason it selects SQ sometimes (I say sometimes, because some other times it selects the correct resource). I did not touch the screen in any way when the script was running, so there shouldn't have been an issue.

**Comment by reconman** [comment]
I just put in a fix for that. I discovered the bug a few days ago. It seems to want to start a quest and clicks on the SQ refill option instead.

There is no other explanation.

Also, if the refill window is already opened, the script won't try to refill with SQ anymore.

Please update your game.lua file with my bugfix.
