### ISSUE TITLE
Support selection "first" doesn't seem to work on Nox

### ISSUE THREAD

**Issue by SMoumen** [29988122/Fate-Grand-Order_Lua#373]
Hello, I just downloaded your script, and it seems that it is looping the support selection state.
It justs scroll down and refresh, on repeat

**Comment by reconman** [comment]
What device are you using? Did you change anything regarding autoGameArea or immersiveMode?

**Comment by reconman** [comment]
Also what's your game region?

**Comment by SMoumen** [comment]
i'm using NOX emulator, i'm playing on JP

**Comment by SMoumen** [comment]
Also it doesn't seem to get past the victory screen, once the fight is ended, the script doesnt tap to loop through another encounter

**Comment by reconman** [comment]
Have you set the gameRegion configuration parameter to JP?

In which mode are you running Ankulua? The script only works with clicking and screenshotting using the `root` mode.

**Comment by SMoumen** [comment]
Yes it is set to JP
The battle part works just fine though. How do I check the mode?

**Comment by reconman** [comment]
Open Ankulua, click on ... in the top right, choose Settings.

There's a part called `Operation Settings` where the screenshot and touch methods are listed.

**Comment by reconman** [comment]
Hmm, but your sentence of "the battle part works just fine" indicates that Ankulua should be configured correctly.

I currently have no idea on what could be wrong.

**Comment by SMoumen** [comment]
nvm found the issue, was a typo in the .lua, sorry
