### ISSUE TITLE
Help auto GUDAGUDA Final Honnōji 2019 Re-Run

### ISSUE THREAD

**Issue by llvllr30** [29988122/Fate-Grand-Order_Lua#377]
wanting to ask that can  u add auto click for reward screen in gudaguda event
i also set isevent = 1 but it not worked for me
![image](https://user-images.githubusercontent.com/40718759/81170833-8cb19900-8fc5-11ea-9c6a-40ac096f1069.png)

**Comment by 29988122** [comment]
Dirty fix.
Replace this file for now. 
Restore the file when the event's over.
[regular.zip](https://github.com/29988122/Fate-Grand-Order_Lua/files/4609293/regular.zip)

**Comment by llvllr30** [comment]
> Dirty fix.
> Replace this file for now.
> Restore the file when the event's over.
> [regular.zip](https://github.com/29988122/Fate-Grand-Order_Lua/files/4609293/regular.zip)

tks it work perfectly now
