### ISSUE TITLE
Can't find path specified

### ISSUE THREAD

**Issue by pokecrater1** [29988122/Fate-Grand-Order_Lua#38]
When I go to install via the run.bat, a cmd window pops up with this message. I thought it was a folder permission problem but I am not able to change it. I checked the bat file to see if the file paths are correct, and redownloaded the the Fate_Grand_Order__Lua. None of it seems to fix the problem of running the run.bat file. I tried downloading a daemon off of another place and running its .bat and experienced the same message "Can't find path specified". Was wondering if anyone else has had a similar issue or if you have an idea on what to do.

**Comment by 29988122** [comment]
www.dropbox.com/s/04sncdwv4ufpbzz/ama_daemon_zh.v1.7.1.zip?dl=1

Try this? 

"Please keep the file/folder structure intact"

**Comment by pokecrater1** [comment]
I still have the issue. I haven't changed the file folder structure (Fate-Grand-Order_Lua \ama_daemon folder). My usb debugging mode is on, I tried moving the folders (of the Lua\ama_daemon) to different directories in my phone to run the .bat in each scenario but there was no change whatsoever. It might be an issue exclusive to my phone.

**Comment by pokecrater1** [comment]
I am executing the daemon from my PC. I don't think I can do it from my phone in the first place. Your instructions seem clear on the manual. It's not your fault.
