### ISSUE TITLE
How to add more settings in autoskills_list

### ISSUE THREAD

**Issue by hayate1412** [29988122/Fate-Grand-Order_Lua#384]
I have many different entries but there are only 3 settings. It takes too much efford to replace entry witht he new one in the setting.

**Comment by reconman** [comment]
Please reformulate your question. What "3 settings" are you talking about? Why are you replacing entries? Why is it too much effort to create a new entry?

**Comment by hayate1412** [comment]
Sorry for my english
![Uploading autoskills list.png.jpg…]()

Before, we have 10 entries, 1 to 10. Now we only have 3, qp,dust and gear. 
Cause i have to replace skill command for 6 different farming quests so it take a lot of efford.

**Comment by hayate1412** [comment]
![autoskills list png](https://user-images.githubusercontent.com/59958509/83341101-da01fb80-a322-11ea-97b8-b63d6ec20ee0.jpg)

**Comment by reconman** [comment]
You misunderstood, you can add unlimited entries!

For example,
```
Autoskill_List =
{
	{
		Name = "QP",
		Support_PreferredCEs = MonaLisa,
		Skill_Command = "a2b2dfi25,#,5,#,5"
	},
	{
		Name = "Feathers",
		Support_PreferredCEs = Lunchtime,
		Support_PreferredServants = Waver,
		Skill_Command = "0,#,hia5,#,g2cbdft245"
	},
	{
		Name = "Hearts",
		Support_PreferredCEs = Lunchtime,
		Support_PreferredServants = Waver,
		Skill_Command = "bd4,#,ag1hi4,#,fec2k25"
	},
	{
		Name = "EXP",
		Support_PreferredCEs = Lunchtime,
		Support_PreferredServants = Merlin,
		Skill_Command = "ci14,#,gd5,#,b4"
	},
	{
		Name = "Ice ball",
		Support_PreferredCEs = Lunchtime,
		Support_PreferredServants = Merlin,
		Skill_Command = "dg5,#,e5,#,i1abc1k14"
	}
	{
		Name = "Bullet",
		Support_PreferredCEs = Lunchtime,
		Support_PreferredServants = Merlin,
		Skill_Command = "c4,#,cdg4,#,i2fk25"
	}
}
```

**Comment by hayate1412** [comment]
Oh. I will try it now. 
Thanks a lot for your reply.
