### ISSUE TITLE
Can't launch the game after starting a script

### ISSUE THREAD

**Issue by Aghandor** [29988122/Fate-Grand-Order_Lua#389]
After I start the app AnkuLua and runned one of the 2 scripts (SnapAndPlay and RecordAndPlay), the Game simply cannot be launched any more, it either close instantly or close instantly and open my mailing application so that I can contact the support.

**Comment by Aghandor** [comment]
I turned off the script and the game works fine now, but the script does not seem to be working

**Comment by reconman** [comment]
Why are you using SnapAndPlay and RecordAndPlay? Did you ever try again?

**Comment by Aghandor** [comment]
I tried again using the other scripts but it was still not working, so I settled for another script
