### ISSUE TITLE
Problem in AutoSkill

### ISSUE THREAD

**Issue by sliverlin** [29988122/Fate-Grand-Order_Lua#39]
Hello!
I have some problem on the autoskill function, my 3rd servant won't activate skill2 in battle 3 but only Ult.
This is my setting for skillcommand
Enable_Autoskill = 1
Skill_Confirmation = 0
Skill_Command = "i6,#,bc5,#,h6"

p.s I'm using "Stella!!!" in battle 1, and then the next servant comes out, not sure if it is related to this.

**Comment by sliverlin** [comment]
I found that it is not related to the stella ult, I changed my servant order and 3rd servant still wont activate skill in battle.

**Comment by 29988122** [comment]
Did you update the script to the latest version? Since there's some stage recognition issue, I've modified quite a bit.

Then please check the toast message(battle1, battle2, battle3, which showed on the screen) to identify if the issue's stage recognition related.

**Comment by sliverlin** [comment]
I am using the lastest version, but I didn't see toast message for battle recognition. 
Btw, the current behavior in battle 3 is :
1. switch to priority target
2. click attack
3. click all ult (but only 6 is activatable in my situation)
4. click the rest two cards for attack

**Comment by 29988122** [comment]
The latest version *should* show messages such as "Battle 1/3" every round before enter card selection.
Please make sure you replaced all the files https://github.com/29988122/Fate-Grand-Order_Lua/archive/1.8.3.zip
in your phone.

Because I also modified FGO_JP/TW/EN/CN_REGULAR.lua, please also check that file if you didn't update it before.

The toast message code:
```
function checkStageCount(region)
	--Alternative fix for different font of stage count number among regions
	local s = region:exists("_GeneratedStagecountSnapshot.png")

	if s ~= nil then
		toast("Battle "..checkStageCountStage.."/3")
		return checkStageCountStage
	end
	
	if s == nil then
		StageCountRegion:save("_GeneratedStagecountSnapshot.png")
		checkStageCountStage = checkStageCountStage + 1
		toast("Battle "..checkStageCountStage.."/3")
		return checkStageCountStage
	end
end
```

**Comment by sliverlin** [comment]
I have updated the script and now theres battle 1/3, battle 2/3, and battle 2/3 again in battle3
seems like theres some issue on the stage recognition

**Comment by 29988122** [comment]
Please check your image folder inside phone(image_jp, image_tw, depends on your server), and upload _GeneratedStagecountSnapshot.png here, I'll see where the problem is.

**Comment by sliverlin** [comment]
hmm...I dont have this image in my phone(tw server)
seems like this is the reason why stagecount doesnt work.

**Comment by 29988122** [comment]
那就奇怪了..因為如果沒有截圖/比較功能那script應該連運作都不行才是

我猜猜，小米/華為/oppo手機？

**Comment by sliverlin** [comment]
是小米手機沒錯(小米6)
挺奇怪的...另外寫了一個只有save函數的測試腳本一樣都不會截圖

**Comment by 29988122** [comment]
1.更新一下ankulua, 確定有沒有是最新版
2.去ankulua裡面的設定更改截圖方法，應該有daemon, media projection, 還有一些其他的方法, 排列組合試試
3.來這邊找一下 http://ankulua-tw.boards.net/board/1/
關鍵字小米，看有沒有人遇過類似的問題
因為小米手機的權限控管比較特別，可能要開特殊的選項，然後那個選項不是很好找...

4.以上方法都沒有用，在ankulua board註冊帳號，直接問框架的維護者
因為我沒有辦法跟android底層互動，那個相容性是ankulua團隊維護的..XD

**Comment by sliverlin** [comment]
root和media projection都試了不行
奇怪的是現在才發現手機的檔案管理程式可以看到圖檔但是接電腦看不見
且battle3仍然顯示battle 2/3
圖檔也是2的
[https://drive.google.com/open?id=1Q4GCJyKVcd6q60YbA1NUjiPQ1jeNkeiL](url)
有在截圖且battle2技能施放是正確，感覺有正常運作
我試試看調整一下圖片比對的相似度好了!

**Comment by sliverlin** [comment]
比對範圍微調&相似度調到0.9之後可以正常運行battle3了!
StageCountRegion = Region(1710,25,55,60)

local s = region:exists(Pattern("GeneratedStagecountSnapshot.png"):similar(0.9))

話說2和3有這麼像嗎XD
感謝你的幫忙~

**Comment by 29988122** [comment]
臺版居然連數字放置位置都跟日版不同...= = 不愧是王董
(bilibili版目前的改版好像是可以正常使用的)

感謝你的測試，我來修正相關的座標.....

**Comment by aqer** [comment]
目前的code只修正了座標卻沒有加相似度那行,台版仍會把stage3判斷成stage2,加了後就正常

**Comment by 29988122** [comment]
哎呀我是笨蛋

一開始因為沒有臺版可以測試，想說先放著，因為我腦弱了，原本想說"奇怪sikuli框架預設相似應該是0.7啊，往上改有什麼用"

今天看到你的回應想一想才發現這邊的邏輯相反，不是因為抓不到畫面所以要改低，而是因為程式把有變化當成沒變化所以要改高.....
=
我先在本地(我玩日版)多測幾次不同的關卡背景看看0.9會不會造成反過來的行為，某些關卡變化了而抓不到之類的，沒問題再送。不然應該要用個0.8防止極端狀況像是背景都是黑的#255,255,255之類的...

**Comment by aqer** [comment]
順便問一下 日版現在還可以用? 我的手機升級android 8後關掉USB偵錯後就不能跑ankulua了,但開著USB偵錯卻又無法打開FGO日版...

**Comment by 29988122** [comment]
我也是android 8，是正常的，htc 10 stock firmware，裝daemon->關偵錯->開遊戲
我有用magisk啦，不過我覺得可能沒什麼關係...

大概是不同的rom有不同的safety measure，你可能要
1.自己摸索一下選項
2.或是乾脆裝magisk用root不要用daemon
3.去Ankulua那邊問一下支援狀況，讓他們處理
4.乖乖用emu跑..reddit有人寫全套的tutorial XD 
https://www.reddit.com/r/grandorder/comments/573lek/how_to_play_on_pc/

總之還是感謝你幫其他臺版玩家謀福利修bug！
之前有一次測四個版本弄了快一個禮拜，以後我就決定只維護日版了，太多細節會影響script 囧rz

**Comment by aqer** [comment]
感謝回覆, 其他android 8可以用的話那應該是ASUS的ROM檔的吧
等之後換別家手機後再試試日版可不可以用了
台版倒是沒有這個問題~
