### ISSUE TITLE
How to update safely?

### ISSUE THREAD

**Issue by Orpheus25** [29988122/Fate-Grand-Order_Lua#391]
Hi,

Sorry if this is the wrong place. I'm using this script with an old version and i think it's time i update it. But i'm not sure how i should go about it, i'm afraid of breaking something. Do i just remove the old files and replace them with the new? Or are there extra steps like rebooting the phone before to remove the daemon and reapply the one from the new files afterwards?

Thanks a lot for your help

**Comment by arft1kwerg** [comment]
If you have any farming set-ups in the old regular folder that you wish to save, copy them into a notepad. It's usually simpler to remove all the old files and then drop the new ones in. Rebooting and daemon depends on the android version as newer ones just need to enable permissions for ankulua.

**Comment by Orpheus25** [comment]
I did it how you said and everything went really well, thank you very much!
