### ISSUE TITLE
NA: Close or repeat request

### ISSUE THREAD

**Issue by KaitoKid** [29988122/Fate-Grand-Order_Lua#392]
Could someone update the NA script to handle the new logic for free quests?

![image](https://user-images.githubusercontent.com/9055441/85397843-22b76980-b509-11ea-867b-0f3706dae92e.png)

**Comment by MathewSachin** [comment]
Can you post a screenshot of that screen. I think most people including me would be doing story today.
I can get it cropped and make the relevant change in code of you're willing to test.

**Comment by potchy** [comment]
The code was already written. You just need to update `confirm.png` and remove `GameRegion == "JP" and `.

https://github.com/29988122/Fate-Grand-Order_Lua/blob/14cad1c1ef272660c2485132dc73cdecbd1e4574/regular.lua#L160

**Comment by reconman** [comment]
But we don't have CN or TW images.

**Comment by MathewSachin** [comment]
Yeah. I know. It's just that I don't want to use my AP on free quests right now. Story takes a lot of AP.

**Comment by MathewSachin** [comment]
I cropped from the image @reconman gave me:
<img width="74" alt="confirm" src="https://user-images.githubusercontent.com/10654537/85410831-30aad000-b585-11ea-8555-d9115fef3436.png">

**Disclaimer:** haven't tested this yet
Can anyone check if this works? I really want to use my AP on story 😢

**Comment by Justtaway** [comment]
I did like @potchy said and edited regular.lua to this:
![WdTSEu1XHU](https://user-images.githubusercontent.com/9951646/85416434-21bd2100-b577-11ea-942a-01a03e86cc35.png)
Tried with @MathewSachin image and made my own — results are the same, it just stops at the screen with Repeat button. Maybe I'm doing something wrong, idk, but for not it's not working

**Comment by Tenken77777** [comment]
MathewSachin's picture works, make sure to rename confirm.png so that the folder only shows "confirm" and not "confirm.png" because the "png" is automatically generated

**Comment by Justtaway** [comment]
> folder only shows "confirm" and not "confirm.png" 
You mean not naming file confirm.png.png? It's already that way. 
![T8qcQISAKi](https://user-images.githubusercontent.com/9951646/85469823-d32f7700-b5b6-11ea-83c1-b8ca91e79c34.png)

**Comment by forgehe** [comment]
Can also confirm that the same changes works fine.  
Removed `GameRegion == "JP" and ` and added @MathewSachin 's confirm.png to image_EN folder, and after a short delay, it clicked the button.  
Further modifying line 160 to 
`if (GameRegion == "JP" or GameRegion == "EN") and game.CONTINUE_REGION:exists(GeneralImagePath .. "confirm.png") then` also works. I guess we can remove the GameRegion check once we get images for the other servers.  

However, I did just run into an issue that said "This quest period is over", since the daily quests just reset, and I stupidly didn't screenshot it, or see if it would get stuck there.

**Comment by Tenken77777** [comment]
> 
> 
> > folder only shows "confirm" and not "confirm.png"
> 
> You mean not naming file confirm.png.png? It's already that way.
> ![T8qcQISAKi](https://user-images.githubusercontent.com/9951646/85469823-d32f7700-b5b6-11ea-83c1-b8ca91e79c34.png)

Yes the program only looks for "confirm.png" and not "confirm.png.png" , the icon provided already has the png extension as default, so rename it to just "confirm"

**Comment by Justtaway** [comment]
> the icon provided already has the png extension as default, so rename it to just "confirm"

Of course I know it, I just have extensions enabled in explorer.
Maybe there is something wrong with my script for farming? Or heck, maybe even AnkuLua version? I have Ankulua 8.3.0, since it's the latest modded pro version.

**Comment by MathewSachin** [comment]
> if (GameRegion == "JP" or GameRegion == "EN") and game.CONTINUE_REGION:exists(GeneralImagePath .. "confirm.png") then

I think this should be good. Would you mind putting up a Pull request? I don't mind if you use my image.

**Comment by Justtaway** [comment]
Tried with last 8.7.0 version — still doesn't work.
Here's my script. and in regular.lua only one line (160) is different:
`if (GameRegion == "JP" or GameRegion == "EN") and game.CONTINUE_REGION:exists(GeneralImagePath .. "confirm.png") then`
[_dust_farm.txt](https://github.com/29988122/Fate-Grand-Order_Lua/files/4827571/_dust_farm.txt)

**Comment by reconman** [comment]
@Justtaway I can see that your script is a few months outdated, you should update your scripts. For example, you can configure multiple parties, each with a different support servant, CE, and SkillCommand.

**Comment by Justtaway** [comment]
@reconman I used updated FGO_regular script, but I get no window to select autoskill set, only empty message like this:
![PaUbpFJx18](https://user-images.githubusercontent.com/9951646/85625216-c0c74300-b673-11ea-8973-091bed82df9e.png)

[FGO_REGULAR.txt](https://github.com/29988122/Fate-Grand-Order_Lua/files/4827799/FGO_REGULAR.txt)

**Comment by reconman** [comment]
@Justtaway I haven't seen this behavior before, and when I run your script it displays the 3 party teams normally. Did you replace all the  .lua files with the versions from Github?

**Comment by Justtaway** [comment]
@reconman it was too stupid — files in Bluestacks were never synced with windows.
Since, somehoew, Ankulua doesn't see shared folder from windows, I just moved all files to internal storage. And, as you can guess. all my updates to scripts or files in windows didn't even make it to Bluestacks...
God, I feel absolutely stupid.
Tried running script now — works perfectly fine (after I forgot like 5 things and debuged them by running script and seeing continue button not being pressed)
