### ISSUE TITLE
Caution keeps appearing

### ISSUE THREAD

**Issue by Cebeus** [29988122/Fate-Grand-Order_Lua#394]
I've just updated all the files by replacing the files I had currently with the ones fresh from github. Whenever I try running the program, it just gives me a caution sign and after I hit OK, it randomly clicks places.

![image](https://user-images.githubusercontent.com/59350808/85666233-0d5d4f00-b671-11ea-9ad9-25eaadc0ead3.png)

Here is my fgo script
[FGO_REGULAR.txt](https://github.com/29988122/Fate-Grand-Order_Lua/files/4829357/FGO_REGULAR.txt)

I play on a nox emulator with ankulua v8.6.0 and I made sure to move the new files to the designated ankulua spot from the picture folder.

![image](https://user-images.githubusercontent.com/59350808/85666146-f6b6f800-b670-11ea-9dea-06beb58d65ac.png)

I've tried everything I could think of but I've hit a dead end. Does anyone have a solution?

**Comment by reconman** [comment]
See https://github.com/29988122/Fate-Grand-Order_Lua/issues/392#issuecomment-649103540

**Comment by Cebeus** [comment]
I've seen that too but what does it mean when bluestacks didn't sync with window. What do I need to do in order to sync it?

**Comment by forgehe** [comment]
Enable_Autoskill is set to 0 instead of 1

**Comment by Cebeus** [comment]
That... solved it. Thank you so much, I was totally looking at it the wrong way.

**Comment by Cebeus** [comment]
I think another problem may have cropped up. I can run everything but the friend selection fine and it hits the repeat button ok. However, when I go to the support screen it gives me this.

![image](https://user-images.githubusercontent.com/59350808/85676893-dfc9d300-b67b-11ea-97cc-a9331109f556.png)

I'm a bit tired trying to solve, I'll give it a shot in the morning.

**Comment by forgehe** [comment]
Going through your FGO_REGULAR file more carefully, your default support servants has an extra comma between the merlins.

`Support_PreferredServants = "waver4.png, waver3.png, waver2.png, waver1.png, merlin4.png, ,merlin23.png"`

Additionally, when you're writing the autoskills, you dont specify the preferred if you want to use default values. Just leave it blank and it will use the default values.

So from:
```
Autoskill_List =
{
	{
		Name = "Salem Underground house",
		Skill_Command = "c4,#,g6,#,hdefbk254",
		Support_SelectionMode = "preferred",
		Support_PreferredServants = "preferred",
		Support_PreferredCEs = "*preferred"
	},
	{
		Name = "Dust",
		Skill_Command = "bc4,#,def5,#,ghk36",
		Support_SelectionMode = "preferred",
		Support_PreferredServants = "preferred"
	},
	{
		Name = "aurora steel ice and fire",
		Skill_Command = "6,#,h6,#,bx31fed1gj46",
		Support_SelectionMode = "preferred"
	}
}
```

to 

```
Autoskill_List =
{
	{
		Name = "Salem Underground house",
		Skill_Command = "c4,#,g6,#,hdefbk254"
	},
	{
		Name = "Dust",
		Skill_Command = "bc4,#,def5,#,ghk36"
	},
	{
		Name = "aurora steel ice and fire",
		Skill_Command = "6,#,h6,#,bx31fed1gj46"
	}
}
```

**Comment by Cebeus** [comment]
Sorry for the late reply, I went to sleep because I was rather exhausted last night.

I noticed and fixed the extra comma right before I went to sleep last night as the extra comma messed up my friend selection with an error warning. Thanks a lot for all the help. I've been using the outdated version, so I was really just going through this blindly.

**Comment by reconman** [comment]
I've added a notice for AutoSkill=0 in e391880d70d6c499427ad73570b440d960abaf90
