### ISSUE TITLE
Resolution problem

### ISSUE THREAD

**Issue by sliverlin** [29988122/Fate-Grand-Order_Lua#40]
你好我又來惹
這兩天換了新手機但是是18:9的解析度(2160x1080)
開啟FGO會出現左右的藍條，應該是這個緣故導致座標都亂了，腳本無法作用
想請問有沒有什麼方式可以校正
(目前我試了把腳本內所有起始X座標+120和按照2560&1920的比例+160都沒用)

![screenshot_2018-05-23-17-07-22-912_com komoe fgomycard](https://user-images.githubusercontent.com/39355740/40418153-2b90f8da-5eb4-11e8-9a8e-0a0c3343b033.png)

**Comment by 29988122** [comment]
請參照
https://github.com/29988122/Fate-Grand-Order_Lua/issues/33
Ankulua沒有處理的情況下，我真的不太好改

目前我的解法是請你用這個啦 XD
https://www.reddit.com/r/grandorder/comments/573lek/how_to_play_on_pc/

**Comment by ryuga93** [comment]
Hi, maybe you can try to open the script with an IDE that can do refractoring or use Notepad++ to rename all the Region() and Location()

Write wrapper functions for Region and Location with the conversion and rename every instance with one click.

**Comment by 29988122** [comment]
We call that rewrite / refactor, right? I have to admit that currently I don't have a good coding style, so I'm afraid that any tweak of the script will break it and took too much hard effort to fix.

==
The function scriptdimension and comparedimension that Ankulua framework implemented caused this behavior. I checked the LineageM script written by Ankulua Dev, and frankly the solution seemed more complicated that what I've originally thought. We also have no idea whether they'll change the behavior about aspect ratio support or not, so I choose to wait.

**Comment by 29988122** [comment]
真虧你想得到這種特殊解.....不過18:9的手機不只有一隻，什麼s8s9小米zf5之類的，一卡車

為了日後寫程式的相容性我還是只能等Ankulua官方做處理，特別寫例外狀況會很坑 囧


總之恭喜你找到解！ XD

**Comment by ryuga93** [comment]
I would say it's the laziness of game dev to support 18:9 that caused this problem XD

**Comment by pokeguys** [comment]
Using OpenCV can easily fix this issue. But it required an external API server to process and communicate between the PC and App due to Ankulua doesn't provide any OpenCV function in Lua. 🤦‍♂️ If you need this feature, I can create a PR (I am not quite sure it is 100% work. I don't have any device > 16:9 resolution)

## Result
![image](https://user-images.githubusercontent.com/5060799/47259973-0ae24380-d4e5-11e8-9772-11f46bf55e0a.png)

**Comment by 29988122** [comment]
I'm currently doing my graduation thesis, not really available at the moment.

I guess @potchy has something to say about API / bandwidth issue?

**Comment by pokeguys** [comment]
I think it can be implemented in the lua by "hacking" some Ankulua functions. But I don't think they will allow us to keep using that secret method 😞

I agree there might be some bandwidth issue depends on how the API server setup. But for the details, I will open a new issues about the API solution in a few weeks later. kind of busy right now 😖

**Comment by gn01791992** [comment]
恩..看到這篇想請教一下，因為我換的手機是小米POCO F1  系統是安卓9
解析度是更奇怪的2,248 x 1,080，且由於 AnkuLua目前無法在安卓8以上很好的已daemon後關閉USB偵錯情況下運作，然後我有去官方論壇詢問，他們答覆目前可以使用協助工具(無障礙)服務運作。

實際操作腳本後確認到抽禮物箱是沒問題，但戰鬥腳本不會進行運作，所以我猜測是否因為解析度怪異導致抓取不到圖示以至於戰鬥腳本不進行運作。
想請教一下sliverlin是如何修改腳本的(當然若可以分享你已改好的腳本使我去跟原腳本比較何處修改更好)。
又或由作者協助教學(不過這工作量有點大，最好還是如作者所說由Ankulua那邊進行改動)。

**Comment by potchy** [comment]
AnkuLua's author said it isn't possible (yet) to explicitly set the screen area in which the script will work on.
As such, it is infeasible for us to create a separate script for each possible resolution. [There is a workaround, though.](http://ankulua.boards.net/thread/1243/set-script-area)


1. Turn on USB debugging in your device.
2. Navigate to `\ama_daemon`.
3. Run `aspect_ratio_workaround.bat`. This will set your device resolution to 1280x720, so the script can work correctly.
4. When you're finished, run `aspect_ratio_reset.bat` to rollback changes.

Either do this or use **Nox** or **MEmu** in your PC.

**Comment by 29988122** [comment]
https://github.com/29988122/Fate-Grand-Order_Lua/issues/75
For image recognition info, check this thread instead. 

The resolution issue will be resolved by @TryBane in the near release.
