### ISSUE TITLE
Battle_AutoChooseTarget opens "Status Changes" window

### ISSUE THREAD

**Issue by migd513** [29988122/Fate-Grand-Order_Lua#400]
If Battle_AutoChooseTarget = 1 and the wave already has the strongest enemy selected (default rightmost enemy), the script will tap on the same enemy which opens the "Status Changes" buff/debuff prompt and stops the script.

This behavior can be seen in wave 2 of America: Charlotte.

Workaround: Set Battle_AutoChooseTarget = 0

**Comment by reconman** [comment]
I adjusted the click position to close the enemy info window. There was already code for exiting the window, but it didn't work reliably because the Y value was 0.
