### ISSUE TITLE
Custom Script for Summer Race

### ISSUE THREAD

**Issue by SilvaLau** [29988122/Fate-Grand-Order_Lua#402]
Can I get a custom script for the Dead Heat Summer Race rerun?

**Comment by reconman** [comment]
And what exactly should that custom script do that is not handled by the default one?

**Comment by SilvaLau** [comment]
hmm, I don't know, for selecting the boosters and such maybe? The documentation said "A custom script is required for summer racing events and Oni island events. Please ask in issue forum if you need this feature."

**Comment by reconman** [comment]
Nah, that's outdated. Just set this: https://github.com/29988122/Fate-Grand-Order_Lua/blob/2e5057b6c15d08c6e76f30e6e49b803917cf46c5/docs/features.md#boostitem_selectionmode

**Comment by SilvaLau** [comment]
On, thank you. Just for clarification though, can I put all the command inside the auto-skill list or should I put them outside of the list? Like the Battle Card Priority and other such things.

`--AutoSkill
Enable_Autoskill = 1
Skill_Confirmation = 1

Autoskill_List =
{
	{
		Name = "Quick",
		BoostItem_SelectionMode = "1"
		Battle_CardPriority = "WQ, WB, WA",
		Support_SelectionMode = "preferred",
		Support_PreferredServants = "nitocros4",
		Support_PreferredCEs = "sugar_vacation.png, chaldea_beach_volleyball.png, seaside_luxury.png"
	}
}

--Card Priority Customization
Battle_CardPriority = "BAQ"
--AutoChooseTarget
Battle_AutoChooseTarget = 1
--NoblePhantasm Casting
Battle_NoblePhantasm = "danger"`

**Comment by reconman** [comment]
Outside if it should be a global setting, inside if it should be setting only for that one AutoSkill setup.

**Comment by SilvaLau** [comment]
oh, so that means I have to create a new script file for every different scenario then?

**Comment by reconman** [comment]
What is "every different scenario"?

You can use 1 script for all scenarios if you put in a bunch of AutoSkill parties where each party overrides some global settings.

**Comment by SilvaLau** [comment]
well, I mean, what if I want to select a different boost item, or prioritize different cards based on the team? I can't do that in a single script right?

> Also your CardPriority inside the AutoSkill_List item is incomplete. Should be "WQ, WB, WA, Q, B, A, RQ, RB, RA".

oh, thanks

**Comment by reconman** [comment]
You can, just like in the part of the script you posted.

**Comment by SilvaLau** [comment]
oh wait, I can actually do that? sorry, I'm new to this...
