### ISSUE TITLE
How to set Party Selection?

### ISSUE THREAD

**Issue by SilvaLau** [29988122/Fate-Grand-Order_Lua#403]
I tried setting the script as written below but it didn't seem to be changing my party, am I doing something wrong?

Name = "Nobu Node",
Skill_Command = "",
Party_Number = "9",
BoostItem_SelectionMode = "1",
Battle_CardPriority = "WQ, WB, WA, Q, B, A, RQ, RB, RA",
Support_SelectionMode = "preferred",
Support_PreferredServants = "nitocris_assassin.png, scathach_assassin.png",
Support_PreferredCEs = "white_cruising.png, king_joker_jack.png, seaside_luxury.png"

**Comment by reconman** [comment]
Can you upload your whole file? Also you updated all your .lua files, right?

**Comment by SilvaLau** [comment]
> Can you upload your whole file? Also you updated all your .lua files, right?

"updated" all my .lua files? uhhhh

-- Can be EN, JP, CN or TW
GameRegion = "EN"

--Script Configuration, check instructions in the README and wiki: https://github.com/29988122/Fate-Grand-Order_Lua/wiki/Script-configuration-English
--***************************************************************************
--AutoRefill Stamina
Refill_Enabled = 0
Refill_Resource = "All Apples"
Refill_Repetitions = 0

--AutoSupportSelection Defaults
Support_SelectionMode = "first"
Support_SwipesPerUpdate = 5
Support_MaxUpdates = 3
Support_FallbackTo = "manual"
Support_FriendsOnly = 0
Support_FriendNames = ""
Support_PreferredServants = "waver4.png, waver3.png, waver2.png, waver1.png"
Support_PreferredCEs = "*chaldea_lunchtime.png"

--AutoSkill
Enable_Autoskill = 1
Skill_Confirmation = 1

Autoskill_List =
{
	{
		Name = "Nobu Node",
		Skill_Command = "",
		Party_Number = "9",
		BoostItem_SelectionMode = "1",
		Battle_CardPriority = "WQ, WB, WA, Q, B, A, RQ, RB, RA",
		Support_SelectionMode = "preferred",
		Support_PreferredServants = "nitocris_assassin.png, scathach_assassin.png",
		Support_PreferredCEs = "white_cruising.png, king_joker_jack.png, seaside_luxury.png"
	},
	{
		Name = "Raikou Node",
		Skill_Command = "",
		Party_Number = "4",
		BoostItem_SelectionMode = "3",
		Battle_CardPriority = "WB, WA, WQ, B, A, Q, RB, RA, RQ",
		Support_SelectionMode = "preferred",
		Support_PreferredServants = "Frankenstein_Saber.png, musashi.png",
		Support_PreferredCEs = "sugar_vacation.png, chaldea_beach_volleyball.png, seaside_luxury.png"
	}
}

--Card Priority Customization
Battle_CardPriority = "WB, WA, WQ, B, A, Q, RB, RA, RQ"
--AutoChooseTarget
Battle_AutoChooseTarget = 1
--NoblePhantasm Casting
Battle_NoblePhantasm = "danger"

-- set to 'true' if needing to debug
Debug_Mode = false
-- stop the script after retreiving a Bond 10 CE card
StopAfterBond10 = 0
-- Boost item, possible values: disabled, 1, 2 or 3. Make sure "Confirm Use of Boost Item" is off
BoostItem_SelectionMode = "disabled"
StorySkip = 1
--Auto Withdrawing
Withdraw_Enabled = false
--FastSkipDeadAnimation
UnstableFastSkipDeadAnimation = 0

-- Do not modify below this line
dir = scriptPath()
dofile(dir .. "middleware.lua")

**Comment by reconman** [comment]
I mean, did you update middleware.lua, regular.lua and all the files inside of modules?

**Comment by SilvaLau** [comment]
I just did, I wasn't aware of the update.
