### ISSUE TITLE
Wrong ankulua path

### ISSUE THREAD

**Issue by KaitoKid** [29988122/Fate-Grand-Order_Lua#408]
![image](https://user-images.githubusercontent.com/9055441/91021731-07b8b280-e5a9-11ea-943f-0692e5d38d56.png)

Seems like there's an extra `/` in the path. Running Ankulua 8.8 and the latest release of FGO Lua

**Comment by reconman** [comment]
The // should have no effect, at least I never had an error related to that. Does skadi_3.png exist in the directory /sdcard/Pictures/image_SUPPORT?

**Comment by KaitoKid** [comment]
@reconman Geez, I merged a local branch with the latest pull from remote master where some of the `skadi` files were missing, good catch.
