### ISSUE TITLE
"A thank you letter from user"

### ISSUE THREAD

**Issue by 29988122** [29988122/Fate-Grand-Order_Lua#41]
https://github.com/potchy/messages/issues/1
Thank you potchy, your message really motivates me. Glad you like it!

I just move it here so @ryuga93 would know that @potchy can also show his gratitude to you : )
ryuga93 wrote the autoskill part which is probably the most useful chunk of the script!

All hail ryuga93.
: p

potchy commented 8 minutes ago 
@29988122 Hey, this isn't an actual issue. I just want to thank you for your FGO script. The code is concise,  elegant and it's pretty easy to tweak it to my needs. It helped me a lot  with 2BP grinding in Rashoumon. Unfortunately, github lacks a private message feature, so I had to create an issue to notify you. lol

**Comment by ryuga93** [comment]
＠potchy @29988122 Thank you! To be honest I did not expect this. XD

**Comment by potchy** [comment]
hail ryuga93
lol

**Comment by Rajvir8** [comment]
I'd rather not make another issue for the same purpose, so I'll post here and hope your watching.

I'd just like to say thank you for sharing this on Github, I'm going to be busy with work later so I appreciate being able to use my stamina for something.

It's even better than the proper autobattle in Danmachi as I still have to actually confirm the mission is complete and select the next one.

**Comment by 29988122** [comment]
Thank you, I appreciated it very much.

By the way what do you mean by Danmachi? Which event is that?
You may be able to auto that if you enable is_event = 1 in your config file.

**Comment by Rajvir8** [comment]
I was comparing it to another Game Danmachi Memoria Freeze which has auto battle built in. it's compensated by the fact that buffs are very powerful in that game and auto battle won't use it.

I was happy to see the auto-battle here is just as smooth here where it is a unofficial mod, compared to Danmachi where it is an officially supported part of the game.

Thank you again for the script, I'm enjoying being able to grind for Master Levels efficiently.

**Comment by 29988122** [comment]
Oh, I get it now. Thank you for your words again!

Some small talk:
I were to put this script on a framework which worked for both ios and Android, better if it's free-of-charge. But, only until later that I found out there's no such framework existed. 

And even if we talked only Android, the better ones with good compatibility are all paid software. Although I get the idea - it's extremely time-consuming to maintain such a framework, dealing with multiple phones / OSes combination in the Android world.

I got my copy from promoting AnkuLua(via this repo, you get the idea), but it will definitely be better if everybody could use it.

**Comment by Rajvir8** [comment]
I can totally understand that, the cooldown is a bit annoying but a 13 minute cooldown for 30 minutes of auto progress isn't horrible.

But here's to hoping that a free framework is eventually devolved and worked on by a non-profit/volunteers,

People thought that a full browser that was as good as the main company's could never come from a not-for profit but FireFox showed up eventually.

**Comment by anubi** [comment]
The oreo update to Android might kill this project though. Unless a workaround is found out anyway.  As someone who just wants to farm bones and then uninstall this thing (I'm honestly paranoid DW will figure out how to identify users based on consistently of taps, which is stupid/crazy but totally something they would do to PAYING CUSTOMERS who will SUPPORT THE GAME WITH MONEY arghghgh)

**Comment by 29988122** [comment]
@anubi 
https://github.com/29988122/Fate-Grand-Order_Lua/issues/49
You can find my speculation about DW's stance of our small script here.

Yeah, people should really consider EMU as an option from now on. I might as well update readme.md.
I don't think Ankulua's author can by pass that without root - most of the regular ppl does not like root.(not me I will die without xposed lol)

Even if I can play the game with magisk - the author was kind enough, who even wrote an update to specifically circumvent FGO detection of root and magisk - it's still root needed, and you gotta unlock your bootloader.

By the way I like your metaphor of "tapper C&C-like machine", good ol' days.

**Comment by anubi** [comment]
I wish I was joking but I almost got the part list mailed: https://www.thingiverse.com/thing:123420

It would be a sight to behold.

**Comment by 29988122** [comment]
Holy shit....Well done, damn well done. 

Such a engineering feat(?), can't wait to see the result and video for FGO!
