### ISSUE TITLE
Script is not using skills on 3rd battle

### ISSUE THREAD

**Issue by machina2020** [29988122/Fate-Grand-Order_Lua#410]
I have been trying to figure out how to this work and managed to make it work today but now is not using skills on 3rd battle when it did work before and only use normal cards now.

This is part of the code I put to farm embers.

	{
		Name = "Ember",
		Skill_Command = "d1f1gh6,#,x31cg14,#,i14",
		Support_SelectionMode = "preferred",
		Support_PreferredServants = "skadi4.png, skadi3.png, skadi2.png, skadi1.png",
	}

**Comment by reconman** [comment]
See https://github.com/29988122/Fate-Grand-Order_Lua/issues/382#issuecomment-629859967
