### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by chins4tw** [29988122/Fate-Grand-Order_Lua#415]
I'm getting a syntax error when trying to use fgo_regular 

Syntax error: /sdcard/AnkuLua/Fate-Grand-order_Lua-master/FGO_REGULAR.lua:22:
unexpected symbol near '='

I'm assuming it means something is wrong with the 22nd line in fgo regular which is the party selection:party number line

It was originally 
Party_Number = nil

It failed to work like that so I changed it to Party_Number = 9 
which is the party I want to use but I still get the same error

please help

**Comment by reconman** [comment]
Can you upload your file to some website and share it?

**Comment by chins4tw** [comment]
> 
> 
> Can you upload your file to some website and share it?

https://www.dropbox.com/s/tz8mgdu63wyqlz9/FGO_REGULAR.lua?dl=0

**Comment by reconman** [comment]
You forgot something at line 19. The CE value is never assigned.
