### ISSUE TITLE
Cant repeat quest

### ISSUE THREAD

**Issue by haekal1002** [29988122/Fate-Grand-Order_Lua#417]
So i activated the script at the support menu, it chooses castoria, went to the battle, activated castoria's skills, fills up chen gong's np gauge, kill the enemy, yada yada everything went well. After the battle is finished i tried to select another or the same quest, the support menu comes up and i let the script do its job. It selects the servant and go to battle. But in the battle, instead of selecting castoria's skills, it selects attack cards and deviate from the autoskills script. 
Does anyone know why this happens? or is it a bug? I have to manually restart the script for it to become normal.

**Comment by reconman** [comment]
Why did you close the issue?
