### ISSUE TITLE
NP at the END of the chain?

### ISSUE THREAD

**Issue by miro3no** [29988122/Fate-Grand-Order_Lua#421]
Hello.
I am reading through instructions, but can not find info about it anywhere.
Is it possible to set NP after 2 basic card attacks? 
I currently have a setup, where I can realiably 3turn it, if anyone attacks the highest HP enemy before firing NP to get enough refund. Yet I do not know, if I can set it up like that through the script.
Thank you for the answer.

**Comment by reconman** [comment]
Look here: https://29988122.github.io/Fate-Grand-Order_Lua/#/features?id=attack-with-command-cards-before-nps
