### ISSUE TITLE
Sorry it cant work on me

### ISSUE THREAD

**Issue by brokenman222** [29988122/Fate-Grand-Order_Lua#43]
My phone is xiaomi note 4 i already follow the instruction until when it says for me to run the .bat on the pc 
It always sho the error "the system cannot find the path specified" please help me i already toggle the usb debugging on my phone
Thank you

**Comment by 29988122** [comment]
![default](https://user-images.githubusercontent.com/5474709/40869920-923952d6-6656-11e8-9f63-8792ba97e621.png)
Try enable these two options.

Xaiomi phones are especially strict on permission settings.
