### ISSUE TITLE
Warning against updating to Android 8.0 Oreo

### ISSUE THREAD

**Issue by TheIanator** [29988122/Fate-Grand-Order_Lua#45]
http://ankulua.boards.net/post/11234/thread

In android 8.0 turning usb debugging off will turn off the daemon, rending AnkuLua completely unable to work on FGO. Not something that can be fixed here, but thought I'd drop a warning and hopefully save others the confusion.

**Comment by 29988122** [comment]
Added text in the beginning of readme.md.
