### ISSUE TITLE
In EN version it is not recognizing weak or resist cards.

### ISSUE THREAD

**Issue by TylerNodell** [29988122/Fate-Grand-Order_Lua#46]
I've been loving the work you guys have been doing for this system, however I've noticed that it is not recognizing card with type advantage or disadvantage.

**Comment by 29988122** [comment]
@ryuga93 

How's it going? Is there any changes in the EN version?

**Comment by TylerNodell** [comment]
Not really sure. I have only just started using your build so I have yet to see it in a working state.

**Comment by TylerNodell** [comment]
https://photos.app.goo.gl/Gdmu47usMaKEhEXp9

That's what it currently looks like.

**Comment by 29988122** [comment]
Hmm..What's the status?

I mean, does it
1.Able to distinguish between menu screen and battle screen?
2.How was the click behavior? Can you describe it?
or
3.It didn't click at all?

**Comment by TylerNodell** [comment]
Sorry, I wasn't clear about that. The other features work fine. Other than a small snippet in the refill section that needed to be commented out, everything works. The only thing that doesn't is that it does not factor in resistances or weaknesses. In the card selection screen it always fills in Buster first than Arts and Quick. It also always selects from left to right and ignores weak or resist.

**Comment by ryuga93** [comment]
I did not notice any significant changes after the Camelot update, but I can't test the script myself, my ZTE does not have enough RAM to run FGO. Maybe @potchy can test it.

**Comment by TylerNodell** [comment]
Yes I fixed that by just commenting out that code snippet. Do you think the issue is because I'm using the 1.9.1 release?

**Comment by potchy** [comment]
Hmm, I've been using the script during the week, but I haven't noticed anything weird. I'll test it later and report back.

**Comment by TylerNodell** [comment]
I'll take a video of it later. Where can I send that to?

**Comment by 29988122** [comment]
Try youtube.com, vimeo.com, or dailymotion.com?

**Comment by TylerNodell** [comment]
https://drive.google.com/file/d/12R5qVYxn112HB2naGMKwvIMrPd35bo4N/view?usp=drivesdk

**Comment by potchy** [comment]
It's not working for me as well. I have no idea why, though. 🤔

I might be able to help on the weekend.

**Comment by potchy** [comment]
I thought I might have screwed something up with my commit, but that isn't it. It's not working with older builds as well.

I tried updating "weak.png" and "resist.png" in the "image_en" folder and it's gotten better. Would you mind trying it, @TylerNodell?
[image_EN.zip](https://github.com/29988122/Fate-Grand-Order_Lua/files/2196182/image_EN.zip)

**Comment by TylerNodell** [comment]
I tried updating it but I've seen no discernible difference.

**Comment by Rajvir8** [comment]
I also updated it and there isn't a difference for me either, it still chooses to use Buster Cards first, Arts Second and Quick Last from Left to Right.

Resistances and weaknesses remain ignored.

**Comment by ryuga93** [comment]
@potchy could you check if the regions are still the same?

**Comment by potchy** [comment]
I'll be checking ASAP.

**Comment by potchy** [comment]
@TylerNodell, please try this fix:
[en-affinity-fix.zip](https://github.com/29988122/Fate-Grand-Order_Lua/files/2216448/en-affinity-fix.zip)

**Comment by potchy** [comment]
Uh, @29988122 I'll be closing this, since you already merged the fix. lol
