### ISSUE TITLE
Suddenly Unable to Conect to Nox

### ISSUE THREAD

**Issue by Rajvir8** [29988122/Fate-Grand-Order_Lua#48]
I've been using this for a few days now, but for some reason while the Daemon can still start successfully it is now unable to connect to Nox.

I tried restarting my computer and updating Fate-Grand-Order_Lua and neither worked.

Not sure what the problem is?

Maybe Nox updated itself, but normally I'd at least be notified before an update was made.

So I'm not sure how the problem developed or how to fix it.

**Comment by Rajvir8** [comment]
This is what it looks like
![image](https://user-images.githubusercontent.com/17600697/42819521-d26796c4-89a1-11e8-8b9c-95b6b5a1685c.png)

**Comment by ryuga93** [comment]
Hi, I faced this problem while using Nox initially, and if I remembered correctly, I copied the adb from nox folder to replace the one in deamon folder. Remember to make a copy of the original one, or just add the .ori extension to it.

**Comment by Rajvir8** [comment]
I'm just about to experiment, first I'm not sure where the ADB in Nox is, but I should find it before long.

Once I find it I'll copy paste it, but do I replace the ADB file in tools or the Nox_ADB?

Both?

Since you'll probably not see this right away, I'll try both methods through copy pasting.

**Comment by Rajvir8** [comment]
Alright I found the ADB of Nox in the bin folder

I then tried both methods to see if either of them would work.

First I tried changing the ADB file in tools and while the message changed it didn't work.

I reverted back to the original and changed the Nox_ADB and it still didn't work.

Here is the new message I got
![capture](https://user-images.githubusercontent.com/17600697/42826436-642513ba-89b2-11e8-9472-f20b7cd513f4.JPG)

It seems to be implying that USB Debugging is off for some reason, but I double checked and it's still on.  I'm not sure what the problem is exactly.

Especially since just yesterday it was working fine in it's original form.

**Comment by Rajvir8** [comment]
I'm doing some research on it, but my guess is that the new text is coming because it isn't killing the service first.

It's going straight to connecting, with the original it killed something first and then made sure Daemon was working successfully and then it connected.

It failed at the third step.

When I replace the ADB it seems like it is failing on the first step.

Still going to keep looking to see if I can figure out a solution.

**Comment by Rajvir8** [comment]
I never did find out how to fix it, anything on your end?

**Comment by ryuga93** [comment]
The new message implies that Deamon is installed. Have you tried to run Ankulua?

**Comment by Rajvir8** [comment]
I just tried again and it turned out that did make it work.

Huh looks like I should have at least tried Ankulua rather than assume it didn't work based off the dialogue.

I assumed it would say connected to the device successfully like it used to.
