### ISSUE TITLE
Fixing Refill for EN

### ISSUE THREAD

**Issue by WoodenMug** [29988122/Fate-Grand-Order_Lua#51]
Hello,
I need to update FGO_EN_REGULAR.lua to include 
`NotJPserverForStaminaRefillExtraClick = 1`
so the refill works properly.
It seems I can't push my local branch and make a pull request. Could you put the fix in or grant me push permission? It will enable US players to use this script.

谢谢！

**Comment by 29988122** [comment]
Ahh, so EN server *did* upgrade to the version that refill behavior changed.

Done. Thanks for reporting!
https://github.com/29988122/Fate-Grand-Order_Lua/commit/8716bf879912e1079d4c57a7048e9ddad5200f5c

**Comment by WoodenMug** [comment]
great! thanks for the patch
