### ISSUE TITLE
Preset command choice?

### ISSUE THREAD

**Issue by WoodenMug** [29988122/Fate-Grand-Order_Lua#52]
First, the script saved me so much farming time I want to say thank you.
However, I feel like each time I have change a command sequence I have to enable root->change script-disable root->re-enable daemon -> start game. I would like to configure a list of preferred sequence in  FGO_XX_REGULAR.LUA and have an UI to choose what I want to execute. 
I am willing to make the change when I have time. Can I have permission to create pull requests?

Thanks,
Ray

**Comment by 29988122** [comment]
Emu I guess?

You can install "fx file explorer" directly from Google Play Store or Apkmirror, which provides a simple text editor for you to modify the script.

Or just like me, you can use Memu and Memupatcher.exe(check reddit /r/grandorder for further detail, titled emu wars or something else), which supported folder sync feature. Then you can directly modify your FGO folder in OS (windows, linux, osx).

**Comment by WoodenMug** [comment]
Thanks for the tip! That's very helpful.

**Comment by 29988122** [comment]
By the way, if it's an actual android and you happened to have unlocked bootloader, then install Android version <= 8.0 and install magisk+magisk hide, then you can have root+fgo running at the same time, no more daemon needed.
