### ISSUE TITLE
Script blocks on certain points

### ISSUE THREAD

**Issue by PrimordialRune** [29988122/Fate-Grand-Order_Lua#53]
The script is blocking on certain points, i tried to use it for the story and sometimes it doesn't recognize the next icon on the quest, it doesn't skip the story and it blocks after the quest is completed at the rewards screen after it finishes the quest.

Are those things bugs or are those features not implemented yet?

**Comment by 29988122** [comment]
Oh, the script doesn't recognize story screen, thus it won't proceed normally.

I ..somehow? encourage you to play the story on your own, it's more fun that way.

**Comment by PrimordialRune** [comment]
Oh, yes, i thought it was able to do the story too, my bad ahaha
I hoped that because i'm a NA player and restarting the same story is quite boring, but no problem!

But for the thing that it blocks at the rewards screen? Is it normal?

**Comment by 29988122** [comment]
Well the script will detect pattern of certain location on the screen.
In this case, I guess something on the story screen "triggers" it into the wrong section of the code, so anything could happen. 
There's no better way dealing with it, cause FGO's not a PC game, we cannot detect memory to determine which screen we're currently in.

Anyway it could be more interesting after story chapter 4.(I guess)
