### ISSUE TITLE
Can't get it work

### ISSUE THREAD

**Issue by shuyafaye** [29988122/Fate-Grand-Order_Lua#54]
I've been following all your steps but somehow it doesn't work. 

It always shows this error "Will only select servant/danger enemy as noble phantasm target, unless specified using Skill Command. Please check github for further detail." on the menu screen where I set the quest that I want at upper-right corner.

In battle screen, the error is "No priority target selected". And it does nothing. 

I've made sure the daemon installation is successful and copied all files in my phone. 

Device: Xiaomi Redmi Note 4
Android: 7.0

**Comment by 29988122** [comment]
Although this page is in Chinese, you can google translate it:
http://ankulua-tw.boards.net/thread/4/

小米用戶注意:
如果半透明的"play" 按鈕沒出現，請到設定->安全中心->授權管理->右上角齒輪進入->應用權限監控打開
然後再進入應用權限管理將Ankulua裡面的顯示浮動資訊框打勾，就會出現了。

如果開發者選項裡有USB 調適(安全設定)，請一並打開

Which means: Xiao Mi user, please enable usb debugging/usb tweaking/usb advanced security.
This is a different option from usb debugging mode.

This option allows Daemon to touch screen, while stay undetected from FGO.

**Comment by shuyafaye** [comment]
Unfortunately, I've done that as well but the error still appear.

**Comment by 29988122** [comment]
You may need to google translate this page.
http://ankulua-tw.boards.net/thread/229/miui-8-note3

"No priority target selected" was not an error, it's a message script print for mainly debug purposes. It means: the recognition is successful, script is working.

However, it did not start clicking the screen immediately after. It indicated only one thing - MIUI forbade AnkuLua from doing so. That is, Ankulua has the permission to read screen, but does not have the permission to click screen. MIUI separated those permissions into different developer's options.

Try again, switch the above mentioned options in the linked post(2~3 likely) to on, it will solve this issue.
