### ISSUE TITLE
Shorten the animation when servants or enemies dead

### ISSUE THREAD

**Issue by k0286** [29988122/Fate-Grand-Order_Lua#55]
Hello,
I know there is almost a `エネミー消滅短縮` option in the battle menu on the JP server.

But I hope you can add the function that can shorten or skip the exit animation of  enemies or servants for other servers.

I think that is very easy to implement by just keeping clicking  a region before a new round comes.

**Comment by 29988122** [comment]
https://github.com/29988122/Fate-Grand-Order_Lua/commit/4e6925760c22cf97a7b286171e15ec4cd325add2

Add a line 
```
UnstableFastSkipDeadAnimation = 1
```
anywhere in your```FGO_%server%_REGULAR.lua, and you're good to go.

Unfortunately Lua is a single-threaded programming language, thus I (likely) cannot set up a watcher to check every second if we finished battle animations or not. Our current way is time counting, plain and simple.

That means - if you killed enemies real fast, the script could be still clicking, thought it was still skipping dead animations, wasting time; if you killed them slow, the clickings could be already finished, animations not skipped.
Feel free to change line 300~ in regular.lua to fit your need.

Not really useful though...
Can't really insert screen recognition every second, your phone and battery will die QQ
