### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by zCypher** [29988122/Fate-Grand-Order_Lua#59]
![message](https://user-images.githubusercontent.com/42288165/43988121-2d4370a6-9d05-11e8-9596-efebf3ba06f6.jpg)

Whenever I try to run the script in the game or outsite it I get this error
Even on debug mode I get this error, I've tried moving the folders, the .lua file to other places, It didn't work as well, can I get some help?

**Comment by 29988122** [comment]
/sdcard/Download/regular.lua is there, right?
Then it could be permission issue - try grant Ankulua folder read/write permission.

What's your phone by the way? Mi phones and Android 8.0 phones are known for their restrict permission control.

**Comment by zCypher** [comment]
I've tried the R/W permission thing, but I got some sdcard problems.

I'm actually using Nox Emulator, I've reinstalled it with a different config, I'll try the permission thing again and see if that works for me.

**Comment by 29988122** [comment]
Nox should be fine, as for now I'm using the latest version of nox running Summer event in JP server.

No idea what happened ...

**Comment by zCypher** [comment]
Yeah, nevermind, I managed to make it work.

Thanks for the help, it's working perfectly now!

**Comment by 29988122** [comment]
: D
