### ISSUE TITLE
Idk

### ISSUE THREAD

**Issue by ColdDeus** [29988122/Fate-Grand-Order_Lua#6]
Cant i ask you why this thing happend, i am aleready use the latest release 1.3.1
![1504004439300-321243059](https://user-images.githubusercontent.com/31419775/29817901-05cb0db8-8ce4-11e7-9d0d-41ffe9b99bbf.jpg)

**Comment by 29988122** [comment]
After few days of checking..I can only figure out one possibility.

1. Make sure you downloaded latest version from release section
2. DO NOT alter the folder structure, extract all files, and do not extract them under C:\
