### ISSUE TITLE
First time Messing with the settings

### ISSUE THREAD

**Issue by Rajvir8** [29988122/Fate-Grand-Order_Lua#60]
Hi I just wanted to make sure I was doing this right and thought I might as well ask.

I'm opening FGO_EN_REGULAR with Notepad

But I'm not perfectly clear how the turn system works.

Is the Autoskill_List[1] for turn 1 and so on?

Does it also record battles?  Or is it just turns?

It mentions that by default it picks weak buster->buster->resist buster->weak arts->arts->resist arts->weak quick->quick->resist quick

Could I change it to weak buster->weak arts->buster->arts->weak quick->quick->resist buster->resist arts->resist quick

Thanks in advanced, and I hope with your help I'll figure it out quickly.

**Comment by 29988122** [comment]
I guess you don't need autoskill list at all - that's only useful when you need to farm different quests / different enemies during event. It's meant to avoid hassle from manual editing lua files in order to adapt to quests.

Just make autoskill list default = 0, and enter what you want as readme says here https://github.com/29988122/Fate-Grand-Order_Lua#autoskill between double quote. Skill_Command = ""

**Comment by 29988122** [comment]
>It mentions that by default it picks weak buster->buster->resist buster->weak arts->arts->resist arts->weak quick->quick->resist quick
>Could I change it to weak buster->weak arts->buster->arts->weak quick->quick->resist buster->resist arts->resist quick

This is kinda tricky, so I did not write it into manual.
Open regular.lua, check line 37~line 51. That's the formula(card score, weighted score) of damage estimation.

Just change line 37~43, make it whatever you want and suits the need of weak buster->weak arts->buster->arts->weak quick->quick->resist buster->resist arts->resist quick(order in score, obviously)

**Comment by Rajvir8** [comment]
Alright so I can ignore the autoskill list completely, I can play around with the formula for damage calculations on my own as that sounds interesting.

But I'm still a bit confused on how to put turn order in, specifying the skill and servant is understandable

For using my Lancer's second skill dodge in the first turn I'd use

 e

would I then add two 0 and the next skill I plan to use in turn 3

Let's say Berserker's Attack up

"e,0,0,a"

Or would that be

"e,#,#,a"

I'm not sure what the difference is?

**Comment by 29988122** [comment]
>But I'm still a bit confused on how to put turn order in, specifying the skill and servant is understandable

In you case, "e,0,0,a".
# means "WAVE" as for most quests they have 3 waves of enemies.

**Comment by Rajvir8** [comment]
Thanks I'll give it a try now, thanks for the help.  If anything comes up I'll reopen the issue.

**Comment by 29988122** [comment]
Oh it accidentally became bold font. 

You can feel free to ask any thing tho! I don't mean that lol.

Glad that my script helped you!

**Comment by Rajvir8** [comment]
I just tried and I'm afraid it didn't work at all.

I imagine I must have messed up something.

I changed it to this

--When Enable_Autoskill_List = 1, the script starts with a dialogue for you to choose Autoskill setting from one of the predefined list
Enable_Autoskill_List = 1
Autoskill_List = {1}
--The folllowing are predefined settings by user
Autoskill_List[1] = "eghi,0,0,acdf,b"

They just didn't use any skills at all at any point, I thought it might be an issue with turn 1 and how it might be coming up to fast.  But the skills never popped up at all.

I did get the list asking which source I wanted to use when I entered into battle and I choose 1, the only one with anything in it.

**Comment by 29988122** [comment]
>They just didn't use any skills at all at any point

Android 8.0? MIUI phone?

**Comment by Rajvir8** [comment]
I'm using Nox

The plan is to start off with using my support servant's full arsenal of skills and Cu Dodge

Then wait two turns and then Use Hercules Attack Up and Guts, then Next turn use his dodge.

I'll probably make a second where I delay using my support servants turns more properly.

I can't change it to wave can I?

I'm currently planning on using turns, but saving all of my support servant skills for the boss wouldn't be a bad idea as an option.

Of course that's for the future best to get it working now.

**Comment by 29988122** [comment]
OK somebody got the exactly same issue before. Hold on I'll find it

**Comment by Rajvir8** [comment]
Got it, thanks

**Comment by 29988122** [comment]
https://github.com/29988122/Fate-Grand-Order_Lua/issues/54

This is why it does nothing: the daemon installation likely failed. So there's 0 screen touching at all.
I can only ask you to (backup first!)
1.create a new vm to see if ankulua can click screen correctly
2.completely uninstall nox, install a new one, use a fresh new vm to test.
3.then import your backed up FGO vm to try again.

**Comment by Rajvir8** [comment]
I understand I read that issue earlier, it's still working fine though.

It's proceeding to go through the half off AP 15 Berserker zone fine and is still winning as we speak

**Comment by Rajvir8** [comment]
I want to be able to go the the new half off 20 AP though which will likely require skills.  I can't get those to work, the touch screen is working fine.

**Comment by Rajvir8** [comment]
That person wasn't able to get the script running at all after all.

**Comment by 29988122** [comment]
Got your situation wrong, my bad.

So if the following section were set like this, it will work. In its simplest form:
```
~irrelevant~
dir = scriptPath()
setImagePath(dir .. "image_JP")
StageCountRegion = Region(1722,25,46,53)
NotJPserverForStaminaRefillExtraClick = 1
Refill_or_Not = 0
Use_Stone = 0
How_Many = 0

~revelant~
Enable_Autoskill = **1**
Skill_Confirmation = 0
Skill_Command = **"abc,#,def,#,ghi"**
Enable_Autoskill_List = 0

~irrelevant~
Enable_Autoskill_List = 0
Autoskill_List = {}
Autoskill_List[1] = ""
Autoskill_List[2] = ""
Autoskill_List[3] = ""
Autoskill_List[4] = ""
Autoskill_List[5] = ""
Autoskill_List[6] = ""
Autoskill_List[7] = ""
Autoskill_List[8] = ""
Autoskill_List[9] = ""
Autoskill_List[10] = ""
Battle_CardPriority = "BAQ"
isEvent = 0
dofile(dir .. "regular.lua")
```

By doing so, it will cast the 1st, 2nd, 3rd skill of the first servant(in your party in the first wave.), and start normal battle.
When the 1st wave is wiped out, we entered 2nd wave.
Then it'll cast the 1st, 2nd, 3rd skill of the second servant. 
When the 2st wave is wiped out, we entered 3nd wave.
Then it'll cast the 1st, 2nd, 3rd skill of the third servant. 

Then it will auto choose cards until the quest's over.

**Comment by Rajvir8** [comment]
Wait I think I may have just spotted my big mistake, you left the Autoskill list empty, but you filled out Skill Command which I left empty, you also left autoskill list off while I turned it on.  I'll try swapping them and see if that fixes it.

**Comment by Rajvir8** [comment]
I also left Autoskill on 0 so it might have been stuck, I focused on the list only

**Comment by 29988122** [comment]
Ok that's it.

The flowchart:
Is Autoskill on?
NO: then screw your skills.
YES:load skill_command to execute, next step.

Is autoskill list on?
No: use skill_command
Yes: popup a window to let user choose from 1-10, then **use user chosen commend** instead of skill_command.

**Comment by Rajvir8** [comment]
It's working now, can't believe I missed that.  Thanks

**Comment by Rajvir8** [comment]
I'll have to play around with it more and come up with a longer string, and consider which servants they apply to for support.  But this works perfectly, thanks again.

**Comment by 29988122** [comment]
: D
