### ISSUE TITLE
Runtime error (USB Debugging?)

### ISSUE THREAD

**Issue by Fabut** [29988122/Fate-Grand-Order_Lua#64]
I dragged the extracted folder into my phone's download folder and attempted to open run.bat in the specified location. After doing so it gave me this error and now my phone isn't able to open FGO anymore. Whenever I attempt to open the game it says "Fate/Grand Order is not playable under your playing environment". How do I fix this and did this just mess up my game?

https://prnt.sc/ko2pmy

**Comment by 29988122** [comment]
1. you must execute the run.bat "ON YOUR WINDOWS PC"

2. After the daemon has been installed, you can disable usb-debugging and run fgo.

**Comment by Fabut** [comment]
I did execute it on my PC. The link of the screenshot I put is from my computer. Am I supposed to try to execute the run.bat that is inside the phone? Also I'm not sure where exactly I need to put the FBO extracted folder in. If you could simplify the steps for me I might find out what I did wrong.

**Comment by 29988122** [comment]
The system cannot find the path specified = phone not found = please install minimal adb driver as shown in readme.txt

**Comment by Fabut** [comment]
I installed that but I have no idea how to use it.

**Comment by 29988122** [comment]
reboot->enable usb debugging->plug it into PC to see if it detected your phone(beep sound)

Then install daemon again.

**Comment by Fabut** [comment]
I'll try to reboot it before connecting when I get home, but when I tried it yesterday I'm pretty sure my PC detected my phone. I was able to see my phone's files on my computer, which is how I was able to put the Fate folder inside the phone.

**Comment by Fabut** [comment]
Still doesn't work for me, I'll list down exactly what I did.
1. I downloaded the file and extracted the zip on my computer.
2. I rebooted the phone, enabled USB debugging, changed the mode from charging to file sharing, and plugged it into my computer
3. I moved the extracted folder from my computer to my phone's internal shared storage.
"This PC\Pixel 2 XL\Internal shared storage"
4. I opened the folder inside the internal shared storage with my computer and opened run.bat inside of 
"This PC\Pixel 2 XL\Internal shared storage\Fate-Grand-Order_Lua-master\Fate-Grand-Order_Lua-master\ama_daemon"
5. It opens command prompt with the text "The system cannot find the path specified"

I really don't know how to fix this at this point, if I have to use minimal adb driver could you explain what I'm supposed to do with it? It just opens command prompt.


![screenshot_4](https://user-images.githubusercontent.com/42794285/44819588-31999300-aba2-11e8-89e5-32c965c616f9.png)

**Comment by Fabut** [comment]
Ok I found out that I was trying to open the run.bat inside of the phone's files instead of the one in my desktop. The daemon installation was successful but I'm running into a final problem. Whenever I try opening AnkuLua the app just crashes. I'm not sure why the app is crashing, is it because of the app itself or the daemon installation?

**Comment by Fabut** [comment]
In the AnkuLua app I can't find the script. The only two scripts I see are called snapAndPlay.lua and recordAndPlay.lua. I don't see any option to select or open a custom script anywhere.

**Comment by Fabut** [comment]
I got AnkuLua working and loaded the script. I play the EN version of the game so I loaded the FGO_EN_REGULAR.lua into AnkuLua. However when I press the gray arrow during a battle it does nothing and gives me a runtime error.

https://photos.google.com/share/AF1QipM-pWPhBNtR5XI7wJSugeNgzuFuwPVXTt0a7vvjXu4pROfsLq-sSEdmcSzypCpDaA/photo/AF1QipNU9lB1pL8KH_PsOcEld18pTa7aGGS6lfcG381Y?key=V2UwdXMxTVJMcE9FbTBkR0w1Z3lOYmRHdWxCMzBR

https://photos.google.com/share/AF1QipM-pWPhBNtR5XI7wJSugeNgzuFuwPVXTt0a7vvjXu4pROfsLq-sSEdmcSzypCpDaA/photo/AF1QipPQRNY6aDbajQzmcWcbR4dDdJ4iK72k7IN10htB?key=V2UwdXMxTVJMcE9FbTBkR0w1Z3lOYmRHdWxCMzBR

**Comment by Fabut** [comment]
I managed to load the EN version of the script into AnkuLua. However when I try using or pressing the grey arrow during a battle it does nothing. After a couple seconds it gives me a runtime error saying this:

![2](https://user-images.githubusercontent.com/42794285/44823847-7da30280-abb7-11e8-9776-8e808aa27ab6.png)

![1](https://user-images.githubusercontent.com/42794285/44823849-7ed42f80-abb7-11e8-9eee-c4c647130322.png)

I would really appreciate it if you could help me solve this. I'm not sure what this means and how I'm supposed to fix it. Thank you

**Comment by 29988122** [comment]
The thing is: phone storage connected =/= phone debug bridge (adb) connected.

Minimal ADB and Fastboot driver should make adb recognized in windows. keyword:should.
You'll need to uninstall all drivers and reinstall minimal adb and fastboot driver(in windows Device Manager, google if you have no idea how to do it)many times, until windows recognized your phone's debug bridge.(while usb debugging is enabled)


After it's recognized and run.bat executed, of course usb debugging can be disabled and run FGO smoothly.

**Comment by Fabut** [comment]
I'm pretty sure it's being recognized in Windows. I used Minimal ADB and Fastboot to detect my phone on my computer. These are the results of using Minimal ADB/Fastboot and opening run.bat inside the Fate folder on my desktop.

This is the result of Minimal ADB and Fastboot
![minimaladb](https://user-images.githubusercontent.com/42794285/44833719-d7b9bd00-abe3-11e8-980c-9be61ce602cc.png)

This is the result of opening run.bat inside the Fate folder on my desktop
![save](https://user-images.githubusercontent.com/42794285/44833730-e0aa8e80-abe3-11e8-9c27-29ab4f861d27.png)

**If I try to open AnkuLua WITHOUT Daemon, it will tell me that I am unable to use the app without Daemon. However, disabling USB Debugging will still allow me to access the AnkuLua app, meaning that I must still have daemon? Though the errors I showed in my previous post looks like daemon is being disconnected/not found.**

**Comment by ryuga93** [comment]
May I know your android version and phone model?

**Comment by 29988122** [comment]
I agree with every of your observation @Fabut, I was wrong, and the issue's a little more weird than I expected. 

Can you try move fate-grand-order-lua folder to C:\ or D:\ (root), and execute run.bat as administrator?
Under windows, bat executable file sometimes has encoding problems.

**Comment by Fabut** [comment]
@Ryuga93 I'm using a Google Pixel 2 XL with Android Version P. 

@29988122 I'll try to do that when I get home and post results

**Comment by 29988122** [comment]
Ehhhhhhhh.......Nooooooooo, I'm sorry.

https://github.com/29988122/Fate-Grand-Order_Lua/blob/master/README.md

"PSA: DO NOT update to Android 8.0 and above, or you'll have to use Emulator for the script."

Android restrictions, you might need to ask the author of Ankulua to support. Not likely to happen tho, he once said that the difficulty was likely ten-fold.

**Comment by Fabut** [comment]
@29988122 I'm trying to do it on the NOX emulator now and the only problem I'm facing is that the run.bat isn't detecting the emulator.

**Comment by Fabut** [comment]
@29988122 
I received an email from AnkuLUA and they said that their app already supports Android P. I've tried a bunch of solutions but I still have no luck with using my android device (I've moved the Fate folder to my C: drive but running as administrator will give an error. 

Now I've been trying to do it on the NOX emulator. I've managed to install Daemon and load the script but now the problem lies in FGO for me. Whenever I attempt to open FGO it shows a white screen and then it closes itself. This is extremely similar to the problem when I couldn't open FGO on my phone, and issue was that USB Debugging was enabled (FGO doesn't allow USB Debugging to be on). I disabled USB Debugging on the emulator and the issue still persists. I believe that something is alerting FGO to close itself, maybe something similar to USB Debugging? I've tried disabling rooting but I had no luck with that either. I've also tried MEMU Emulator and I'm having the same problem with this one as well. On this Emulator I even tried to download FGO through QooApp (Different type of Play Store). Now I'm going to try doing the same on KOPlayer. 

I believe the emulator has something that is blocking or alerting FGO to close itself. I'm not sure if emulators are banned from the game but something similar to the detection of USB Debugging is not allowing me to launch the game on NOX or Emu. IF KOPlayer doesn't work for me then I have to either find the cause of the issue or try to find the solution for my phone instead.

**Comment by ryuga93** [comment]
I'm using Nox 6.2.1.1, tested with the QooApp version and it is running fine. Two things that will prevent FGO from running are root and USB debugging. It should work fine if you disabled both.

Maybe reinstall Nox and FGO try run it before doing anything with Ankulua.

**Comment by 29988122** [comment]
Of recent 3 days FGO JP blocked Nox, the way to bypass it would be 
1.change your system time to yr > 2020
2.it will pop up error
3.change it to auto set time
4.click retry, profit

source: me
https://www.facebook.com/jerry.ho.395/posts/2234431926585388

**Comment by 29988122** [comment]
Also, Ankulua supported >=Android 8.0 doesn't mean that you can use it on FGO.

Source: http://ankulua-tw.boards.net/post/6175/thread (google translate it)
