### ISSUE TITLE
2.0.0 function decodeSkill for cast NP default wait time 0.8 is too short

### ISSUE THREAD

**Issue by lokilin** [29988122/Fate-Grand-Order_Lua#65]
if index >= -44 and index <= -42 and decodeSkill_NPCasting == 0 then
		---Enter card selection screen, ready to cast NP.
		click(Location(2300,1200))
		decodeSkill_NPCasting = 1
		**wait(0.8)**
end

0.8 can't work on my machine. This number was 1 at 1.9.4, and it worked perfect.
0.8 may not work on some machine I thought.

**Comment by 29988122** [comment]
https://github.com/29988122/Fate-Grand-Order_Lua/commit/95c67f241196f846b6b3ac68dc2998c3f2cf6181

Thank you for pointing this out : D
