### ISSUE TITLE
[Feature Request]Target Choose Should Happen in Each Stage

### ISSUE THREAD

**Issue by WoodenMug** [29988122/Fate-Grand-Order_Lua#67]
Currently the script will choose target once and never do it again because reset of TargetChoosen happen in menu stage: 
https://github.com/29988122/Fate-Grand-Order_Lua/blob/95c67f241196f846b6b3ac68dc2998c3f2cf6181/regular.lua#L756-L762
I suggest we move the variable out of the if clause (causing every battle action to check target) or putting it in the stage increment block (causing every stage to check target)

Thanks,
WoodenMug

**Comment by 29988122** [comment]
https://github.com/29988122/Fate-Grand-Order_Lua/issues/62
This one also.

**Comment by WoodenMug** [comment]
Thanks, I can take a look at it and show you the snippet when I have something.

**Comment by potchy** [comment]
Solved with #82
