### ISSUE TITLE
Problem with non friend supports

### ISSUE THREAD

**Issue by drakan08** [29988122/Fate-Grand-Order_Lua#68]
I noticed while testing the new function for Ce and supports servants that if the scrip chooses one support that is not your friend at the end of the battle it will get stuck on the send friend request screen.

I guess this something simple to fix as to add another line of code to check for the "Do Not Request" button.
 
*Update:
https://drive.google.com/drive/folders/1Hty7xy6_uacYggxPv34zo9Fq_M1l_exR?usp
NA
![screenshot_2018-09-16-17-29-44](https://user-images.githubusercontent.com/26861121/45600849-ef61b580-b9d9-11e8-8835-48ffff6ae074.png)
JP
![screenshot_2018-09-16-17-54-46](https://user-images.githubusercontent.com/26861121/45600850-ef61b580-b9d9-11e8-86f8-00dea395379e.png)

**Comment by potchy** [comment]
Hm, yes, there's this problem, but we'll need pictures from other servers besides NA.

**Comment by ryuga93** [comment]
The detection is probably fine with the arrow and class icons above

**Comment by 29988122** [comment]
測過了感覺可以 揪咪

真的不行或是會誤作動再說 XD
