### ISSUE TITLE
Can't install daemon

### ISSUE THREAD

**Issue by saiyansoul** [29988122/Fate-Grand-Order_Lua#7]
it seems i cannot install the daemon on my phone.

'.\tools\lua5.1.exe' is not recognized as an internal or external command,
operable program or batch file.
 
it says like that

**Comment by 29988122** [comment]
After few days of checking..I can only figure out one possibility.

1. Make sure you downloaded latest version from release section
2. DO NOT alter the folder structure, extract all files, and do not extract them under C:\

**Comment by ryuga93** [comment]
@29988122 Could you check if your release contains lua5.1.exe in the tools folder? Probably that's the problem. Github seems to remove all exe files when you upload them.

**Comment by 29988122** [comment]
Yes, that's exactly the problem!
Thank you bro, never thought of it...
