### ISSUE TITLE
Nox is taking up a large amount of space, due to snapshots?

### ISSUE THREAD

**Issue by ostrobos** [29988122/Fate-Grand-Order_Lua#70]
Hi, I think the snapshots are taking up a decent amount of space on Nox, but I'm not too sure if it actually is. Nox has been taking up around 8 GB and now changed to 14 GB after running the script a few times. What do you think the reason is? I'd like to believe it's the snapshots, but that doesn't make too much sense. Have you noticed anything like that? My previous Nox emulator had taken up 50 GB before I started a new emulator.
![qiv2gkh](https://user-images.githubusercontent.com/43448795/45832803-ec640f00-bcd0-11e8-8e45-9a4eb8f35de6.png)

**Comment by 29988122** [comment]
No idea, the screenshot will replace itself every time(same file).

So the script will only generate 1 jpg file. I did not observe abnormal size on my side of nox.
Maybe you can run a storage space analyzer such as SDMaid to check what took up the space of your Android image.
