### ISSUE TITLE
For Support it doesn't take the star into Account?

### ISSUE THREAD

**Issue by Rajvir8** [29988122/Fate-Grand-Order_Lua#72]
I noticed that although support is working perfectly now, when I have it on Bronze Grinding it isn't taking the star into account.

I'm using
![bronze medal](https://user-images.githubusercontent.com/17600697/46031340-a0e1a480-c0c6-11e8-8bc3-e9a27459d637.PNG)

But it still chose a random person who had a normal Caligura rather than a max stared one.

It also got stuck on the friendship request, but from what I heard that's still being fixed as well.

**Comment by potchy** [comment]
It's probably too small for AnkuLua's detection. :c
I'll take a look at it later.

**Comment by Rajvir8** [comment]
Thanks I appreciate it Potchy

**Comment by potchy** [comment]
Please try the latest release to see if it solved this issue.
See #73 for more details.

**Comment by 29988122** [comment]
I guess it's fixed by the comments? 

@Rajvir8 
Try to test using the latest master branch

https://github.com/29988122/Fate-Grand-Order_Lua/archive/master.zip
I guess potchy solved it, because I saw the newly added limitbroken.png.

**Comment by Rajvir8** [comment]
It's fixed, I just got the chance to test it today as some of my friends finally have limit broken maid so I was able to test it.
