### ISSUE TITLE
Problem about command card selection

### ISSUE THREAD

**Issue by 95275566** [29988122/Fate-Grand-Order_Lua#76]
我的情況是有時在wave3會進入無限迴圈，一直重覆點擊我方其中一名角色然後再關掉角色狀態視窗。

除此之外，也有wave2/3不用寶具的情況。

請問這樣的情況可以怎樣解決?我的skill command是這樣
d1efghi16,#,jx31achi14,#,b4

**Comment by 29988122** [comment]
您是那個伺服器的？
目前您寫的指令是Battle 1放從者3的寶具和Battle 2放從者1的寶具，Battle 3放從者1的寶具(而且如果進Battle 3的當回合沒有np100就不會放寶具了，要每回合都檢查你要#,4,4,4,4,4,4,4這樣下去寫)

==
如果是語義誤會，您沒有寫錯只是文章敘述錯的話，那請讓我看看您執行"d1efghi16,#,jx31achi14,#,b4"時候的影片，這樣我才能判斷哪邊程式進入了不該進入的狀態，是autoskill指令寫錯還是辨識圖像有問題。

**Comment by 95275566** [comment]
我是日版玩家，需要影片的話，我要再測試一下直到出現相同情況才能拍影片。
我Battle2/3都是用弓貞德寶具，從者配置確保能夠在Battle2回收62NP，然後Battle3靠NP技充滿。
目前除了那種迴圈情況，也出現過懷疑太早點擊寶具卡位置，沒成功點擊寶具卡的情況。
我不清楚會不會是跟夜神模擬器使用的CPU數和RAM有關，顯卡是GTX750ti。

如果是因為硬體性能不足導致卡頓而出現這種情況的話，請問有辦法透過加入延遲點擊的時間解決嗎?

**Comment by 29988122** [comment]
我猜您先開個四核，起碼3g ram給nox，弄成directx模式(如果能開)，20~30fps再看看
您的推測的話：是，如果我同時開vm開wow再開1080p影片的話，Nox就跟死掉一樣，刷紐約會常常漏按鍵。

因為目前延遲的部分沒辦法統一調整，如果您在在Ankulua內有開開快速點擊或是另一種點擊方法的話，把它關掉

然後您可以土法煉鋼的用記事本在regular.lua內搜尋"wait("
把27個entries裡面的秒數手動全部改成1.5甚至是2倍，可以解決很多機器lag所帶來的問題（雖然刷箱效率會變低）
我之前也調了很久，現在的wait()秒數是在腳本速度和穩定性間的一個尚可接受的平衡。

您試試看再和我說結果！

**Comment by 95275566** [comment]
[最初提及的問題在這影片裡。](https://youtu.be/odsLDVl4SEo)
如果我像影片那樣，手動關掉視窗進去選卡畫面的話，他會隨便選3張卡而不是選寶具卡。
我換另一隊的話，這種情況較少發生，可能弓貞動畫太拖而且會卡。

目前開2核+4GB RAM給NOX也會有這種情況，我先試試把entries全改掉的方法，謝謝你耐心為我解答。

**Comment by 29988122** [comment]
ok, 他進入選卡state了，你可以看見script一直試圖要點右下角...XD

多半是因為前面在技能施放的時候，某一個技能是在cd的，或是同一回合連續施放技能時施放太快=就算在2x下servant本身技能動畫還是太長，就會出現這種狀況。
lag也會導致按鍵沒反應 - 這個比較特別，這是fgo的問題，不是script或是emu的問題。

您看一下454到459行，我推測這邊的wait影響比較大。
```
	if index >= -44 and index <= -42 and decodeSkill_NPCasting == 0 then
		---Enter card selection screen, ready to cast NP.
		click(Location(2300,1200))
		decodeSkill_NPCasting = 1
		wait(1)
		--Although it seems slow, make it no shorter than 1 sec to protect user with less processing power devices.
```
改成wait 1.5或更多，或許就能讓大多數的卡住狀況得到緩解。
當然最保險的方法還是把全部的wait()一起改過啦，不過這樣刷箱效率的問題就(ry

**Comment by 95275566** [comment]
謝謝你花時間為我解決問題，目前先放著他運行一段時間看看。
弓貞的技能都複合效果，動畫也拖，可能真的比較長。
祝你刷箱順利！
