### ISSUE TITLE
Minor Support list problem

### ISSUE THREAD

**Issue by ineedhelp6969** [29988122/Fate-Grand-Order_Lua#77]
Hello!, having a slight issue with the auto support, i had it set to a merlin pic, example: https://imgur.com/a/Quqq9Lp , and it was choosing it just fine, however  when i wanted to  switch  to a waver with the same CE https://imgur.com/a/t28YWDf , the script just goes past it and just keeps searching. for a support.

**Comment by 29988122** [comment]
@potchy 
Could it be the problem of "event tooltip"? 

Like, the ticket +2 balloon tooltip. It's a blinking tooltip, thus the timing Ankulua took the screenshot will affect the success rate of recognition.

**Comment by ineedhelp6969** [comment]
I tried another screenshot, tried to get it like the merlin one https://imgur.com/a/J6atsGY , it still keeps searching

**Comment by potchy** [comment]
Would you mind sending a screenshot of your support list?
Preferably, one where we can see both Merlin and Waver, or one for each, whatever.

Try cutting the blue borders:
![xkkpr4d](https://user-images.githubusercontent.com/4316326/46317708-45be1f00-c5aa-11e8-9b5d-3e82cf04aba5.png)

Also, I've noticed all your screenshots are in different resolutions. How are you taking them?
