### ISSUE TITLE
nox adb connection port

### ISSUE THREAD

**Issue by mchance22** [29988122/Fate-Grand-Order_Lua#78]
Hi
i would like your help with this issue

![imagen](https://user-images.githubusercontent.com/43779327/46343405-37502180-c603-11e8-8841-ddb9fc2cc14c.png)

it seems the bat tries using a port, but the noxx instance is in other
is there a way to change this?

**Comment by aqer** [comment]
I start using NOX last week and encounter the same problem.

After I report to Ankulua forum, the author of Ankulua told me to install boot daemon on NOX so I don't need to install daemon from PC.

It works for me, you may try it.
[http://ankulua.boards.net/thread/1148/install-boot-daemon](http://ankulua.boards.net/thread/1148/install-boot-daemon)
[http://ankulua-tw.boards.net/thread/679/daemon](http://ankulua-tw.boards.net/thread/679/daemon)

**Comment by mchance22** [comment]
ty very much
