### ISSUE TITLE
When using "preferred" support select mode, select friends only

### ISSUE THREAD

**Issue by potchy** [29988122/Fate-Grand-Order_Lua#79]
[Quoted directly from](https://github.com/29988122/Fate-Grand-Order_Lua/pull/73#issuecomment-426467622) @TheIanator.

> Looks great. One more thing I was thinking of adding was detection for friends only, noticed that on both JP and NA there's a friend point icon at the lower right of the support servant that is absent when the support is not a friend.
> 
> ![screenshot_20181002-174053](https://user-images.githubusercontent.com/29805524/46383007-56829980-c66b-11e8-9316-8e1b0f329afc.png)
> ![screenshot_20181002-173808](https://user-images.githubusercontent.com/29805524/46383008-56829980-c66b-11e8-8be2-314a497b9bfa.png)

**Comment by potchy** [comment]
I'll be working on this feature in branch [**friends-detection**](https://github.com/29988122/Fate-Grand-Order_Lua/tree/friends-detection).

**Comment by 29988122** [comment]
< 3

**Comment by potchy** [comment]
I think this is almost ready, but I'll wait for Halloween Part 2 before merging to `master`, so I can do a bit more testing.
