### ISSUE TITLE
New feature request: servants exit animation accumulate

### ISSUE THREAD

**Issue by Xianbei233** [29988122/Fate-Grand-Order_Lua#89]
RT, this animation waste too much time, i think it should add some tap event at screen central to accumulate the animation

**Comment by Xianbei233** [comment]
and i also think the gap time between recognition and taking action is a little long. Is this the limit of ankulua or actually we can modify the value?

**Comment by potchy** [comment]
You mean Servants death animation? If that's the case, see #55.

**Comment by Xianbei233** [comment]
@potchy  got it, any more option can i modify?or a more detailed document maybe better. The readme is just give the stable module usage, i want to do more customize

**Comment by Xianbei233** [comment]
![image](https://user-images.githubusercontent.com/16370242/47983883-b5767b00-e10f-11e8-961a-03dfb2eb4eed.png)
