### ISSUE TITLE
run.bat 找不到指定的路徑..

### ISSUE THREAD

**Issue by aqer** [29988122/Fate-Grand-Order_Lua#9]
從電腦上執行手機裡的run.bat 找不到指定的路徑
![default](https://user-images.githubusercontent.com/24737421/30252415-d1a9150a-96a4-11e7-9364-ab61d617ddf2.png)

驅動程式有裝過了
![default](https://user-images.githubusercontent.com/24737421/30252422-0accfd2e-96a5-11e7-8cf6-299c073740da.png)

手機是ASUS Zenfone 3, 作業系統是win 7 64bit
USB偵錯也有開..不知道是甚麼導致的
還是我的步驟有問題嗎?

**Comment by 29988122** [comment]
資料夾結構應該是這樣子

Fate-Grand-Order_Lua
Fate-Grand-Order_Lua\ama_daemon
Fate-Grand-Order_Lua\ama_daemon\run.bat
Fate-Grand-Order_Lua\ama_daemon\daemon
Fate-Grand-Order_Lua\ama_daemon\tools

Fate-Grand-Order_Lua\ama_daemon\tools\lua5.1.exe
Fate-Grand-Order_Lua\ama_daemon\tools\luac5.1.exe
Fate-Grand-Order_Lua\ama_daemon\tools\adb.exe
Fate-Grand-Order_Lua\ama_daemon\tools\install.luac

1.請檢查一下資料夾"目錄結構"是否如上，沒有改動過
我列出了一些基本上必須有的檔案

2.然後之前的版本有一個bug，沒有放*.exe進去，也請確認是不是載最新的release

3.都不行再用系統管理者權限執行看看...

還是不行就在這邊回報吧，如果您相信我，再約個時間teamviewer遠端遙控我看一下，我猜是五分鐘內可以解決的問題

**Comment by aqer** [comment]
1. 這些資料夾及檔案結構都有
2. 檔案是1.4.1版的
3. 不知道如何使用系統管理者權限執行? 右鍵沒有這個選項
![image](https://user-images.githubusercontent.com/24737421/30261780-c13ad472-9700-11e7-8688-436681f51adb.png)

在外面看手機是
![image](https://user-images.githubusercontent.com/24737421/30261800-d728639e-9700-11e7-80a7-8a71d8a45b2a.png)
路徑是
![image](https://user-images.githubusercontent.com/24737421/30261809-e8f3bda8-9700-11e7-9966-b5ac18f1239a.png)

我看有的討論說接上手機會有偵錯的授權視窗,
不過我的手機開啟USB偵錯只會問你允不允許USB偵錯而已
麻煩你了 謝謝!

**Comment by 29988122** [comment]
![2017-09-11 15 42 24](https://user-images.githubusercontent.com/5474709/30263543-e2809e94-9707-11e7-8d2d-678a45c3239c.png)
手機沒接應該是這樣的訊息才對，你那個好像和驅動程式也沒什麼關係

說實話我不知道該怎麽解.. =.=
你檔案試試不要放在系統目錄下，改放在C:\fatelua或是D:\fatelua之類的

系統管理員執行選項要用shift+右鍵 就會出現了

**Comment by aqer** [comment]
本來都是放在手機上執行,改放C槽試
C:\Fate-Grand-Order_Lua\ama_daemon

在C槽雙擊執行
![image](https://user-images.githubusercontent.com/24737421/30264739-6d8c845e-970c-11e7-9893-aee77ce6f737.png)

在C槽用系統管理員執行
![image](https://user-images.githubusercontent.com/24737421/30264768-86211e62-970c-11e7-8303-af54f0ead520.png)

**Comment by 29988122** [comment]
（原本）你放手機上執行當然不行啊，那又不是一般硬碟..

lua5.1.dll有在Fate-Grand-Order_Lua\ama_daemon\tools嗎，為什麼你檔案缺東缺西的 XD

**Comment by aqer** [comment]
誤解了XD　我還以為要放手機執行才對

Fate-Grand-Order_Lua\ama_daemon\tools　裡沒有lua5.1.dll耶
解壓縮出來就沒有這個檔案了

**Comment by 29988122** [comment]
Yeah bro, check 1.4.2 latest release

Thanks for the feedback, or I cannot find this simple mistake.

**Comment by aqer** [comment]
1.4.2可以了,感謝解惑！
