### ISSUE TITLE
NA - Taking snapshot of stage recognition bug

### ISSUE THREAD

**Issue by Tenken77777** [29988122/Fate-Grand-Order_Lua#93]
Hi, when the battle starts, the app would take snapshot of stage recognition, and it will always start me out at Battle #2 even though I'm only at Battle #1.  Therefore it always tries to use the second set of autoskills at the beginning of the battle.

**Comment by potchy** [comment]
Couldn't reproduce.
I used the script to farm both Halloween events and it worked fine. Are you sure you're using the latest version? We haven't updated the release tab for a while, so just ignore it and download the source code directly. 

If it still doesn't work, please upload your `_GeneratedStageCounterSnapshot.png` file. Save a copy before the battle starts, wait for the "Taking snapshot" message to appear, save another copy and finally upload both versions.

**Comment by Tenken77777** [comment]
Thanks for the quick reply.

Here is a screenshot of the start of the battle after stage recognition.  I don't know how to generate the _GeneratedStageCounterSnapshot.png file though.  Thanks for helping.  This app is awesome!
![screenshot_2018-11-09-17-23-57](https://user-images.githubusercontent.com/44913261/48297578-d8cb5e00-e460-11e8-80e3-0ce953b468b9.png)
