### ISSUE TITLE
Hi, just a question about emulators.

### ISSUE THREAD

**Issue by iwakoto** [29988122/Fate-Grand-Order_Lua#96]
Hi sorry if I'm not understanding something, but after installing daemon and going to ankulua on Nox I can't select the script.
Because it's invisible without root.
Am I missing something?
Thank you.

**Comment by potchy** [comment]
I'm confused.
Have you got it working or not?

**Comment by iwakoto** [comment]
Hi yes, it was complicated but i figured it out.
you had to drag the files onto nox, then click open PC to see the folder, then drag them again and click open in nox.
then in nox you had to copy the folder, go back in the directory to exit out of the rooted place where the file is placed when you have root, and then paste them in non rooted directory on sd card.
then you open the folder you opened first on pc when dragged on nox and press nx daemon
and then in ankulua you go to the unrooted directory where you made a copy of the folder

but
i installed nox again today new version ver5 and did the same thing
root - move the folder in, copy the folder - activate usb debugging - run nox daemon
but it now says "there is no device detected" so it doesn't work anymore.

**Comment by iwakoto** [comment]
I figured out a workaround, it seems it was happening because i was trying to install it on one of the instances I created in multi drive.
It works after reinstalling.
So I guess it only registers with the very first one, but when you create new emulator instances they aren't recognized.
