### ISSUE TITLE
Add ability to update infinitely

### ISSUE THREAD

**Issue by TryBane** [29988122/Fate-Grand-Order_Lua#97]
Just to allow me to not have to worry about something going wrong, I'd like to be able to make the script loop infinitely until it finds the "Waver + Event CE" That I want while farming. It should be simple to make it so that 0 or -1 is seen as an infinite loop. I'll see if I can do it myself, but I am pretty busy which is why I never got around to implementing the original functionality myself. Much thanks for the one that did though! Glad my suggestions came in handy.

**Comment by potchy** [comment]
I feel like this would introduce unnecessary complexity to the code.
Just use a high number like 99. Chances are that if your preferred support hasn't appeared in 99 tries, it likely won't appear after 9999 tries either.

Alternatively, set both `Support_SelectionMode` and `Support_FallbackTo` to `preferred`.
This will make the script loop indefinitely.
