### ISSUE TITLE
Using Preferred automatically causes an Error

### ISSUE THREAD

**Issue by Rajvir8** [29988122/Fate-Grand-Order_Lua#99]
![image](https://user-images.githubusercontent.com/17600697/48854890-f6fa5d80-ed80-11e8-8510-92024cbdf5c8.png)

I made sure to copy my Nox ADB as usual and it seems to run fine when it comes to booting up AnkuLua

It just doesn't work for some reason.

Any ideas?

**Comment by Rajvir8** [comment]
I did some tests and it seems like my the main problem ended up in my Notepad settings as doing some quick tests shows that if I leave the settings unchanged and update everything then it works.

I'll have to try modifying it again tomorrow when I have more time but at least everything fixed.  Thanks for the Mona Lisa.

 These were the failed settings

--Default, I suggest you not to modify them
dir = scriptPath()
setImagePath(dir)

GameRegion = "EN"
StageCountRegion = Region(1722,25,46,53)

--Temp solution, https://github.com/29988122/Fate-Grand-Order_Lua/issues/21#issuecomment-357257089 
NotJPserverForStaminaRefillExtraClick = 1

--[[Experimental https://github.com/29988122/Fate-Grand-Order_Lua/issues/55 
    UnstableFastSkipDeadAnimation = 1]]

--StaminaRefill
Refill_or_Not = 0
Use_Stone = 0
How_Many = 0

--Support selection possible options: "first"; "preferred"; "manual"
--Please check the details here https://github.com/29988122/Fate-Grand-Order_Lua/blob/master/README.md#autosupportselection
Support_SelectionMode = "preferred"
Support_SwapsPerRefresh = 10
Support_MaxRefreshes = 5
Support_FallbackTo = "manual"
Support_PreferredServants = "Any" --Any number of images separated by commas, if set to "Any" will pick any servant
Support_PreferredCEs = "maid_in_halloween.png" --Any number of images separated by commas, if set to "Any" will pick any craft essence


--[[
AutoSkill:
',' = Turn counter
',#,' = Battle counter
'0' = Skip 1 turn

Servant skill = a b c	d e f	g h i
Master skill = j k l
Target Servant = 1 2 3
Activate Servant NP = 4 5 6

Please insert your command in between the "".

eg:
Skill_Command = "bce,0,f3hi,#,j2d,#,4,a1g3"

Battle 1:
Turn 1 - Servant 1 skill b, c, Servant 2 skill e
Turn 2 - No skill
Turn 3 - Servant 2 skill f on servant 3, Servant 3 skill h, i

Battle 2:
Turn 1 - Master skill j on servant 2, Servant 2 skill d

Battle 3:
Turn 1 - Activate NP servant 1
Turn 2 - Servant 1 skill a on self, Servant 3 skill g on self

Skill_Confirmation: OFF = 0
(When you need to confirm skill use) ON = 1
]]
Enable_Autoskill = 1
Skill_Confirmation = 0
Skill_Command = ""

--When Enable_Autoskill_List = 1, the script starts with a dialogue for you to choose Autoskill setting from one of the predefined list
Enable_Autoskill_List = 1
Autoskill_List = {}
--The folllowing are predefined settings by user
Autoskill_List[1] = "ad,ef,0,0,bc,456"
Autoskill_List[2] = ""
Autoskill_List[3] = ""
Autoskill_List[4] = ""
Autoskill_List[5] = ""
Autoskill_List[6] = ""
Autoskill_List[7] = ""
Autoskill_List[8] = ""
Autoskill_List[9] = ""
Autoskill_List[10] = ""

--You can change card selection priority. For example, BAQ stands for: weak buster->buster->resist buster->weak arts->arts->resist arts->weak quick->quick->resist quick
Battle_CardPriority = "BAQ"

--Whenever there's additional event point reward window to be clicked through, isEvent = 1. Please check the details on github.
isEvent = 1

dofile(dir .. "regular.lua")

**Comment by potchy** [comment]
It was probably an encoding issue then.

**Comment by 29988122** [comment]
Yeah, could be something like cr / crlf

**Comment by Rajvir8** [comment]
Found out that it has something to do with the Support Selection

This isn't working

Support_SelectionMode = "preferred"
Support_SwipesPerUpdate = 10
Support_MaxUpdates = 10
Support_FallbackTo = "first"
Support_FriendsOnly = 0
Support_PreferredServants = "Any"
Support_PreferredCEs = "*mona_lisa.png"

**Comment by Rajvir8** [comment]
Not really sure what to edit to get it to work, there aren't any significantly changed symbols in there.  I'll try removing the _ and see if that helps at all

**Comment by Rajvir8** [comment]
For some reason whenever I change it to Preferred it automatically starts failing.

I have no idea, even if the only thing I do is change it to preferred and not edit anything else.

**Comment by potchy** [comment]
I tried that setting and it worked fine. 🤔

**Comment by 29988122** [comment]
You should really upload the file to let us check if it's really a CR/CRLF
or other editor related issues. Both the working one and the not working
one.

Or it could be an Ankulua / Lua interpreter issue about how strings are
handled.

potchy <notifications@github.com> 於 2018年11月23日 週五 上午1:51寫道：

**Comment by Rajvir8** [comment]
Got it, I'll upload both to MediaFire now.

So this is the normal Fate_EN Regular that comes with the download of a few days ago
http://www.mediafire.com/file/ml3s2sfyl1d9m9k/FGO_EN_REGULAR.lua/file

I have changed nothing and it works fine

But the moment I change it to Preferred and change nothing else the error occurs

Here is a Text File which using causes the error to pop up
http://www.mediafire.com/file/xe4obob0z64r69d/FGO_EN_REGULAR.lua/file

I edited it to Preferred and changed it to Mona Lisa, Any.

I'm currently using Nox, but when I was experimenting with my phone earlier several days ago the error also popped up.  I just assumed it was because it was Android 8.1

**Comment by Rajvir8** [comment]
Interesting, I've always edited it with Normal Notepad so I'm guessing it always happened but Anka Lua must have accepted it before.

Well I've just installed Notepad++ and I'll edit it the fresh working one and give it a shot using only Notepad++ and making sure it's encoded in UTF-8.

That fixed the problem.

Thank you for the help, and thank you for asking for the files.  If you hadn't we wouldn't have discovered the problem.
